### ISSUE TITLE
Promisify the codebase

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator#1006]
Would be nice to cleanup the codebase to use promises instead of callbacks: https://github.com/yeoman/generator/search?utf8=%E2%9C%93&q=cb

For public methods we could support both until the next major version and then remove callback support.

**Comment by addyosmani** [comment]
I'm in support of this. To take it a step further: is your proposal to strictly upgrade the codebase to use promises or are we talking about a shift to async/await as part of this switch away from callbacks?

**Comment by SBoudrias** [comment]
I think that's all our publicly facing API.

For internal methods we should think about what to use instead of `async` for scheduling series of async functions.

**Comment by sindresorhus** [comment]
Woot. I'll take a look later today.

Either Bluebird or https://github.com/sindresorhus/promise-fun/blob/master/readme.md#packages

**Comment by sindresorhus** [comment]
@SBoudrias Looks good. I think we should also deprecate the `this.async()` pattern in favor of saying that something is async if the user returns a promise, otherwise it's sync. This is also an excellent pattern with async/await.

**Comment by addyosmani** [comment]
>  Looks good. I think we should also deprecate the this.async() pattern in favor of saying that something is async if the user returns a promise, otherwise it's sync

I like the idea of deprecating this.async() unless there's strong opposition. Seems like a sensible call for ergonomics.

**Comment by addyosmani** [comment]
@mischah Noticed you added the in-progress label to this one. Are you working on it? :)

**Comment by SBoudrias** [comment]
This made it into 2.0.0
