### ISSUE TITLE
package.json's "files": ["generators"] cause the error "Couldn't find a package.json (or bower.json) file"

### ISSUE THREAD

**Issue by hugojing** [yeoman/generator#1009]
I follow http://yeoman.io/authoring/index.html, built my generator project like this:

```
├───package.json
└───generators/
    └───app/
         └───index.js
         └───other
```

Then set up package.json file like this:

```json
{
  "name": "generator-name",
  "version": "0.1.0",
  "description": "",
  "files": [
    "generators"
  ],
  "keywords": ["yeoman-generator"],
  "dependencies": {
    "yeoman-generator": "^1.0.0"
  }
}
```

When i run:
```bash
$ node --debug `which yo` webpack-babel
```
It's OK.

After I publish my package to npm, I can't install it successfully.

This is ERR INFO:

```bash
$ yarn global add generator-xxxxx
error - Couldn't find a package.json (or bower.json) file in /Users/xxxx/.yarn-cache/npm-generator-xxxxx-0.6.0
```

Finally, I delete `"files": ["generators"]` in  package.json file and succeed!

I wonder if `"files": ["generators"]` cause this error, thanks.

🍺

**Comment by SBoudrias** [comment]
Any chance the cache caused the issue?

**Comment by hugojing** [comment]
I've been cleared npm/yarn's cache.

I will test again tomorrow.

Thanks for your reply.

**Comment by hugojing** [comment]
I found the reason!

Because I use `yarn publish`!

`npm publish` always included these files:

```
package.json
README (and its variants)
CHANGELOG (and its variants)
LICENSE / LICENCE
```

So we can write `"files": ["generators"]` in package.json.

But `yarn publish` will ignore every unspecified file.

Perhaps we should suggest everyone to write `"files": ["generators", "package.json", "README", "CHANGELOG", "LICENSE", "LICENCE"]` to compatible with yarn. What do you think?

🍺

**Comment by mischah** [comment]
Thanks for reporting. 

> Perhaps we should suggest everyone to write "files": ["generators", "package.json", "README", "CHANGELOG", "LICENSE", "LICENCE"] to compatible with yarn. What do you think?

Where should we write that? I'm not sure if this piece of information is too specific to land in Yeoman docs.
