### ISSUE TITLE
Is there a way to detect when a group of this.fs commands have completed?

### ISSUE THREAD

**Issue by nessthehero** [yeoman/generator#1010]
I'm trying to use this.spawnCommand to run a shell script after I copy a bunch of files from the node_modules directory. However, the command ends up running before the files are finished copying over.

Is there a way to force the script to wait until the files are copied before running additional commands?

Here's the code in question:

```node
install() {
	this.installDependencies({
		skipInstall: this.options['skip-install'],
		skipMessage: this.options['skip-install-message'],
		bower: false
	});
}

end() {

	// Copy over the BarkleyREI stuff
	this.log('Now we copy over all the BarkleyREI sub-repos...');

	// brei-sass-boilerplate
	this.fs.copy(
		this.destinationPath('node_modules/brei-sass-boilerplate/**/*'),
		this.destinationPath('app/sass/')
	);

	// brei-sass-mixins
	this.fs.copy(
		this.destinationPath('node_modules/brei-sass-mixins/*.scss'),
		this.destinationPath('app/sass/helpers/mixins/')
	);

	// brei-grunt-config
	this.fs.copy(
		this.destinationPath('node_modules/brei-grunt-config/**/*'),
		this.destinationPath('app/')
	);

	// brei-assemble-structure
	this.fs.copy(
		this.destinationPath('node_modules/brei-assemble-structure/**/*'),
		this.destinationPath('app/assemble/')
	);

	// brei-assemble-helpers
	this.fs.copy(
		this.destinationPath('node_modules/brei-assemble-helpers/*.js'),
		this.destinationPath('app/assemble/helpers/')
	);

	// Delete crap we don't need

	this.fs.delete(
		this.destinationPath('{app/assemble,app/sass,grunt-config}/**/*/{README.md, .gitkeep}')
	);

	this.spawnCommandSync('sh', ['post.sh']);

	//

	if (this.options['skip-install']) {
		this.log(yosay(
			'Make sure to run `npm install` and `bower install` to install all your dependencies! Happy coding!\n\n' +
			'Generated with v' + this.pkg.version
		));
	} else {
		this.log(yosay(
			'Happy coding!\n\n' +
			'Generated with v' + this.pkg.version
		));
	}

	return;

}
```

**Comment by Toddses** [comment]
I'm a fan of promises, and have used promises to accomplish this, via the [fs-promise](https://www.npmjs.com/package/fs-promise) library. Brief example:

```js
const fsp = require('fs-promise');

let p1, p2 = null;

p1 = fsp.copy(fileA, fileB);
p2 = fsp.copy(fileC, fileD);

Promise.all([p1, p2]).then(() => {
  // do stuff
});
```

**Comment by mischah** [comment]
Hej @nessthehero 

> Is there a way to force the script to wait until the files are copied before running additional commands?

Yup. Check the description of »The run loop« in the [authoring docs](http://yeoman.io/authoring/running-context.html).

I would recommend writing your files within the `writing` phase 😏

**Comment by nessthehero** [comment]
@Toddses Thanks! I'll give that a try later (probably tomorrow) and report back.

@mischah The thing is, the files I'm trying to copy are downloaded in the `install` phase, which happens after the `writing` phase.

I'm applying the defacto mentality that's been set down since yeoman-remote was removed, in that I am putting dependencies into npm and copying them over from node_modules. Since writing happens before install, I can't copy files that don't exist yet.

I tried changing to the other format:
```
Generator.extend({
  priorityName: {
    method() {},
    method2() {}
  }
});
```

but I couldn't get it to work. If someone has a working example of that format with multiple phases, I'd be grateful.

**Comment by mischah** [comment]
Mhmm. Sounds weird. 

Why don’t you add those modules as dependencies to your generator?
In that case they would be available with your generator. 

Couldn’t you use `generator.sourceRoot('./node_modules')` in that case? See http://yeoman.io/authoring/file-system.html

… Just throwing in ideas.

**Comment by mischah** [comment]
P.S.

Better post this kind of questions in the [Gitter](https://gitter.im/yeoman/yeoman) chat. Chances are high that more people are getting your question over there.

**Comment by nessthehero** [comment]
That might not be a bad idea. I'll consider that.

I knew about the Gitter but I didn't have the immediate time to explain my issue and maintain attention to the chat, but I'll try that next time.

Thanks for both your help on this.

**Comment by SBoudrias** [comment]
To handle files on disk, you'll need to spawn your command in the `end` phase. Before that, all files lives in the in-memory file system.
