### ISSUE TITLE
Generator.argument type Number won't work

### ISSUE THREAD

**Issue by pauloallex24** [yeoman/generator#1012]
Hi.
I've this:
            `this.argument('version', {type: Number, required: true});`
And if I run on terminal `yo project:new T` that was supposed to fail (because "T" is not a number), it won't fail. I've readed on the documentation that I can use algo a function instead of Number or String but I just can't get it work. Any ideias?

If I just run `yo project:new` I get the error of missing the argument.

Regards

**Comment by SBoudrias** [comment]
Ah yes, this type doesn't validate. It'll just run `Number('t')` which will return `NaN`.

You can implement your own function:

```js
this.argument('version', {
    type: (val) => {
        const num = Number(val);
        assert(!isNaN(num), 'version can only be a number');
        return num;
    },
    required: true
});
```

We should probably do the validation of number in the core library. I think that was just an oversight. If you feel like fixing it, that's the function you'd want to modify https://github.com/yeoman/generator/blob/master/lib/index.js#L259

**Comment by pauloallex24** [comment]
Oh, right. Now it makes sense! Thanks.
For me, the assert just work fine. 
Regards
