### ISSUE TITLE
Adding my own custom generator to yeoman generators list

### ISSUE THREAD

**Issue by PoojaAg18** [yeoman/generator#1019]
I have added my code to both the places 

https://github.com/PoojaAg18/generator-drupal-module-theme
https://www.npmjs.com/package/generator-drupal-module-theme

Still I can't see my generator under yeoman generators, Please help with the same

Thanks!

**Comment by SBoudrias** [comment]
The search is not instant. It's a batch running every few hours.

I see your generator in the list now; there's just some missing stats right now. The npms service needs to analyze it first, that might take a few more hours.
