### ISSUE TITLE
Any way to register a custom prompt with Inquirer?

### ISSUE THREAD

**Issue by purtuga** [yeoman/generator#1020]
I would like to use custom prompt ([inquirer-directory](https://github.com/nicksrandall/inquirer-directory)), but can't see a way to register the custom prompt with the instance of Inquirer used by Generator... Any tips?

**Comment by SBoudrias** [comment]
This isn't really possible. Yeoman strive to support many interfaces (editors, GUI, headless, etc) and to do so, we need to restrict the type of Inquirer prompt supported.

**Comment by purtuga** [comment]
hi @SBoudrias - Thank you for the quick response... 
I was looking at yeoman/environment... Do you think I might (on my own) still be able to achive this using yeoman/environment and the [TerminalAdapter](http://yeoman.io/environment/TerminalAdapter.html)?

**Comment by SBoudrias** [comment]
You could probably hack your way in somehow. But that's not a public API, so it could break on minor release.

**Comment by purtuga** [comment]
Oh... I see.. Then never mind... :) I guess I'll just find another solution... 
thanks again for your response.
