### ISSUE TITLE
Copy error when using opposite glob patterns

### ISSUE THREAD

**Issue by codekraft-studio** [yeoman/generator#1022]
I've this situation where I use:
```javascript
// Copy and render all the script files
this.fs.copyTpl(
      this.templatePath('theme/**/+(*.js|*.php)'),
      this.destinationPath('src/'),
      this.props,
      {sync: true}
);
// Simple copy all the rest
this.fs.copy(
      this.templatePath('theme/**/!(*.js|*.php)'),
      this.destinationPath('src/'),
      {sync: true}
);
```

If I run these functions individually they work, when I run them together they stop working and throw this error: `Trying to copy from a source that does not exist: ....\theme\**\+(*.js|*.php)`

__If I comment the second function the first one works and vice versa.__

How can I debug this? I've no clue of what is going on.. at first I thought of a async problem than I added `{sync: true}` as per [node-glob documentation](https://github.com/isaacs/node-glob#options) even if is deprecated.. hoping that will work.. and it doesn't.

Can someone help me?
Many thanks in advance.

**Comment by SBoudrias** [comment]
Probably has something to do with how mem-fs-editor loads file into the mem-fs instance. It might assume the folder exists in memory, so it skips the disk operation (and doesn't find any file matching the second pattern given we've only matched those matching the first)

**Comment by codekraft-studio** [comment]
@SBoudrias I thought the same but unfortunatelly If I try to copy png,jpg,gif files or any other image files it fails with this: "Can't find the closing tag <%", I already tested it, that's why I used this approach to copyTpl all the scripts and simply copy all the rest, how can I solve this problem?

Thank you for the quick response!

**Comment by SBoudrias** [comment]
You can also separate templates and other files in different folders. Not ideal, but that's a work around.

**Comment by codekraft-studio** [comment]
Basically I'm already doing this if you want to take a look to the project: https://github.com/codekraft-studio/generator-wordpress-starter/tree/features/custom-template

The `theme` folder has the WordPress theme in it, while the `grunt` and `gulp` folder has the separate package.json and gulp/grunt file templates. see [here](https://github.com/codekraft-studio/generator-wordpress-starter/tree/features/custom-template/generators/app/templates)

It's possible to wait until the first copyTpl function has done?  So I can allow the user to dinamically generate any template he wants without being tied to a particular folder structure, the theme/ folder is already required for this to work, all the theme files should be put there.

I don't know if I explained well..

I tried to use the sync property but I don't know if is still working, since is deprecated as option.

**Comment by codekraft-studio** [comment]
Maybe I've a hint about the solution, but I'm not able to figure it out, the actual script is doing [this](https://github.com/codekraft-studio/generator-wordpress-starter/blob/features/custom-template/generators/app/index.js#L14-L32):

```javascript
this.fs.copyTpl(
      this.templatePath('theme/**/*.{js,php,css,scss}'),
      this.destinationPath('src/'),
      this.props
);

this.fs.copy(
      this.templatePath('theme/**/*.{png,gif,jpg}'),
      this.destinationPath('src/')
);
```

And is currently working but this patterns, not:

```javascript
// Copy and render all the script files
this.fs.copyTpl(
      this.templatePath('theme/**/+(*.js|*.php)'),
      this.destinationPath('src/'),
      this.props
);
// Simple copy all the rest
this.fs.copy(
      this.templatePath('theme/**/!(*.js|*.php)'),
      this.destinationPath('src/')
);
```

They are acting on the same folder, but on different files in the first case.
Is mem-fs loading all files and than apply the glob or what? I'm trying to figure it out which are the steps involved.

Thanks again.

**Comment by mischah** [comment]
This is something which can be closed, right?
