### ISSUE TITLE
Update yeoman-environment dependency to latest (v1.6)

### ISSUE THREAD

**Issue by blikblum** [yeoman/generator#1024]
While debugging one issue with `inquirer` in the generator i'm developing, i realized that the latest published `yeoman-generator` package depends on an outdated `yeoman-environment` version (1.1) which in your turn depends in an outdated `inquirer` version. 

This is important because the [yeoman docs](http://yeoman.io/authoring/user-interactions.html) points to inquirer documentation and some features listed there are not present in the inquirer version currently shipped with `yeoman-generator`

**Comment by SBoudrias** [comment]
1.6 is in our package.json yeoman-environment target range. You'll get the latest installed when you install yeoman-generator.

Learn a bit more about semver and how it's used with npm: https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by blikblum** [comment]
Sorry i missed that in fact the 1.6.6 environment release was done before inquirer version was bumped 4 months ago. Seems i need to wait a new environment release
