### ISSUE TITLE
Freez during generator questions

### ISSUE THREAD

**Issue by kiiroule** [yeoman/generator#1025]
Hi,

I tryed to launch jhipster and when the first question appears, my computer is freezing.
I see the same thing when i launch yo, i can't select which generator to upgrade.

yeoman version 2.0.0
jhipster version 4.5.3

**Comment by SBoudrias** [comment]
This is likely one of two issues:

1. The terminal you're using is not a TTY. Make sure you used cmd.exe or PowerShell
2. If you're using Node 8.1, they've release a bug breaking TTY. You'd need to downgrade until they release the fix.

**Comment by kiiroule** [comment]
Yes, i was using the 8.1 node version.
I downgrade to 6.1 and now it's workig, thanks a lot
