### ISSUE TITLE
Yeoman generators freeze with Node 8.1.0

### ISSUE THREAD

**Issue by raymondfeng** [yeoman/generator#1026]
We are experiencing the issue with multiple yeoman generators that freeze at certain prompts with Node 8.1.0. There is no problem with Node 8.0.0.

Two examples we tried:
- https://github.com/yeoman/generator-node
- https://github.com/strongloop/generator-loopback

See https://github.com/strongloop/loopback-cli/issues/36

**Comment by Toddses** [comment]
#1025 seems like it's related.

**Comment by raymondfeng** [comment]
Close it as dup of https://github.com/nodejs/node/issues/13557
