### ISSUE TITLE
this.appname always set to my personal directory,can't change

### ISSUE THREAD

**Issue by 995270418L** [yeoman/generator#1029]
whatever i am in to use command 'yo myProject', the this.appname always be same ( /home/name in my computer ) . how  do  i set the this.appname to be my command line floder. like pwd in bash shell

**Comment by SBoudrias** [comment]
Any chance you have a `.yo-rc.json` file in your home dir?

**Comment by 995270418L** [comment]
thank you , yes，and after i delete it， this.appname be changed，why do it make sense when i change the floder to generator myproject?

**Comment by SBoudrias** [comment]
The `.yo-rc.json` file points Yeoman to the root of a project. So if you accidentally run a generator in your root directory, it'll create a file there and Yeoman will always think that's where your project lives.
