### ISSUE TITLE
yarn global add yo doesn't work with links

### ISSUE THREAD

**Issue by appsforartists** [yeoman/generator#1032]
I expected this to work:

```
cd generator-i-made
yarn global add yo
yarn link
```

but `yo` doesn't find the generator.  NPM works.

I suspect this is the problem:

```
~/.config/yarn/global/node_modules/yo
~/.config/yarn/link/generator-i-made
```

I'm running yarn@0.28.1 and yo@2.

**Comment by SBoudrias** [comment]
Indeed, Yeoman doesn't search the yarn link paths. It'd be easy to add around here: https://github.com/yeoman/environment/blob/master/lib/resolver.js#L106
