### ISSUE TITLE
Option of { type: Array, default: [] } defaults to array of array instead of just array

### ISSUE THREAD

**Issue by ianwalter** [yeoman/generator#1036]
``` js
import Generator from 'yeoman-generator'

export default class extends Generator {
  constructor (args, opts) {
    super(args, opts)
    const defaultLines = ['node_modules', '*.log', '.DS_Store']
    this.option('gitignoreLines', { type: Array, default: defaultLines })
  }

  writing () {
    console.log('OPTIONS', this.options)
    const src = this.templatePath('gitignore')
    this.fs.copyTpl(src, this.destinationPath('.gitignore'), this.options)
  }
}
```

Actual result of console output is:

``` bash
# ...
gitignoreLines: [ [ 'node_modules', '*.log', '.DS_Store' ] ] }
```

Expected result of console output is:

``` bash
# ...
gitignoreLines: [ 'node_modules', '*.log', '.DS_Store' ] }
```

If I register `gitignoreLines` as an argument instead of an option, it works as expected.

**Comment by SBoudrias** [comment]
Looks like a valid bug. Help welcomed to fix it!

**Comment by mrDinckleman** [comment]
In accordance to documentation, Array is not a supported type for the option, so there is no bug.

> `type` Either Boolean, String or Number (can also be a custom function receiving the raw string value and parsing it)
> -- http://yeoman.io/authoring/user-interactions.html

**Comment by SBoudrias** [comment]
Thanks @mrDinckleman, rechecking this issue seems like that's the case. The `type` really is a function processing the input received. So passing an Array in would indeed wrap it up inside an extra array.

In this case I'd suggest passing a string with a known delimiter (e.g. `.split(',')`)
