### ISSUE TITLE
Debug package has vulnerability. NSP fails

### ISSUE THREAD

**Issue by MylesBorins** [yeoman/generator#1039]
Looks like 3.0.1 is vulnerable. Likely need to update to 3.1.0

There is also a vulnerable version in yeoman-environment.

I'll send patches

**Comment by MylesBorins** [comment]
Looks like simply updating the package-lock.json file will fix the problem with regards to vulnerable deps

**Comment by SBoudrias** [comment]
Fixed for both generator and environment. Thanks for the report :)
