### ISSUE TITLE
file conflict resolutions

### ISSUE THREAD

**Issue by avergos29** [yeoman/generator#1040]
Hi,
Is it possible to modify the conflicter to use a custom merge tool in case of a conflict ?
If not, do you plan to make it possible in the future ?
Thanks

**Comment by guilhermevrs** [comment]
I would definately vote for a feature like that. Today is either all of ours or all of theirs. But what happens when we have to keep stuff from both?

**Comment by SBoudrias** [comment]
Hey @avergos29, we're open to receiving a PR adding this feature. Let me know if you need pointer to get started.

**Comment by guilhermevrs** [comment]
Hi @SBoudrias, I would definitely like a feature like that.

Can you give me a pointer to get started? I would like to try a few ideas on the subject

**Comment by SBoudrias** [comment]
@guilhermevrs of course! I think you'd want to modify this file: https://github.com/yeoman/generator/blob/master/lib/util/conflicter.js#L138

I'd assume we should add a new option to the list; maybe "Resolve manually". And when we select this, we should generate a diff content and send this to the diff resolution tool (this is usually defined as an ENV variable on users OS)

As to passing the content, you might need to generate a temporary file and watch for changes to detect once the conflict is resolved. You might be able to grab some inspiration (or reuse) from https://github.com/mrkmg/node-external-editor
