### ISSUE TITLE
Please update your docs - very confusing for new folks

### ISSUE THREAD

**Issue by jasonmacdonald** [yeoman/generator#1041]
Your docs say to use generator-generator to get started, and all the API docs are for v2, but generator-generator installs yeoman-generator v1. Makes for a VERY confusing time trying to just get started. You should probably remove the line about using "generator-generator".

**Comment by mischah** [comment]
Hej @jasonmacdonald Sorry that you have a confusing start with generating a generator and thanks for pointing out that issue.

I’m going to fix that by updating generator-generator instead of changing the docs.

See https://github.com/yeoman/generator-generator/issues/205

**Comment by mischah** [comment]
@jasonmacdonald I’ve just updated `yeoman-generator ` to v2 in `generator-generator`

See https://github.com/yeoman/generator-generator/pull/206/files

But I wonder which problems you encountered since I hadn’t to change a single of code 🤔 

Feedback is appreciated.
