### ISSUE TITLE
Generator throwing error that bower.json isn't present

### ISSUE THREAD

**Issue by chiragbhansali** [yeoman/generator#1042]
I am creating a custom generator that has a few folders with some files. However, when I run the generator after linking it with `npm link`, Yeoman throws an error that bower.json is not present.  After I added the bower.json and ran it, the folders and the files were not copied. The point is a project doesn't have any front-end dependencies, why should I install Bower?

**Comment by SBoudrias** [comment]
You should open a ticket on the generator you tried to use.

As you might image, with over 5000 generators, the core team cannot maintains all of them.
