### ISSUE TITLE
Trying to run a gallery with JQuery twenty twenty, it is one where you have a before and after image, but only the before displays, all other functionality seems to be there ie. the image, pointer to click etc...please help !

### ISSUE THREAD

**Issue by eddymufc** [yeoman/generator#1046]
I feel like the issue is with link hrefs or at the end where i call in the jquery/js etc, maybe a conflict or versions ? i have all the correct files in my css and images folder

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Bootstrap 101 Template</title>

    
    <link href="css/bootstrap.min.css" rel="stylesheet">
    
    <script src="https://use.fontawesome.com/50bb896089.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link rel="stylesheet" href="css/novstyle.css">
    <link href="css/foundation.css" rel="stylesheet" type="text/css" />
    <link href="css/twentytwenty-no-compass.css" rel="stylesheet" type="text/css" />
    <link href="css/twentytwenty.css" rel="stylesheet" type="text/css" />
    </head>

 <div class="large-12 columns">
                    <div class="large-3 columns">
                        <p>Soda</p>
                        <div class="twentytwenty-container">
                            <img src="images/Dog5Before.jpg" />
                            <img src="images/Dog5After.jpg" />
                        </div>
                    </div>
                    <div class="large-3 columns">
                        <p>Noodle</p>
                        <div class="twentytwenty-container">
                            <img src="images/Dog4Before.jpg" />
                            <img src="images/Dog4After.jpg" />
                        </div>
                    </div>
                    <div class="large-3 columns">
                        <p>Lola</p>
                        <div class="twentytwenty-container">
                            <img src="images/Dog3Before.jpg" />
                            <img src="images/Dog3After.jpg" />
                        </div>
                    </div>
                    <div class="large-3 columns">
                        <p>Izzy</p>
                        <div class="twentytwenty-container">
                            <img src="images/Dog2Before.jpg" />
                            <img src="images/Dog2After.jpg" />
                        </div>
                    </div>
                </div>

                <div class="large-12 columns">
                    <br />
                    <br />
                    <div class="large-3 columns">
                        <p>Charlie</p>
                        <div class="twentytwenty-container">
                            <img src="images/Dog7Before.jpg" />
                            <img src="images/Dog7After.jpg" />
                        </div>
                    </div>
                    <div class="large-3 columns">
                        <p>Yasmin</p>
                        <div class="twentytwenty-container">
                            <img src="images/Dog8Before.jpg" />
                            <img src="images/Dog8After.jpg" />
                        </div>
                    </div>
                    <div class="large-3 columns">
                        <p>Cody</p>
                        <div class="twentytwenty-container">
                            <img src="images/Dog1Before.jpg" />
                            <img src="images/Dog1After.jpg" />
                        </div>
                    </div>
                    <div class="large-3 columns">
                        <p>Molly</p>
                        <div class="twentytwenty-container">
                            <img src="images/Dog6Before.jpg" />
                            <img src="images/Dog6After.jpg" />
                        </div>
                    </div>
                </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    
    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
    <script src="js/jquery.event.move.js"></script>
    <script src="js/jquery.twentytwenty.js"></script>
    <script>
        $(function() {
            $(".twentytwenty-container[data-orientation!='vertical']").twentytwenty({
                default_offset_pct: 0.7
            });
            $(".twentytwenty-container[data-orientation='vertical']").twentytwenty({
                default_offset_pct: 0.3,
                orientation: 'vertical'
            });
        });

    </script>

**Comment by SBoudrias** [comment]
Hey, please open issues related to specific projects on the repository of the specific generator you used.

This repository is dedicated to the generator system implementor use to create new generators.
