### ISSUE TITLE
Simple Templating Language

### ISSUE THREAD

**Issue by clemtrek** [yeoman/generator#1047]
It would be very convinient if support for another templating language such as handlebars or nunjucks was added

**Comment by mischah** [comment]
It’s possible for you to add another template engine. See these examples:
- https://www.npmjs.com/package/yeoman-handlebars-engine
- https://www.npmjs.com/package/yeoman-hoganjs-engine

_Both seem pretty unmaintained_ 😞 

The main advantage of using of using the backed in `EJS` like template engine is, that you have all the power of JS available in your templates.

**Comment by mischah** [comment]
It seems that this option is gone.

After digging through the sources I remembered that the ejs template engine comes with the direct dependency to [mem-fs-editor](https://github.com/SBoudrias/mem-fs-editor).

And this is pretty much baked in.

Sorry.

**Comment by SBoudrias** [comment]
That being said, we're only reading and writing strings to files. So it'd be easy to process your templates yourself if you so wish (you could even create your own base class with a utility function to do so).

**Comment by clemtrek** [comment]
Thanks.
