### ISSUE TITLE
"Group Multiple Methods" syntax does not work with class definition

### ISSUE THREAD

**Issue by gavinr** [yeoman/generator#1048]
In [v2.0](https://github.com/yeoman/generator/releases/tag/v2.0.0), it says 

> Generator.extend() is replaced in favor of `class extends Generator {}`

So there is no way to use `Generator.extend()` anymore, but in the doc it says: 

![image](https://user-images.githubusercontent.com/209355/33091553-0eea074e-cebd-11e7-8474-78e40a81dc46.png)
(http://yeoman.io/authoring/running-context.html)

So seems like it's impossible to use the "Group Multiple Methods" syntax if you're using v2.0 or greater. Is this correct?

**Comment by SBoudrias** [comment]
Good question. Likely not possible unless you manually add an object to the prototype maybe?
