### ISSUE TITLE
fs.append causes a conflict

### ISSUE THREAD

**Issue by evil-shrike** [yeoman/generator#1049]
If a generator copies a file and then tries to add more content into it there will be a conflict
```
this.fs.copyTpl(this.templatePath('_appsettings.json.properties'), 'appsettings.json.properties', this);

// later 
this.fs.append('appsettings.json.properties', 'DATA_SOURCE=db');
```
User will be prompted:
```
 conflict appsettings.json.properties
? Overwrite appsettings.json.properties? overwrite
    force appsettings.json.properties
```

It's completely misleading as actually there's no any conflict. The file didn't exist before the run. It's just adding more content in the same session.

**Comment by Cyborg572** [comment]
I'm running into this same problem. I'm trying to clone a repository, and then append some values from the generator options. 

My workaround, for now, is to use `spawnCommand` to run the git clone, read the contents of the file I  want to append to, use `spawnCommand` to delete it,  and then then `this.fs.write` to write the file with added values. Oddly enough if I use `this.fs.delete`, it still throws the conflict.

**Comment by bichenkk** [comment]
@evil-shrike 
Here is my solution. I try to read again and concat the content, and finally write all over again.
```
      const originalContent = fs.readFileSync(this.destinationPath('', 'src/content.js'), 'utf8');
      const toAppendContent = this.fs.read(this.templatePath('add_content'), 'utf8')
      fs.writeFile(this.destinationPath('', 'src/content.js'), originalContent.concat(toAppendContent), function (err) {
        if (err) return console.log(err);
      });
```
