### ISSUE TITLE
Insecure dependencies

### ISSUE THREAD

**Issue by binduwavell** [yeoman/generator#1050]
It appears we have some insecure dependencies in `yeoman-generator` version 2.0.1:

https://www.bithound.io/github/binduwavell/generator-alfresco/master/dependencies/npm/yeoman-generator

This also affects `yeoman-test` as it depends on `yeoman-generator`.

Here is the security alert:

https://snyk.io/vuln/npm:shelljs:20140723?utm_source=bithound

From reading through GitHub issues I think this is planned to be resolved in shelljs 0.8...

**Comment by vvanmol** [comment]
Hello, 

shelljs was updated to 0.8.x which fixes the the command injection vulnerability.  Any plan to update yeoman to include that new version ?

Thanks !

**Comment by SBoudrias** [comment]
@vvanmol want to send a PR?

**Comment by vvanmol** [comment]
Here you go @SBoudrias  ;-)

I only updated a couple of dependency versions in the package.json.  There doesn't seem to have any impact on your application (all tests are in success without any changes).

**Comment by ev1stensberg** [comment]
https://github.com/shelljs/shelljs/pull/524

**Comment by mshima** [comment]
Looks like this is fixed.
