### ISSUE TITLE
Prompting fails when a question type: "checkbox" supply choices as a function

### ISSUE THREAD

**Issue by ryanvanoss** [yeoman/generator#1051]
```
yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)' && cat Gruntfile.js
2.0.0
darwin { http_parser: '2.7.0',
  node: '7.10.1',
  v8: '5.5.372.43',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
cat: Gruntfile.js: No such file or directory
```

Specifically, `getCheckboxDefault` in [prompt-suggestion.js:22:32](https://github.com/yeoman/generator/blob/master/lib/util/prompt-suggestion.js#L21) throws _"TypeError: question.choices[Symbol.iterator] is not a function"_ .

This is simple to reproduce. I added some unit tests to verify. See [ryanvanoss/generator 989bb34](https://github.com/ryanvanoss/generator/commit/989bb34c51b434f94fabcc73a707218a48a7926e), or simply pull into your own repo:

```sh
git remote add ryanvanoss https://github.com/ryanvanoss/generator.git
git pull ryanvanoss checkbox-functions
```

The fix, I imagine, will be more involved... This line is invoked [prior to prompting](https://github.com/yeoman/generator/blob/master/lib/index.js#L152-L153) in order to honor the `store` property that Yeoman adds to questions, but [Inquirer's API](https://www.npmjs.com/package/inquirer#questions) will pass the answers from the previous questions to the choices function.

**Comment by SBoudrias** [comment]
Oh good find.

I guess we'd need to ignore filling in the default if the choices are passed as a function rather than a function.

Would you send us a PR? Seems you found all the relevant piece of code already :)

**Comment by ryanvanoss** [comment]
Absolutely. I'll get something to you today.
