### ISSUE TITLE
No info about withLocalConfig in testing documentation

### ISSUE THREAD

**Issue by lukasz-galka** [yeoman/generator#1053]
Hi, there is no info about `withLocalConfig` in http://yeoman.io/authoring/testing.html 
initial issue https://github.com/yeoman/generator/issues/742

**Comment by SBoudrias** [comment]
Would you like to send a PR? We'd be happy to get some help here

**Comment by lukasz-galka** [comment]
done, https://github.com/yeoman/yeoman.github.io/pull/751
