### ISSUE TITLE
Should allow `-` as part of directory name

### ISSUE THREAD

**Issue by taoning2014** [yeoman/generator#1054]
When init project using `yo`, `determineAppname` is used to set default project name as the current directory name. However if the directory name is `bar-foo`(open `node_modules` of any project, you will find this name convention is quite usual than `bar_foo`). The following regex will replace `-` with space. Recommend change `/[^\w\s]+?/g` to `/[^\w\s-]+?/g`

https://github.com/yeoman/generator/blob/150053c6ab496809d0a96ce0d323a8e1f57bcf31/lib/index.js#L647

**Comment by SBoudrias** [comment]
I'm not sure how I feel about changing that because it's kind of always been this way. Would it make sense for you to reassign this value yourself? In theory, there's nothing forcing you to use `this.appname` directly.
