### ISSUE TITLE
Props are not accessible for choices attribute?

### ISSUE THREAD

**Issue by aposidelov** [yeoman/generator#1059]
Hey, I need the choices to be depended on other prompts but it seems that I don't have an access to 'this' and 'props' inside the callback. You can see example below where I want to have an access to moduleName prompt value from 'choices' callback but props is undefined and this.log doesn't work:
```

let configMenuPrompts = [
    {
        type: 'input',
        name: 'moduleName',
        message: 'Enter machine module name',
        default: ''
    },
    {
        type: 'list',
        name: 'configMenu',
        message: 'Pick config menu for module...',
        choices: function(props) {
            this.log(props);  <<-- error here 'this' doesn't have log function
            let m = props.moduleName;  <-- error here 'props' is undefined
        },
        default: 'user-interface',        
    }
];
```
If I try to use the same callback for 'default' or 'when' everything works OK

**Comment by mischah** [comment]
Hej @aposidelov,

you can access the answers within the `choices` function like described here: https://github.com/SBoudrias/Inquirer.js/#objects

I’m not sure that I understand your use case, but here is a working example:

```javascript
const configMenuPrompts = [
  {
    type: 'input',
    name: 'moduleName',
    message: 'Enter machine module name',
    default: ''
  },
  {
    type: 'list',
    name: 'configMenu',
    message: 'Pick config menu for module...',
    choices: function(answers) {
      const choices = ['user-interface'];
      console.dir(answers);
      choices.push(answers.moduleName);
      return choices;
    },
    default: 'user-interface'
  }
];
```

Cheers, Michael

P.S. Please ask support questions in our [Gitter](https://gitter.im/yeoman/yeoman) chat.

**Comment by aposidelov** [comment]
@mischah it works! thank you
