### ISSUE TITLE
Is there a way to ignore selective ejs templating while copying a file with copyTpl method?

### ISSUE THREAD

**Issue by krgowtham** [yeoman/generator#1061]
I'm using Gruntfile.js where I have multiple templating syntax. I want to replace only selective template syntax (not all) in the file. Is there a way to achieve this using copyTpl method?

**Comment by mischah** [comment]
Yo, you have to »escape« placeholders like over here:
https://github.com/micromata/generator-bootstrap-kickstart/blob/db2e1896a74f5c40d50b38cc36a51ea32a26a856/app/templates/_Gruntfile.js#L47

Cheers, Michael
