### ISSUE TITLE
Binary files copied incorrectly using copyTpl.

### ISSUE THREAD

**Issue by Lighttree** [yeoman/generator#1062]
In case your template folder contains binary file (I was working with `.png`) these files might be corrupted at destination. For example `.png`s fail generation at all _or_ copied as empty files.

```
writing() {
    this.fs.copyTpl(
        this.templatePath(),
        this.destinationPath(),
        this.props
    );
}
```

I think the problem is in old version of `mem-fs-editor` used:
https://github.com/yeoman/generator/blob/master/package.json#L51

this implementation runs `ejs` compiler over binary files and fails there since it might find something that looks like `<%` (`ejs` template syntax).

This seems to be fixed in latest version of `mem-fs-editor` since they added `isBinary` check:
https://github.com/SBoudrias/mem-fs-editor/blob/master/lib/actions/copy-tpl.js#L9

**Comment by koppor** [comment]
Still happens with `4.9.0`. In my concrete case, I could swtich to `copy` as there was no need to modify the binary file.
