### ISSUE TITLE
SpawnCommand and SpawnCommandSync don't allow overriding stdio options

### ISSUE THREAD

**Issue by genepaul** [yeoman/generator#1064]
SpawnCommand and SpawnCommandSync force the stdio options to `inherit`, which basically removes any ability for generator authors to spawn a sub process and capture the results for use in the generator. An example of this is to see whether the user has the latest version of the generator by spawning `npm show my-module version` and capturing the results from that to compare against package.json. Was there a reason for forcing that and not allowing the author to decide?

https://github.com/yeoman/generator/blob/master/lib/actions/spawn-command.js#L20

**Comment by SBoudrias** [comment]
`stdio: inherit` is the default, you should be able to overwrite it.

**Comment by genepaul** [comment]
Right, I misunderstood how `_.defaults` works. I ended up doing things differently anyway, but thanks for the response!
