### ISSUE TITLE
When extending a generator, methods on the superclass are ignored

### ISSUE THREAD

**Issue by rictic** [yeoman/generator#1065]
Consider this code:

```javascript
const Generator = require('yeoman-generator');
class BaseGenerator extends Generator {
  prompting() {
    // customised prompt
  }
}

class MyGenerator extends BaseGenerator {
  // implements other methods but does not implement prompting
}
```

This does not work, BaseGenerator's `prompting` method is not called when MyGenerator is run. The fix is to do:

```javascript
class MyGenerator extends BaseGenerator {
  prompting() {
    return super.prompting();
  }
}
```

It looks like the reason for this is that method names are only counted if they're on the prototype of the generator directly. I'd argue that this is pretty surprising behavior, but it seems like it was done fairly deliberately, perhaps for historical reasons?

**Comment by SBoudrias** [comment]
Yes, this is the way it is for mainly historical reason. That's how it was initially implemented. The documentation state this behavior:

> In other words, each function on the object returned by `Object.getPrototypeOf(Generator)` will be automatically run.
> http://yeoman.io/authoring/running-context.html

I don't think we'll consider changing this behavior now, but I hope this clarifies the behavior. Let us know if you need further help!
