### ISSUE TITLE
yo breaks my sh/bash scripts

### ISSUE THREAD

**Issue by daggerok** [yeoman/generator#1068]
Hi,

I usually copy gradle / maven wrappers to my generator java project, and it worked perfectly fine in past. Since last time I have updated generator with newer wrapper, and now these scripts doesn't work at all - seems like end of line/file or something other was changed during copying/generation (chmod +x doesn't help, so issue not with file permission)

for example, after project generator

```bash
bash mvnw
: command not found
: command not found
'vnw: line 53: syntax error near unexpected token `in
'vnw: line 53: `case "`uname`" in
```

in mvnw file, line 53 is: `case "`uname`" in`

```bash
chmod +x mvnw
./mvnw
bash: ./mvnw: /bin/sh^M: bad interpreter: No such file or directory
```

To make wrapper scripts work again I have to completely re-generate them

Is that a bug or expected behavior?

---
Regards,
Max

**Comment by SBoudrias** [comment]
Can you paste the content of your script? Right now there's not enough details for me to be able to help you.

If it's a copy problem, then we should identify the character who's wrongly replaced first.

**Comment by SBoudrias** [comment]
In the case of `mvnw`, the error you printed is telling us that `/bin/sh` is not a valid interpreter (or not installed on your computer) - doesn't look like a copy issue.

**Comment by SBoudrias** [comment]
And about `bash mvnw`, I'm wondering if this forces to run this script as a `bash` script while it might not be bash compatible.

**Comment by daggerok** [comment]
but as far I'm regenerating same scripts with same /bin/sh interpreter it will works. Seems like this IS a copy problem, because when it copying it may change for example end of line, so interpreter line could be not for example `#!/bin/sh\n` but something like `#/bin/sh\r\n` or vise versa...

**Comment by SBoudrias** [comment]
Any chance different line ending would be caused by a `.gitattribute` file?

**Comment by daggerok** [comment]
Maybe, but I have added that .gitattributes few days ago trying to fix that problem. I can remove it

**Comment by daggerok** [comment]
Hello

Issue was solved after removing and re-installing from scratch `yo` and `generator-jvm` packages. For some reasons, after just package `npm i -g generator-jvm` npm showing me that version was updated, but yo itself used old version.

**Comment by SBoudrias** [comment]
Oh, great to hear! Let me know if any further issue come up!
