### ISSUE TITLE
copyTpl()’s globOptions changed from node-glob to fast-glob

### ISSUE THREAD

**Issue by sonicdoe** [yeoman/generator#1076]
[globby v8](https://github.com/sindresorhus/globby/releases/tag/v8.0.0) switched from [node-glob](https://github.com/isaacs/node-glob) to [fast-glob](https://github.com/mrmlnc/fast-glob). [mem-fs-editor](https://github.com/SBoudrias/mem-fs-editor), a dependency of yeoman-generator, updated to globby v8 in a minor version bump which caused some generators to break, see https://github.com/SBoudrias/mem-fs-editor/issues/111.

I’m mostly opening this issue for discoverability (in case other users are running into a similar issue). Since `copyTpl()` is not really part of yeoman-generator (although, it is exposed through `this.fs.copyTpl()`), it would probably be best to fix this issue in mem-fs-editor itself.

**Comment by SBoudrias** [comment]
Fixed on `mem-fs-editor` side. Latest patch reverts to the backward compatible API.
