### ISSUE TITLE
BOM created in invalid position by copyTpl

### ISSUE THREAD

**Issue by duncdrum** [yeoman/generator#1079]
Hi all, 
the original file `repo.xml` does not contain a BOM.  
```xml
<?xml version="1.0" encoding="UTF-8"?>
<meta xmlns="http://exist-db.org/xquery/repo">
  <description><%- desc %></description>
</meta>
```

Yet after processing it like this:
```js
this.fs.copyTpl(
  this.templatePath('repo.xml')
  this.destinationPath('repo.xml') {
    desc: this.props.desc
})
```

A BOM is inserted at the beginning of the ouput file when writing to disk. This is invalid (!) since no data can precede the `<?` part. 

So my question is this a bug in mem-fs, if WAI, how can I strip the BOM when the generator is writing to disk?  I've tried with:
```js
const stripBom = require('gulp-stripbom')
…
this.registerTransformStream(
      stripBom({ ext: ['xml', 'odd', 'xconf'], showLog: false })
    )
```

but to no avail, the file on disk again has the BOM, would it be possible to determine mime-types for xml and skip BOM insertion entirely by default?

The chai test that showed me the problem, (switch to `fs.readFileSync ` to make it pass, as that by default removes the DOM)
```js
var chai = require('chai')
var expect = require('chai').expect
var chaiXml = require('chai-xml')
var xmldoc = require('xmldoc')
…
chai.use(chaiXml)
    it('should be well formed xml', function () {
      var XML = fs.readFile('repo.xml', 'utf8')
      var doc = new xmldoc.XmlDocument(XML).toString()
      expect(doc).xml.to.be.valid()
    })
```

result
```bash
Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: [
      at error (node_modules/sax/lib/sax.js:651:10)
      at strictFail (node_modules/sax/lib/sax.js:677:7)
      at beginWhiteSpace (node_modules/sax/lib/sax.js:951:7)
      at SAXParser.write (node_modules/sax/lib/sax.js:1006:11)
      at new XmlDocument (node_modules/xmldoc/lib/xmldoc.js:258:15)
      at Context.<anonymous> (test/app-eXide-default.js:37:17)
```

**Comment by SBoudrias** [comment]
Well, I can tell you mem-fs-editor does not include BOM randomly in files. Could it be inserted by a git config or any other program you're running locally? (like visual studio)

**Comment by duncdrum** [comment]
@SBoudrias frankly i don't know yet what is including it (not git not visual studio). While i have managed to workaround the immediate issues, I m still trying to track the actual source. 

Knowing that you think it isn't mem-fs helps, I ll close once i tracked down the source, or have given up :)

**Comment by eddiemonge** [comment]
@duncdrum Have you figured it out yet? I am going to close this and if it is still happening or you can reproduce it in a different, clean environment I'll reopen it.
