### ISSUE TITLE
sourceRoot method joins the path given with destinationRoot instead of sourceRoot

### ISSUE THREAD

**Issue by ozeno** [yeoman/generator#1085]

**Comment by SBoudrias** [comment]
Actually `sourceRoot` isn't a join method. It's replacing the folder used as the source. In 99% of the cases, you don't want/need to use this method at all. Use `destinationPath()` and `templatePath()` if you want to generate paths.

**Comment by ozeno** [comment]
As far as I understand sourceRoot('src') should set the source_root path to 'old_source_root/src' but it sets the source_root to 'destination_root/src' instead.

**Comment by dt-rush** [comment]
This is also tracked by #1070

**Comment by g1eny0ung** [comment]
Same problem for me. I have to change the `_sourceRoot` to make it work as expected.

`this._sourceRoot = path.resolve(__dirname, '../templates')`
