### ISSUE TITLE
passing an object to the `prompt` method

### ISSUE THREAD

**Issue by aleclarson** [yeoman/generator#1087]
When an object is passed to `prompt`, why doesn't the returned promise resolve with the value, instead of wrapping it in an object? If the value was **not** wrapped, the `name` field wouldn't be necessary.

**Comment by SBoudrias** [comment]
This would've made sense - but now it's a little too late to make the change on Yeoman side as a lot of generators have been created already.

FWIW, I'm working on a refactor of Inquirer which is actually gonna do this properly. https://github.com/SBoudrias/Inquirer.js/issues/692 - Help is welcomed by the way!

I'll close this ticket as we're not planning to change the prompt API.
