### ISSUE TITLE
Task queued in priority queues but it is not being executed

### ISSUE THREAD

**Issue by kianting** [yeoman/generator#1090]
Hello, I have segregated the task according to priority queues, when I run yeoman under debug mode I can see that the task is being queued but it is not being but only the task that falls in initialising and prompting queues are being executed. How do I trouble shoot the priority queues and make the task run? Is it something that I am doing that is wrong?

`yo test-proxy
  yeoman:generator Queueing initializing in initializing +0ms
  yeoman:generator Queueing prompting in prompting +1ms
  yeoman:generator Queueing configuring in configuring +0ms
  yeoman:generator Queueing apiProxy in writing +0ms
  yeoman:generator Queueing grunt in writing +1ms
  yeoman:generator Queueing node in writing +0ms
  yeoman:generator Queueing tests in writing +0ms
  yeoman:generator Queueing config in writing +0ms
  yeoman:generator Queueing git in writing +0ms
  yeoman:generator Queueing others in writing +0ms
  yeoman:generator Queueing copyApigeeConfigTemplate in writing +0ms
  yeoman:generator Queueing copyDefault in writing +0ms
  yeoman:generator Queueing copyPackage in writing +0ms
  yeoman:generator Queueing copyReadme in writing +0ms
  yeoman:generator Queueing conflicts in conflicts +0ms
  yeoman:generator Queueing install in install +0ms
  yeoman:generator Queueing swaggerImport in end +0ms
  yeoman:generator Running initializing +1ms
Inializing yo ...
  yeoman:generator Running prompting +2ms
launching prompt ...

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │    Welcome to Yeoman,    │
   `---------´   │   ladies and gentlemen!  │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Out of the box I include scaffolding apiproxy, Node.js, and Gruntfile to build your app.
? Your api name test-mahesh-api
? API Description test mahesh test
? Basepath /mahesh
? Organization Name test-public
? Swagger Specification 
`

**Comment by SBoudrias** [comment]
My guess is that this is caused by an asynchronous task who never resolves (stay pending forever, and Node.js stop the process as nothing happens)

**Comment by kianting** [comment]
hello @SBoudrias thank you for your reply, how do I trouble shoot or debug this asynchronous task or rather how to I enable it so that it docent stay pending forever. How to I make nodes execute the task ?

**Comment by SBoudrias** [comment]
It's somewhere in your code. You must be either returning a Promise that's never resolved or calling `this.async()` without using the callback.

I'd say to look at the debug trace like you did, and seeing where the process stop. From what you posted here, I'd say `prompting()` might never resolves.

**Comment by SBoudrias** [comment]
Perfect! Happy you've been able to figure it out :)
