### ISSUE TITLE
Unable to inherit on multiple levels

### ISSUE THREAD

**Issue by garyvh2** [yeoman/generator#1093]
When extending a generator there might be cases where you have the same logic for certain functions, I.E: `end`, `constructor`, `rootGeneratorName`, `initializing` and so.

```
class GeneratorBase extends Generator {
  ...

  initializing() {
    this.appname = this.appname.replace(/\s+/g, '-');
  }

  end() {
    this.log(chalk.bold('\nSetup Complete!'));
  }

  ...
}
class ElementGenerator extends GeneratorBase {
  ...

  writing() {
    // Some specific writting logic
  }

  ...
}
```

When you extend a class that already extends Generator, the implementation of the `run` for `yeoman-generator` breaks as the methods reading works only on 1 level, as you can see here https://github.com/yeoman/generator/blob/1cd1031eb1cc2ed0288265dd15ddc6cfbcffabb7/lib/index.js#L398 so in this case the `methods` const will only contain the method `writting`

Please tell me if you require further info, or I'm doing something wrong.

**Comment by SBoudrias** [comment]
That's the behavior of Yeoman per design. http://yeoman.io/authoring/running-context.html

If you wish to run another generator, then you should use `composeWith`.

If you wish to run some method, then you could manually reassign them to the prototype.

```js
Generator.prototype.exec = Parent.prototype.exec;
```

or call them explicitly from within your class:

```js
class ElementGenerator extends GeneratorBase {
  initializing() {
  	super.initializing();
  }
}
```

**Comment by garyvh2** [comment]
```
Generator.prototype.exec = Parent.prototype.exec;
```
```
class ElementGenerator extends GeneratorBase {
  initializing() {
  	super.initializing();
  }
}
```

I actually considered both options before creating the issue, but it breaks the intention of having classes on first place, having this boilerplate would make it work, but what sense does it make having to re implement the methods if they are not changing anything on them.

The idea of having `super.initializing()` would be to have some extra steps done over the parent method implementation after its common execution flow. Using it to expose the methods on a 1 level inheritance looks like an anti pattern.

**Comment by SBoudrias** [comment]
Well, this design decision was actually made a very long time ago (before I even got involved with Yeoman). We cannot really change it now because this would break a huge part of the public generators.

The problem has always been methods defined on a yeoman generator are run as "tasks". So there was no easy way to create shareable helpers methods. Only running the tasks on the top level prototype was a way to enable the creation of reusable helpers.
