### ISSUE TITLE
When validating prompt input, invalid text disappears and user must re-type

### ISSUE THREAD

**Issue by bfitzpat** [yeoman/generator#1095]
Currently with the generator, we are validating user input with this prompt:
`            type: 'input',
            name: 'package',
            message: 'Package name: ',
            default: defaultPackage,
validate : utils.validatePackage`

Essentially the user is providing a Java-style package name and we validate to make sure there are no Java keywords or wacky characters. Nothing too earth shattering. Our validator either sends back "true" or a message formatted with Chalk. 
 
When the user types a package name, if the package name is not valid, the full package name that i typed is completely erased and I would need to type it again.

![47090043-56b19600-d222-11e8-841a-e35e03d6074b](https://user-images.githubusercontent.com/530878/47091037-5513ae00-d1e1-11e8-95fd-d1fec4441db7.png)

Then I hit enter.

![47090128-895b8e80-d222-11e8-94c4-a9b9bec1e62b](https://user-images.githubusercontent.com/530878/47091067-60ff7000-d1e1-11e8-848a-58e74396948c.png)

The full package name that the user has typed vanishes. It would be convenient to keep it so they just have to change few characters.

Is this behavior possible using the default Yeoman generator code? Or where would we start looking to try and modify that behavior? 

Thanks in advance.

**Comment by SBoudrias** [comment]
This is related to https://github.com/SBoudrias/Inquirer.js/issues/711

I'll close this ticket as not something we can fix directly in Yeoman. You can follow up on the other ticket.
