### ISSUE TITLE
Provide utility method to return version of generator

### ISSUE THREAD

**Issue by bfitzpat** [yeoman/generator#1096]
When I prompt users for inputs for my camel generator, I would like to display the version of the generator. There doesn't seem to be any kind of a method on the generator itself to get the version for display purposes. Is there a workaround for this kind of behavior or is it something that could be added?

**Comment by SBoudrias** [comment]
You can get your generator version using `require('package.json').version` (might need the right path) in your own code.

Would this be enough for your use case?

**Comment by bfitzpat** [comment]
I'll try that and let you know. Thanks for the suggestion!

**Comment by bfitzpat** [comment]
This worked great. Thanks for the obvious suggestion I completely missed! :)
```
var pjson = require('../package.json');
console.log('Version: ' + pjson.version);
```
