### ISSUE TITLE
Yo composability and run loop priority

### ISSUE THREAD

**Issue by cakriwut** [yeoman/generator#1100]
#Backgound
1. Yeoman composeWith has option to pass options object from main generator to sub generator. *The options must be provided as parameter in composeWith call*
2. Yeoman has run loop priority where *Initializing* comes before *Prompting*

#Problem
1. If we want to provide options for sub-generator, then composeWith must be called after main-generator completes prompting.
2. If we composeWith, after main-generator prompting, (let say writing() of the main-generator) - then the run loop will put sub-generator prompting() , in higher priority - causing user needs to press Enter twice on the second question during sub-generator prompting.

#Question
1. Is there any strategy, that we can define composeWith during Initializating() and provide reference to the future options after main-generator prompting() ?

**Comment by SBoudrias** [comment]
> Is there any strategy, that we can define composeWith during Initializating() and provide reference to the future options after main-generator prompting() ?

That's not possible, but also you shouldn't need to do this.

I don't understand what's the problem with calling `composeWith` after the main generator prompting phase. If you want to skip the second generator prompts when options are provided, you need to implement this yourself (for example by using the prompt `when` option.)

All phases of every generator will always run. There's no way to skip phases.

**Comment by cakriwut** [comment]
Thanks, I use mem-fs-editor as the tunnel between generators.

I close this issue. For other folks who has same challenges, please check generator-office-x npm. 🙏🙏
