### ISSUE TITLE
TypeError: Cannot read property 'Base' of undefined

### ISSUE THREAD

**Issue by mcorning** [yeoman/generator#1104]
this is my first attempt to use yeoman. yeoman doctor gave me clean bill of health at install, so I was surprised to see the undefined error above the first time I ran 
yo mongoose

I was following instructions on https://scalegrid.io/blog/yeoman-mongoose-and-mongodb/

**Comment by SBoudrias** [comment]
Looks like a code bug inside the generator you're using. You should report the issue on their own repository. The Yeoman core team cannot maintain all the generators available out there.

**Comment by mcorning** [comment]
Roger. thanks for the quick reply. 
I'm a rank amateur at this new stuff (for me), so please forgive my randomizing you here.
