### ISSUE TITLE
Do we want to remove Bower?

### ISSUE THREAD

**Issue by UlisesGascon** [yeoman/generator#1106]
Hi team!

As we know Bower has been deprecated. We still have `bowerInstall()` to manage Bower dependency, as well in the [official Doc](https://yeoman.io/authoring/dependencies.html). If you agree I can prepare a PR to remove it and update the docs in the website and update `generator-generator` too.

What do you think? 😄

**Comment by SBoudrias** [comment]
I think we should focus on removing from `generator-generator`.

We could remove it from the core doesn't really bring much value; and having this doesn't add any extra dependencies. So personally I'd keep until there's a reason to get rid of it.

**Comment by mischah** [comment]
I personally think it’s about time to get rid of it.

>  So personally I'd keep until there's a reason to get rid of it.

What do you think about deprecating it?

**Comment by SBoudrias** [comment]
I don't care too much about bower, I'm on board to fully remove if you think it's creating unnecessary noise / give wrong impressions to the Yeoman users.

**Comment by UlisesGascon** [comment]
mmm.. maybe I can start with `generator-generator` and then evaluate how complex is to remove Bower from `generator` 😉

**Comment by mischah** [comment]
Sounds like a plan 👍
