### ISSUE TITLE
Generator-generator doesn't take any input

### ISSUE THREAD

**Issue by Noeky** [yeoman/generator#1114]
When using @microsoft/sharepoint generator it's not taking any user input, and we are not able to create a new spfx project. 

I already tried to reinstall all the components needed to use the generator. 
I also tried to us yo @microsoft/sharepoint --solutionName "hello-world" --framework "react" --componentType "webpart" --componentName "HelloWorld" --componentDescription "HelloWorld web part" --environment "spo" skipFeatureDeployment false

But this also get stuck. 

The versiosn I'm running are
npm ls -g --depth=0
+-- @microsoft/generator-sharepoint@1.8.2
+-- create-react-app@2.1.8
+-- gulp@4.0.2
+-- gulp-cli@2.2.0
+-- npm-install-all@1.1.21
+-- serve@11.0.0
`-- yo@2.0.6

**Comment by r33beers** [comment]
Related to https://github.com/SBoudrias/Inquirer.js/issues/811 ?

**Comment by Noeky** [comment]
> Related to [SBoudrias/Inquirer.js#811](https://github.com/SBoudrias/Inquirer.js/issues/811) ?

No it's not releated

**Comment by SBoudrias** [comment]
Could you try uninstalling/reinstalling now?

Also make sure you're using a standard TTY terminal (cmd.exe/powershell, or any mac terminals)
