### ISSUE TITLE
How to loop inside a prompt

### ISSUE THREAD

**Issue by mohitsaini2114** [yeoman/generator#1115]
prompting() {
     const columnPrompts = [{
      type: 'input',
      name: 'title',
      message: 'Your project title?',
      default: 'ID'
    }, {
      type: 'input',
      name: 'port',
      message: 'port number?',
      default: 'S'
    }, {
      type: 'confirm',
      name: 'repeat',
      message: 'Do you want to add one more port?'  
    }

Above code is just an example. If I get yes to add one more port then I want to call  below code again - 
    {
      type: 'input',
      name: 'port',
      message: 'port number?',
      default: 'S'
    }

**Comment by SBoudrias** [comment]
You can use recursion to do this:

```js
function a() {
	if (condition) {
		a();
	}
}
```
