### ISSUE TITLE
Usage guidelines in README

### ISSUE THREAD

**Issue by arvindpdmn** [yeoman/generator#1116]
Might be a good idea to know how to use this. The README is sparse.

Also confused about where this repo fits when there's [https://github.com/yeoman/yo](https://github.com/yeoman/yo), which is the repo referenced in the main site at [https://yeoman.io](https://yeoman.io)

**Comment by SBoudrias** [comment]
`yeoman-generator` is the framework allowing you to write your own generators; like `generator-node`, etc.

`yo` is command line interface running the generators released by the community.

**Comment by arvindpdmn** [comment]
Thank you. How is `yeoman-generator` related to `generator-generator` if I wish to write my own generator? Do I need to install both?

**Comment by SBoudrias** [comment]
`generator-generator` will generate a package who'll be using `yeoman-generator` (it'll be added to the generated folder `package.json` file)

**Comment by arvindpdmn** [comment]
Thanks. It's clear. Last question:
- Current NPM version is 4.0.1: https://www.npmjs.com/package/yeoman-generator
- API documentation version is 3.2.0: https://yeoman.github.io/generator/

Why is there a mismatch of versions?

**Comment by SBoudrias** [comment]
Ah, the updates aren't automatic on every release yet. And we didn't make any major API changes - we had a major bump because of dropping supports for Node 6.
