### ISSUE TITLE
Optionally generate newline at end of .yo-rc.json

### ISSUE THREAD

**Issue by jimmywan** [yeoman/generator#1117]
My .yo-rc.json files never seem to get generated with a newline at the end.

I can understand why you might not want to change the default behavior if it's been that way for a while, but it's fairly standard to have a newline at the end of a file.

**Comment by SBoudrias** [comment]
Yeoman only copy the templates files; if they have newlines at end of files, it'll be there.

I'm not sure I understand where the issue is coming from? From other generators?

**Comment by jimmywan** [comment]
Sorry, should have paid a bit more attention to what I was looking at before posting. It's the `.yo-rc.json` file that is missing the trailing newline.
