### ISSUE TITLE
Is it possible to display a loader during another task execution?

### ISSUE THREAD

**Issue by eestein** [yeoman/generator#1124]
I have created a generator that runs some long lasting commands, like `ng new` and `npm install`. While those commands are running, I think it’d be nice to display a loader to the user, but I couldn’t find such information in the docs. Is this possible?

**Comment by SBoudrias** [comment]
There's no built-in for this. That being said, you can reuse any open source library that'll run on Node.

For example https://github.com/sindresorhus/ora

**Comment by eestein** [comment]
Ok, thanks
