### ISSUE TITLE
Test generators private methods

### ISSUE THREAD

**Issue by makbol** [yeoman/generator#1134]
Say I wrote my custom generator like this

```js
class extends Generator {
  writing() {
    this._private_method();
  }

  _private_method() {
    console.log('private hey');
  }
}
```
with use of _private_ methods according to [doc recommendation](https://yeoman.io/authoring/running-context.html#helper-and-private-methods)

I'd like to unit test **only** `_private_method()`

I tried to setup test like:

```js
const Generator = require('../generators/app');
const generator = new Generator();

describe('generator:_private_method', () => {
  it('returns correct output', () => {
    assert(generator._private_method());
  });
});
```

but I get error `TypeError: Cannot use 'in' operator to search for 'help' in undefined`

**Comment by SBoudrias** [comment]
The Generator class expect arguments to be passed in. It requires an instance of `yeoman-environment` to work properly.

Something like `const generator = environment.createEnv().instantiate(Generator)`.

This isn't really a public interface, so you might need to dig through the [environment code](https://github.com/yeoman/environment/blob/master/lib/environment.js) to get it to work properly.

**Comment by makbol** [comment]
Thank you @SBoudrias :pray:
