### ISSUE TITLE
Using yo to upgrade projects.

### ISSUE THREAD

**Issue by ChuckJonas** [yeoman/generator#1140]
I apologize if this isn't the correct place for this but I couldn't find the answer anywhere else.

I have a yo-generator that I'm using to scaffold out a react app with a domain specific configuration/build setup.

The generated scaffolding currently comes with a hello world application (`src/app.ts`).

Obviously, the first thing the user will do is replace this app.  

However, as new changes are added to the yo-generator, I would like users to be able to incorporate those back into the application but running the generator again.

Right now when you do this it asks if you want to overwrite each file.  Is there a way detect subsequent runs and just not attempt to copy certain files (EG `src/app.ts`)?

**Comment by ChuckJonas** [comment]
The other challenge I'm facing is how to deal with files where they have modified but still might want to incorporate new changes from the generator (EG package.json)...

**Comment by SBoudrias** [comment]
Hi! This needs to be implemented within your own generator, through usually some custom code.

Here's a few solutions and helpers:

1. You use the [storage](https://yeoman.io/authoring/storage.html) functionality to remember anything between runs.
2. You can always read files from the destination directory to determine if a given file was already created and if you want to recreate it or not.
3. The best is to not update files with templates. This cannot be merged together as Yeoman has no idea how we'd want to merge it in the end. So the solutions is to parse files in data format. For JSON files that's easy with read + `JSON.parse`. For JS you could modify the file AST - that's what babel is doing for example.

You can checkout generator-node as en example. This generator is designed to be highly usable to update projects to match the latest changes within it. Check this sub-generator for example and how it updates the `package.json` file without overwriting the unrelated configurations: https://github.com/yeoman/generator-node/blob/master/generators/eslint/index.js

I hope this helps! Simply put, Yeoman is pretty much only a standardized runner of generators and a few utilities. For the rest it is purely Node.js and can do anything you decide to code.

**Comment by ChuckJonas** [comment]
thanks, this gives me some direction to move towards
