### ISSUE TITLE
Create automated issue workflow.

### ISSUE THREAD

**Issue by mshima** [yeoman/generator#1143]
- Add label at issue creation.
- Close untouched bugs with https://github.com/marketplace/stale

**Comment by mshima** [comment]
@SBoudrias what do you think?

**Comment by SBoudrias** [comment]
I'm open to it; there's a lot of low quality issue that have been opened forever without a way forward

**Comment by mshima** [comment]
Waiting for multiples labels support to close this issue.
https://github.com/actions/stale/issues/17

**Comment by mshima** [comment]
Closing this.
It’s not perfect but it’s fine.
