### ISSUE TITLE
Generator 4.5.0 release

### ISSUE THREAD

**Issue by mshima** [yeoman/generator#1152]
@SBoudrias can you review https://github.com/yeoman/generator/pull/1150, https://github.com/yeoman/generator/pull/1151 and https://github.com/yeoman/generator/pull/1155.
If they are ok, please release 5.5.0.
Thanks

**Comment by SBoudrias** [comment]
Hey @mshima, I've just published 4.5.0 to npm.

I'll let you edit the release notes https://github.com/yeoman/generator/releases/tag/v4.5.0

It's awesome to see someone taking care of adding new features! Thanks for your hard work!

**Comment by mshima** [comment]
> Hey @mshima, I've just published 4.5.0 to npm.

Thank you, @SBoudrias 

> I'll let you edit the release notes https://github.com/yeoman/generator/releases/tag/v4.5.0

Done.

> It's awesome to see someone taking care of adding new features! Thanks for your hard work

 :thumbsup:

Now I need a environment release as soon you have time :joy:. Thanks
