### ISSUE TITLE
Generator uses grouped-queue but does not depend on it

### ISSUE THREAD

**Issue by flatiron32** [yeoman/generator#1189]
This change broke my generator https://github.com/yeoman/generator/pull/1150
``` FAIL  __tests__/app.js
  ● Test suite failed to run

    Cannot find module 'grouped-queue/lib/subqueue' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:276:11)
      at Object.<anonymous> (node_modules/yeoman-generator/lib/index.js:17:18)

```
My fix is to directly depend on grouped-queue directly.

**Comment by mshima** [comment]
@flatiron32 can you confirm https://github.com/yeoman/generator/pull/1190 fixes this problem?

**Comment by flatiron32** [comment]
I am not sure I know how to test correctly because. When I checkout branch `v4.6.0` (the version I first experience a problem with), run `npm link`, and in my project run `npm link yeoman-generator` I don't have the failing tests any more. AFAIKT from diffing the package there is no change.
I think I need advice on how to test a local branch of yeoman-generator in my generator.

**Comment by mshima** [comment]
I normally test with `npm install mshima/generator#master`

**Comment by mshima** [comment]
Eslint was supposed to error with this missing dependency.

This patch will fail if you use custom priorities.
I will not add grouped-queue dependency here, because I will add min environment required for some features.
So I have plans to remove addSubQueue workaround.

**Comment by flatiron32** [comment]
I confirm that #1190 will make my generator's tests pass. 
v4.5.0 --> Pass
v4.6.0 --> Fail
V4.7.0 --> Fail
#1190 --> Pass
All with no changes to my generator.
