### ISSUE TITLE
Jest throws syntax error at L285 in index.js.

### ISSUE THREAD

**Issue by ayesham** [yeoman/generator#1192]
Jest throws syntax error on L285 index.js at the following code:

```js
try {
            SubQueue = require('grouped-queue/lib/subqueue');
          } catch {
            throw new Error(
              "The running environment doesn't have the necessary features to run this generator. Update it and run again."
            );
          }
```

Looks like it was recently added via:

https://github.com/yeoman/generator/pull/1190/commits/b5e5c7543f93c52d904d530667791286f7b6f146#diff-6d186b954a58d5bb740f73d84fe39073R285

**Comment by ayesham** [comment]
Should this be:

```js
         try {
            SubQueue = require('grouped-queue/lib/subqueue');
          } catch (error) {
            throw new Error(
              "The running environment doesn't have the necessary features to run this generator. Update it and run again."
            );
          }
```

**Comment by ayesham** [comment]
Thanks so much for your quick response to this issue. Is it possible to publish a patch for this one?

**Comment by mshima** [comment]
Published.
Eslint was supposed to `catch` this error. :P

**Comment by ayesham** [comment]
Hahahaha! Thanks! On the brighter side, robots can’t take our jobs ;)
