### ISSUE TITLE
Deleting large non-binary file takes extremely long time

### ISSUE THREAD

**Issue by bdukes** [yeoman/generator#1202]
We have a generator which includes a local copy of Yarn (the result of `yarn set version ^1`), which is a 5MB JavaScript file.  After updating this file to the latest version, the delete of the file is taking a very long time (close to an hour).  After debugging the process, it looks like the conflict detection is looping through the file to calculate a diff.  

Is it possible to short-circuit that conflict check for deletions, or configuration I could do to skip it for specific files?

**Comment by mshima** [comment]
Can't you directly copy to the real path at end step?

**Comment by bdukes** [comment]
So instead of using `this.fs.delete` in `writing()`, just use [`fs.unlink`](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_fs_unlink_path_callback) directly in `end()`?  That does seem like it would be a workable workaround.

**Comment by mshima** [comment]
Exactly.
The api to ignore conflicts can be done, and should be kind of easy, it would use transformStream.
