### ISSUE TITLE
Helping users stay up to date

### ISSUE THREAD

**Issue by flatiron32** [yeoman/generator#1231]
I want to help the users of my generator know if it is out of date or not. I would like to detect the version of the generator in use and then compare that to the latest version in the artifact repo. Before I start designing and implementing how to do this, I wanted  to see if this is a challenge that had already been tackled by anyone in the Yeoman community.

**Comment by mshima** [comment]
@flatiron32 I am implementing the path that the generators are auto installed, so it should install the last version, and update if needed.

**Comment by mischah** [comment]
Hej @flatiron32,

this is what you want to use: https://github.com/yeoman/update-notifier

It compares the installed version against possible updates in the npm registry.

Cheers, Michael
