### ISSUE TITLE
this.fs.append triggers a conflict resolution

### ISSUE THREAD

**Issue by drewctate** [yeoman/generator#1239]
When my generator uses mem-fs-editor's `append` function, it triggers a conflict with the existing file that is to be appended to. It would be nice if that didn't happen as it's simply appending. Either the conflicter could be smarter, or there could be a way to flag a particular file as a force target without turning on force for everything.

**Comment by mshima** [comment]
This is the expected behaviour.

To force override this should work: 
`this.env.sharedFs.get(this.destinationPath('foo.bar')).conflicter = 'force';`

**Comment by mshima** [comment]
I think the api doesn't guarantee the instance returned is the same, so better do:
```
const file = this.env.sharedFs.get(this.destinationPath('foo.bar'));
file.conflicter = 'force';
this.env.sharedFs.add(file);
```
And better replay every time the file is written.

**Comment by drewctate** [comment]
That seems a little esoteric, but it did solve my problem. Thanks for the quick response @mshima.

**Comment by mshima** [comment]
This is not a common feature.
Otherwise we could add a shortcut.
