### ISSUE TITLE
npm ERR! missing: yeoman-generator@^4.10.1, required by yeoman-environment@2.10.1

### ISSUE THREAD

**Issue by avizov** [yeoman/generator#1240]
I have a node package that requires "yeoman-generator" version "4.10.0" and "yeoman-environment" version "2.8.1".
The "yeoman-generator"@4.10.0 requires "yeoman-environment" version "^2.9.5" (actually install "_id": "yeoman-environment@2.10.1") which requires "yeoman-generator": "^4.10.1" and this cycling bring us for following errors in our WhiteSource scan:

whitesource run -c whitesource.config.json.fb7464e48e13d0239b7b3a436b2a367b
20:47:24 OK: Config file is located in: whitesource.config.json.fb7464e48e13d0239b7b3a436b2a367b
20:47:24 OK: Running whitesource V20.3.2...
20:47:27 npm ERR! extraneous: yeoman-generator@4.10.1 /home/jenkins/agent/workspace/erator_s4_ext_voter_upd-ui5-base/node_modules/yeoman-generator/node_modules/yeoman-generator
20:47:27 npm ERR! missing: yeoman-generator@^4.10.1, required by yeoman-environment@2.10.1
20:47:27 ERROR: 'npm ls' command failed Make sure to run 'npm install' prior to running the plugin. Please resolve the issue and rerun the scan operation.
Please explain how to resolve this cycling dependency...

**Comment by mshima** [comment]
yeoman-generator dependency on yeoman-environment is optional due to backward compatibility for standalone generators.
Should be removed for 5.x.
`npm install --no-optional`

**Comment by mshima** [comment]
Closing, reverted the version bump

**Comment by avizov** [comment]
with the revert, the issue was resolved
