### ISSUE TITLE
how to pass a array of values to the template in the yeoman generator

### ISSUE THREAD

**Issue by helxsz** [yeoman/generator#1245]
I am using yeoman-generator, which I need to pass a array of value to the template file. for example I want to pass a array of text values to the template.

```
  install() {
      async app() {
         let array = ['abc','cde','efg'];
           this.fs.copyTpl(
            this.templatePath('base','/abc.ts'),
            this.destinationPath('example/abc.ts'),
            {'array':array}
          );         
      } // app 
  }// install 
```
in the .ts file, i define a variable which received the passed array.

`public options =  <%= array %> ;
`My expected result is

`public options =  ['abc','cde','efg'] ;
`however the resulted output is

` public options =  abc,cde,efg ;
`how would I resolve this problem ?

**Comment by mshima** [comment]
```public options = [<%= array.map(value => `'${value}'`).join(',') %>] ;```
Please keep this repository for generator related issues only.
Post others questions to stackoverflow or the related project, in this case ejs.

**Comment by helxsz** [comment]
thanks @mshima
