### ISSUE TITLE
task freezed on win10

### ISSUE THREAD

**Issue by g8up** [yeoman/generator#1249]
I'm a newer to yeoman-generator.
I follow the document here: https://yeoman.io/authoring/user-interactions.html#using-user-answers-at-a-later-stage
```js
module.exports = class extends Generator {
  async prompting() {
    this.answers = await this.prompt([
      {
        type: "confirm",
        name: "cool",
        message: "Would you like to enable the Cool feature?"
      }
    ]);
  }

  writing() {
    this.log("cool feature", this.answers.cool); // user answer `cool` used
  }
};
```
and run on Windows 10:
![image](https://user-images.githubusercontent.com/8005686/83944896-84a17f00-a839-11ea-8d7f-d38a3b4b253d.png)

It stucked.
I'm using `yeoman-generator@4.10.0`.
yo: v2.0.0
Node.js: v12.13.0

**Comment by mshima** [comment]
Looks related with inquirer and https://github.com/SBoudrias/Inquirer.js/#know-issues

**Comment by mshima** [comment]
There is nothing we can do if it’s related with inquirer. So I’m closing this.
If you manage to reproduce with windows + bash, feel free to reopen it.

**Comment by mshima** [comment]
You can try to use yo@3.1.1 instead of 2.0.0 too
