### ISSUE TITLE
`Generator#composeWith` should support returning all composed generators when `returnNewGenerator` were `true`

### ISSUE THREAD

**Issue by JasonHK** [yeoman/generator#1251]
https://github.com/yeoman/generator/blob/5cf1a182ab7208c9b7fb491a5139f8b75b6b0fdc/lib/index.js#L1102-L1105

Shouldn't line 1103 be written like this?

```javascript
-   const generators = generator.map(gen => this.composeWith(gen, options));
+   const generators = generator.map(gen => this.composeWith(gen, options, returnNewGenerator));
```

Currently, when `generator` was an array and `returnNewGenerator` was `true`, `Generator#composeWith` only returns an array of `this` (i.e. the current generator).

I think this is a mistake, although this should be easy to fix.

**Comment by mshima** [comment]
Fixed in #1252 thanks for reporting.
