### ISSUE TITLE
Yeoman fails if the generator uses user.github.username mixin

### ISSUE THREAD

**Issue by kyoh86** [yeoman/generator#1255]
- I have an account with public email address which ends with *.dev TLD.
- GitHub may have a bug so I cannot find my account with my public email address.
- Yeoman uses github-username package and it calls GitHub API.
  - [source](https://github.com/yeoman/generator/blob/master/lib/actions/user.js#L57-L62)

So now, I cannot use yeoman generators using `user.github.username` mixin.
I know that it is not issue of Yeoman, but I want Yeoman to be able to get GitHub Username without GitHub access.

Proposal: If an environment variable `YEOMAN_GITHUB_USERNAME` is set, Yeoman uses it.

**Comment by mshima** [comment]
Have you tried to update github-username from 3.x to 5.x?
I can upgrade if it works.
A workaround like that should not be implemented at generator side.
You should do something like:
```
async task() {
  const username = await this.user.github.username().catch( ()=> fallback );
}
```

**Comment by kyoh86** [comment]
It's not problem of the github-username.
GitHub API does not return my account with my correct email.

... I'll try to negotiate with some generator authors...

**Comment by mshima** [comment]
Do you have this problem with multiples generators?
I fell a env var is not good but adding an option is possible.
```
yo foo --github-username username
```

**Comment by kyoh86** [comment]
ya, but I'll try. thanks.

**Comment by mshima** [comment]
If you are willing to provide a PR:
1) You should add an option like:
https://github.com/yeoman/generator/blob/ba43e2c541e3c7940ea1d567f3d034719f507833/lib/index.js#L182-L186

2) Change user mixing to be able to read the generator:
https://github.com/yeoman/generator/blob/ba43e2c541e3c7940ea1d567f3d034719f507833/lib/actions/user.js#L12
to:
```
const generator = module.exports;
const user = generator.user = {};
```

3) Update username function to read options:
https://github.com/yeoman/generator/blob/ba43e2c541e3c7940ea1d567f3d034719f507833/lib/actions/user.js#L62
To something like:
```
user.github.username = () => {
  if (generator.options && generator.options.githubUsername) {
    return Promise.resolve(generator.options.githubUsername);
  }
  return githubUsername(user.git.email());
}
```

4) Change user mixin load:
https://github.com/yeoman/generator/blob/ba43e2c541e3c7940ea1d567f3d034719f507833/lib/index.js#L1502
to
```
_.extend(Generator.prototype, require('./actions/user'));
```


5) The missing part: provide test case.
