### ISSUE TITLE
conflictor should respect env cwd

### ISSUE THREAD

**Issue by xyc** [yeoman/generator#1259]
`conflictor` logs a relative file path from `process.cwd()` to `file.path`. It doesn't respect the `cwd` path set in environment. This mainly affects logging.

https://github.com/yeoman/generator/blob/245fcf53c8ff0baa00dbc86fd5be3fb47995bce1/lib/util/conflicter.js#L285

**Comment by mshima** [comment]
I will take a look at next major version.
