### ISSUE TITLE
question storage does not work with generator property name

### ISSUE THREAD

**Issue by tonyhallett** [yeoman/generator#1266]
https://github.com/yeoman/generator/blob/bfd02b3d9d41820cd90a216c2b0ee64c2d4b04fb/lib/index.js#L531

#1265 fixes this but 

![image](https://user-images.githubusercontent.com/11292998/106330816-d04ae200-627b-11eb-9167-528b7b3dd0dd.png)

Please advise

**Comment by mshima** [comment]
Fix at https://github.com/yeoman/generator/commit/cd1b55713e55aa987622dbddd6f468e712e47818
