### ISSUE TITLE
Generator broken after updating to 5.0.0

### ISSUE THREAD

**Issue by fernandopasik** [yeoman/generator#1279]
I'm getting this error after upgrading to yeoman-generator 5.0.0

```
Error mygenerator 

This generator (mygenerator) requires yeoman-environment at least 3.0.0-beta.1, current version is 2.10.3
```

**Comment by fernandopasik** [comment]
@mshima I saw you upgraded a few libraries besides this one. Do you know what this could be related to?

**Comment by fernandopasik** [comment]
I tried forcing environment 3.0.0 on my dependencies, but still was pointing to 2.10.3.

After some more investigation I noticed that is actually the version that yo is using in my global packages.

Should we update https://github.com/yeoman/yo/blob/main/package.json#L74 ?

**Comment by mshima** [comment]
@fernandopasik yeoman-generator@5 requires a new version of `yo`. I will update it, but not sure the timeline. First time I've released a version that required a new yo release.
For now I recommend it for generators that includes it's own executable or you can test it using yeoman-environment own binary (new): `npm install -g yeoman-environment; yoe run a-generator`.

**Comment by fernandopasik** [comment]
Makes sense, thanks for clarifying and the help

**Comment by mshima** [comment]
Beta released `npm install yo@next-4`

**Comment by Haixiang6123** [comment]
Same problem here. +1. Updating to yo@next-4 solved my problem. 

Try so many times to reinstall the `yo`. God, I thought my nvm or npm was broken 🤣

**Comment by LandonSchropp** [comment]
I'm running into the same issue. I'm don't mean to sound ungrateful, because Yeoman is awesome, but I wish that these changes would have been released simultaneously. This issue wasn't easy to find on Google.

**Comment by mshima** [comment]
@LandonSchropp yeoman-generator/yeoman-environment/yo relationship is quite unique.
But yo keeps ancient backward compatibility.
Those new releases are quite stable for standalone generators, but there are a few details that may require changes for a better backward compatibility/interoperability.

**Comment by fernandopasik** [comment]
Any updates on when Yeoman v4.0.0 final will be released?
I know there's the v4.0.0-beta.0 which works good with this release

**Comment by mshima** [comment]
yo@4.0.0 is released, hopefully there won't be too many regressions.

**Comment by fdelbrayelle** [comment]
I still have the issue when working on Kafka module for JHipster : 

```
Uncaught Error: This generator (jhipster-kafka:app) requires yeoman-environment at least 3.0.0, current version is 2.10.3, try reinstalling latest version of 'yo' or use '--ignore-version-check' option
```

Even if installing `yo@latest`. Any idea @mshima please?

**Comment by mshima** [comment]
@fdelbrayelle what command are you executing?

**Comment by fdelbrayelle** [comment]
@mshima `npm install yo@latest` then `npm test` and I get this error.

**Comment by mshima** [comment]
Update yeoman-test and install yeoman-environment at devDependencies.

**Comment by fdelbrayelle** [comment]
Solved! Thank you :pray:

**Comment by mshima** [comment]
@fdelbrayelle https://github.com/yeoman/generator/issues/1283

**Comment by fdelbrayelle** [comment]
@mshima Thank you but I don't understand what am I suppose to modify here?

```
        const installConfig = {
            bower: false,
            npm: this.clientPackageManager !== 'yarn',
            yarn: this.clientPackageManager === 'yarn',
            callback: injectDependenciesAndConstants
        };
        if (this.options['skip-install']) {
            this.log(logMsg);
        } else {
            this.installDependencies(installConfig);
        }
```

Use `add*Dependency` instead?

**Comment by mshima** [comment]
@fdelbrayelle if there are dependencies to add, yes.
Otherwise just drop it.

**Comment by fdelbrayelle** [comment]
I don't understand because `this.installDependencies(installConfig)` (which comes from `generator-jhipster-module`) was launching a `npm install` here. As it was deleted from Yeoman Generator latest version, now I cannot use instead `this.addNpmDependency(...)` which doesn't seem to launch a `npm install`. What am I suppose to use instead to launch this one?

Thank you :pray:

**Comment by fdelbrayelle** [comment]
I've found another way :sweat_smile: https://github.com/fdelbrayelle/generator-jhipster-kafka/commit/eaea3e1bab93264dc6af7d5ed0d98109198c3b92
