### ISSUE TITLE
xo is in dependencies instead of devDependencies

### ISSUE THREAD

**Issue by manuth** [yeoman/generator#1282]
When having `yeoman-generator` as a dependency, it's impossible to use the `@typescript-eslint/eslint-plugin` in my project because `yeoman-generator` having `xo` as a normal dependency instead of a devDependency causes a conflict between `./node_modules/@typescript-eslint/eslint-plugin` and `./node_modules/yeoman-generator/node_modules/@typescript-eslint/eslint-plugin`.

The solution of this problem would be to remove `xo` from `dependencies` and add it to the `devDependencies`-list as recommended in the docs of `xo`:
https://github.com/xojs/xo#workflow

> **Before/after**
> ```diff
>  {
>  	"name": "awesome-package",
>  	"scripts": {
> -		"test": "ava",
> +		"test": "xo && ava"
>  	},
>  	"devDependencies": {
> -		"ava": "^2.0.0"
> +		"ava": "^2.0.0",
> +		"xo": "^0.25.0"
>  	}
>  }
> ```

**Comment by mshima** [comment]
Fixed in 5.0.1

**Comment by mshima** [comment]
Thanks @manuth

**Comment by manuth** [comment]
You're welcome - thank you for the rapid fix 😄
