### ISSUE TITLE
this.installDependencies is not a function

### ISSUE THREAD

**Issue by nazarhussain** [yeoman/generator#1293]
Installing dependencies is any generator is failing. 

```js
public install(): void {
    this.installDependencies({ npm: true, bower: false, yarn: false, skipMessage: false });
}
```

It throws the following error. 

```
(node:58529) UnhandledPromiseRejectionWarning: TypeError: this.installDependencies is not a function
   ......
    at Object.<anonymous> (node_modules/yeoman-generator/lib/index.js:1009:25
```

This probably caused because the `actions/install` is not registered to the `Generator` class. 

https://github.com/yeoman/generator/blob/d8dfd103b77b68eddf5f080712154c458ae5d02c/lib/index.js#L1408-L1413

This above code block is missing. 

```js
_.extend(Generator.prototype, require('./actions/install'));
```

**Comment by mshima** [comment]
It is not included by default anymore.
https://github.com/yeoman/generator/releases/tag/v5.0.0

**Comment by nazarhussain** [comment]
Thanks for the information @mshima

**Comment by schorfES** [comment]
The documentation is not up to date and quite misleading

* https://yeoman.github.io/generator/Generator.html#installDependencies
* https://yeoman.io/authoring/dependencies.html
