### ISSUE TITLE
this.addDevDependencies and this.addDependencies can improperly trigger conflict resolver

### ISSUE THREAD

**Issue by ntucker** [yeoman/generator#1299]
Just because a comma is added when addDependencies runs it creates a conflict and prompts the user in addition to breaking the install process

**Comment by terenceodonoghue** [comment]
Running into this with `yeoman-generator@^5.3.0`. Can confirm that the trailing comma seems to be triggering the conflict resolver.

![Screen Shot 2021-06-03 at 8 23 04 pm](https://user-images.githubusercontent.com/1697905/120629763-8122f100-c4a9-11eb-8a35-0c49c45aff63.png)

**Comment by ntucker** [comment]
@terenceodonoghue btw: one mistake I had was not awaiting these methods as they now return promises, which is why the conflict resolver was triggered.

This is still a problem for running yo on existing filesystems, but for completely new projects properly awaiting their return values should avoid this issue.

**Comment by terenceodonoghue** [comment]
@ntucker that did it, thanks! I replaced:

```
writing() {
  this.addDependencies([...])
}
```

with:

```
async writing() {
  await this.addDependencies([...])
}
```

**Comment by mshima** [comment]
Closing, since it's resolved. The addDependencies problem is unrelated and should be discussed in the other issue.

**Comment by ntucker** [comment]
@mshima "This is still a problem for running yo on existing filesystems, but for completely new projects properly awaiting their return values should avoid this issue."

This conflict issue will appear if you have an existing package.json - which is often the case when you're using yo to add pieces to an existing project instead of just create a new one. (I assume this is the point of making yorc files)

**Comment by mshima** [comment]
If you want to force package.json to be written, you can do something like https://github.com/yeoman/generator/issues/1239.
Or write a .yo-resolve file with 
```
package.json force
```

**Comment by ntucker** [comment]
Why is there a merging policy if the expectation is to only write to existing files if it's completely forced?

**Comment by mshima** [comment]
What are you spectating here?
To merge? To don’t generate at all? To use existing values?

The default is to merge, which is the better default for composing.
If you want to keep old values as default, you should load them.
```
this.addDependencies({
  …dependencies,
  …this.packageJson.getAll().dependencies
})
```
