### ISSUE TITLE
addDependencies and addDevDependencies attempt to resolve all packages against the public npm registry

### ISSUE THREAD

**Issue by baconandon** [yeoman/generator#1304]
Extracted from issue #1299 because I've just been bitten by this - feel free to mark as duplicate 🤷 

> addDependencies and addDevDependencies attempt to resolve all packages against the public npm registry and ignores those I've defined in my .npmrc, thus the generator fails with a 404 error.

**Comment by baconandon** [comment]
FWIW it looks like this is a shortcoming of `pacote` - see e.g. https://github.com/npm/pacote/issues/77

**Comment by baconandon** [comment]
To be more explicit the issue I'm having is very similar to the OP.
My generator is trying to add dependencies that are hosted in a private registry. 
My `.npmrc` file has a package-prefixed entry which "should" handle the resolution:

```
@foo:registry=http://npm.foo.example.com
```

**Comment by mshima** [comment]
I'm not sure what to do with this.

Parsing and passing .npmrc config pacote will complicate too much.
Version resolution is just a convenience for dependencies without a version.

If npm/yarn resolves dependencies with empty version, an option to skip version resolution can be added.
For now the only way is to manipulate package.json directly:
```
this.packageJson.merge({
  dependencies:{
    localDep: ''
  },
  devDependencies: {
    localDevDep: ''
  }
});
```
A parameter can be added to addDevDependencies/addDependencies.

**Comment by baconandon** [comment]
Thanks for looking into this @mshima 😄 

For now I have a workaround: I can use [latest-version](https://www.npmjs.com/package/latest-version) to resolve public and private dependency versions before invoking `addDependencies/addDevDependencies` with a structured-object e.g.
```
const packagesWithVersions = getVersions(['@foo/bar', '@foo/baz'])
// looks like { "@foo/bar": "1.2.3", "@foo/baz": "4.5.6" }
this.addDevDependencies(packagesWithVersions)
```
instead of 
```
this.addDevDependencies(['@foo/bar', '@foo/baz'])
 ```

**Comment by mshima** [comment]
@baconandon maybe you could provide a PR switching to latest-version at:
https://github.com/yeoman/generator/blob/9cab8c90decdbbc6befcae0da10d55da3f7cd873/lib/actions/package-json.js#L24-L28

**Comment by mshima** [comment]
should be fixed at v6.
