### ISSUE TITLE
API to modify JS files

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator#138]
Currently we do ugly stuff like regex and appending.

Might explore using Esprima or something. Ideas?

Possible tools:

- https://github.com/Constellation/escodegen
- https://github.com/substack/node-falafel
- https://github.com/millermedeiros/rocambole/

**Comment by SBoudrias** [comment]
This have been in the documentation for a while: http://yeoman.io/authoring/file-system.html

Let's close this issue.
