### ISSUE TITLE
Cannot Remove Default Add-In

### ISSUE THREAD

**Issue by gagestinson** [yeoman/generator#1466]
I was developing an add-in and when installing the generator I ran it by default to see how it looked in Outlook. It displays fine, I then uninstalled it and node is not running but the add-in buttons are still there and I cannot figure out how to get rid of them.
![image](https://github.com/yeoman/generator/assets/132514592/0c74ae3b-f117-46ec-8873-f0664992adaf)

**Comment by mshima** [comment]
you need to post at the specific generator repository.
