### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by ystxn** [yeoman/generator#1497]
yo@v5 completely broke support for `require` imports, thereby breaking all existing generator projects. Yet, all documentation and examples have yet to be updated.

**Comment by jwohlfahrt** [comment]
+1 to this request. Would love some up to date documentation to make migration a bit less painful. Thanks for opening this issue!

**Comment by thomaslagies** [comment]
Any updates so far? 
I'm still on v4 because of this.

Also, there are releases for v7, but the latest installable npm package is still on v5.

Am I misssing something?
