### ISSUE TITLE
How to compose generators in our own ESM-based generator

### ISSUE THREAD

**Issue by springcomp** [yeoman/generator#1505]
I’m authoring a custom ESM generator using TypeScript.
I’m having a hard time finding documentation for composing existing generator.

Is there any documentation available ?
Is this possible ? If so how one would achieve such features.

I have created a simple [`generator-readme`](https://github.com/springcomp/generator-readme/tree/esm) to demonstrate the issue I have.

I’m having a hard time trying to [compose with the existing `generator-license` generator](https://github.com/springcomp/generator-readme/blob/42d3b7ef75d0f0b3f933dd9a8c16beda81d4ce9d/generators/app/App.ts#L64):

```typescript
  public async default() {

    if (this.options.license) {
      console.log(import.meta.url);
      const path = resolve('generator-license', import.meta.url);
      console.log(path);
      const licenseOpts: LicenseOptions = {
        publish: false,
      };
      this.composeWith<GeneratorLicense>('license', [], licenseOpts);
    }
  }
```

**Comment by mshima** [comment]
- composeWith is async, you need to await it.
- is generator-license registered. If it’s not you can composeWith the resolved path.

**Comment by mshima** [comment]
> * composeWith is async, you need to await it.
> * is generator-license registered? If it’s not you can composeWith the resolved path.

**Comment by springcomp** [comment]
> > * composeWith is async, you need to await it.
> > * is generator-license registered? If it’s not you can composeWith the resolved path.

Would you please help me out ?

I have not been able to make your suggestions work:

```js
  public async default() {

    if (this.options.license) {
      const path = resolve('generator-license', import.meta.url);
      const licenseOpts: LicenseOptions = {
        publish: false,
      };
      await this.composeWith<GeneratorLicense>(path, licenseOpts);
    }
  }
```

I would like to compose with an embedded generated included as a dependency, rather than relying on the user having to install the required generator themselves.

**Comment by mshima** [comment]
If path is an url you should convert to file path.

**Comment by springcomp** [comment]
> If path is an url you should convert to file path.

`path` is a file path that points to the `generator-license` library under the `node_modules/` folder.

**Comment by mshima** [comment]
I don’t know if you understood, but resolve return is an url.
See https://www.npmjs.com/package/import-meta-resolve#use
It’s `file://*` you should convert to file path.

**Comment by springcomp** [comment]
Hello @mshima  thanks for clarifying.

I have indeed converted the `file://` URL to a local path.
However, that still does not work.
In fact, it turns out that the `composeWith` method really expects a URL with a `file://` scheme.
So the error remains.

```typescript
import { fileURLToPath } from 'node:url';
…
  public async default() {

    if (this.options.license) {
      const path = resolve('generator-license', import.meta.url);
      const localPath = fileURLToPath(path);
      console.log(localPath);
      const licenseOpts: LicenseOptions = {
        publish: false,
      };
      await this.composeWith<GeneratorLicense>(localPath, licenseOpts);
    }
  }

```

I’m still having a hard time figuring out how to compose generators.
