### ISSUE TITLE
hookFor options not being passed on

### ISSUE THREAD

**Issue by necolas** [yeoman/generator#214]
I have an `all` generator that runs several sub-generators. One of those generators – `app` – installs dependencies once it's finished. But when `all` is being run, I'd like to skip installation in the `app` generator and have `all` decide when to install dependencies (after all the sub-generators have been run).

I have this in `all`:

``` js
this.hookFor('mygen:app', {
  options: {
    'skip-install': true
  }
});
```

And this in `app`:

``` js
this.on('end', function () {
  this.installDependencies({ skipInstall: this.options['skip-install'] });
});
```

My expectation was that when `app` is run from `all`, it would skip the installation of dependencies. But it doesn't. The `skip-install` option is never part of the `options` hash that `app` has access to.

Is this a bug or am I missing something? Thanks

**Comment by SBoudrias** [comment]
Closing since we're getting rid of `hookFor` (and `invoke`) in favor of the better `composeWith`.
