### ISSUE TITLE
Keep exec mode on file copy

### ISSUE THREAD

**Issue by jdespatis** [yeoman/generator#235]
Hello,

I'm using `this.copy("fromFile.sh", "toFile.sh")` to copy a file which has 0755 as chmod on a Linux.
This chmod is lost on the copy and not applied to `toFile.sh`

Why not adding a third param `keepMode` to `actions.copy` and `actions.template`, to tell to keep or not the mode?

Or maybe keep the mode by default (espacially the +x mod, if it applies to current OS) ?

**Comment by ChuckJonas** [comment]
what's the solution here?
