### ISSUE TITLE
Separate the core and the generator instances

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#315]
At the moment, every Yeoman helper function is directly linked to the generator instance (`this.write`, `this.log`, `this.spawn`, etc).

This is good for a lot of them as they need to be executed in context, but for a lot of other methods, that's not really the case.

I wonder if it wouldn't be cleaner to separate the generator instances from the utility functions. And instead of calling `this.spawn`, being able to call `yo.spawn`.

_I haven't check exactly which methods are context independent, so maybe there's not enough to make it worthwhile._

**Comment by MarcoScabbiolo** [comment]
> plus it liberate devs from the hassle of this binding for free

That sounds like a good enough reason for me!

On top of decoupling the utility methods from the Generator instance it would be nice to *auto-bind* the methods that **need** to run in the context of the Generator so we can pass them around without having to bind them every time.

Decoupling may take some effort but just binding the methods shouldn't take so much, I could do it if everybody is OK with the idea.
