### ISSUE TITLE
[Composability] Generators composability

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#345]
Hi there,

I would've post on Yo.next repo, but issues are closed over there, so...

Anyway, we spoke about how 2.0 should allow better composability between different generators. There wasn't any clear way of possibility, so we should brainstorm over how generators could work togheter.

---

I was thinking about the issue, and I felt like an `intent` API (like web intent or the android core intent system) could make sense in this case.

Let's say Angular generator generates a controller and would like to scaffhold a test. It could trigger an intent like `.intent('test', { filePath: 'controllers/foo.js' })` and then other generators who're listening to the `test` event can respond accordingly. Of course `test` is an easy one, I can see how some types of intent could be harder to define... But it is a way of specifying standard communication protocol between multiple generators.

**Comment by gliwka** [comment]
Two years later, any plans to implement this?

**Comment by SBoudrias** [comment]
@gliwka No immediate plans.

**Comment by alexbab** [comment]
Hi,
https://github.com/yeoman/generator-node/pull/186/files
I can't get this to work does it mean it hasn't been implemented?

**Comment by mischah** [comment]
Hi @alexbab,

I would recommend asking support questions over here: https://gitter.im/yeoman/yeoman

**Comment by alexkreidler** [comment]
See https://github.com/yeoman/generator/issues/1084#issuecomment-569913969 for an update on the ecosystem as of 2019
