### ISSUE TITLE
Project specific generators

### ISSUE THREAD

**Issue by hurrymaplelad** [yeoman/generator#348]
Any thoughts on writing generators specific to a single project?

Say I'm writing a blog and I want to generate posts (like the [example generator](http://yeoman.io/generators.html#writing-your-first-generator)), but my blog's directory structure is a little funny, and I want to include some extra head matter.  No canned npm generator will match my idiosyncrasies, so I'll have to cobble one together.  I don't really want it in a separate package, since it's tightly coupled to this one project.

Let's say I put it in `<project_root>/generators`.  How do I register it with `yo`?
- `npm link` will work but it feels hacky.  I have to remember to re-link after each clone.
- `bundledDependencies` could be an option, but they [don't work quite right yet](https://github.com/isaacs/npm/issues/2442).
- [relative paths in package.json](https://github.com/isaacs/npm/issues/1558) would also be nice.

Anyone else running into this?  Is outside the scope of yeoman?

**Comment by cancerberoSgx** [comment]
I've accomplished this with something like this, just in case somebody needs it:
```sh
mkdir myproj
cd myproj
npm init -y
npm install yo ../generator-mine
node node_modules/yo/lib/cli.js ./node_modules/generator-mine/generators/app/
```

**Comment by SBoudrias** [comment]
If you want to install yo locally, you can use `yarn` which will then allow you to run `yarn yo ./path`. Yarn automatically use the locally installed binary. (`yarn yo`, `yarn jest`, `yarn nsp`, etc etc)
