### ISSUE TITLE
Provide optional JSON output

### ISSUE THREAD

**Issue by bebraw** [yeoman/generator#441]
It would be handy if it was possible to get JSON output of the tool instead of regular text. This would enable developers to write tools that operate on the generated files as you could pipe the output to some tool that then does something based on the input.

Example:

```bash
yo angular:filter --json | reindent
```

Format could be something like this (alter as needed):

```json
{
    "added": ["file1.js", "file2.js"]
}
```

TLDR; Optional JSON output would provide a natural extension point for tool developers.

**NOTE** I submitted this idea originally to [generator-angular](https://github.com/yeoman/generator-angular/issues/524) and @passy suggested I post it here instead so here we go.

**Comment by SBoudrias** [comment]
Every files writes now go through a stream and anyone can add filters on that streams to do whatever they need.

As so, I believe this issue is now resolved as there's a way to intercept every file writes. You can read our release blog post for more details: http://yeoman.io/blog/release-0.18.html
