### ISSUE TITLE
Emit events for file writes

### ISSUE THREAD

**Issue by teq0** [yeoman/generator#496]
(This is carrying on from https://github.com/yeoman/yeoman/issues/1238 since that project was locked down.)

There are times when it would be useful within a generator to be able to do some additional whenever files are created or modified, such as being able to add them to a project file (e.g. a .csproj file for Visual Studio).

The simplest way to allow generators to do this would be to have events raised when this happens, particularly from in actions.js whenever there is a fs.writeFileSync() etc.

Note that the .csproj file is just one example.  A custom generator might want to do things like create a JIRA task to start a workflow for, say, internationalisation, or tag files to be included into resource sets that will later be bundled.

It would just take adding something like 

    this.emit('file.write', { action: 'copy', dest: destination, src: source });

after each fs.writeFileSync() or other method that modifies a file.

**Comment by SBoudrias** [comment]
Provided you use the new in memory file-system, every file writes are going to pass through a stream.

As so, you can add streams filters and handle every file who're going to be written to disk. See our release blog post for more details: http://yeoman.io/blog/release-0.18.html

**Comment by teq0** [comment]
Thanks. The original use case we had kind of went away so I didn't go much further with it. This is a much cleaner solution.
