### ISSUE TITLE
template() now accept a forth parameter (_.templateSettings)

### ISSUE THREAD

**Issue by davidemoro** [yeoman/generator#517]
Tested on: "yeoman-generator": "~0.17.0-pre.1" (I know, I am testing a pre-release version :)

The template is not rendered with custom templateSettings (unless you put almost one entry **<%= prop %>**).
How to reproduce
----------------------
app/index.js:

    this.template('_buildout.cfg',
                  'buildout.cfg',
                   this,
                   {
                    evaluate: /\{\{([\s\S]+?)\}\}/g,
                    interpolate: /\{\{=([\s\S]+?)\}\}/g,
                    escape: /\{\{-([\s\S]+?)\}\}/g
                   }
    );

app/templates/_buildout.cfg:

    recipe = rod.recipe.mongodb
    darwin-32bit-url = http://downloads.mongodb.org/...-{{=mongodbVersion}}.tgz

If you add somewhere **<%= mongodbVersion %>** in a comment of the _buildout.cfg template, it works. See https://github.com/davidemoro/generator-mongodb/blob/master/app/templates/_buildout.cfg#L17 for example

**Comment by SBoudrias** [comment]
Just as a followup.

Using `mem-fs-editor` interface won't cause this issue. This is available as `this.fs.copyTpl()`. See our release note and documentation about this feature:

- http://yeoman.io/blog/release-0.18.html
- http://yeoman.io/authoring/file-system.html

We plan to deprecate most of the legacy file system - or at least get rid of these weird side effect behavior. As so, I think it's fair to say we won't fix the legacy API as we're looking forward to our new utilities.
