### ISSUE TITLE
Gruntfile doesn't take into account Coffee based version

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator#546]
https://github.com/yeoman/generator/blob/master/lib/base.js#L149-L169

**Comment by SBoudrias** [comment]
I'll close this issue because it's pretty much a dreamer issue. I don't think anyone physically have the time to fiddle a coffeescript AST parser or a sourcemap communication protocol to get this to work.

I fear the issue would stay open forever, so let's be honest and assume we won't fix it.
