### ISSUE TITLE
Create symlink from within the generator

### ISSUE THREAD

**Issue by mulderp** [yeoman/generator#547]
Hi,

I am seeing:

```
    this.mkdir('app/node_modules');
```

but how could I create symlinks into that directory?

Thanks!

**Comment by cueedee** [comment]
Well, I needed this feature and so took up the task suggested; the result of which can be found in [this gist](https://gist.github.com/cueedee/e8746a94c9af9b796c6b1530e69d3587) for whoever wants it too.
