### ISSUE TITLE
composeWith should take prompt arguments

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator#552]
If it does already, the docs should be updated. If not, it should allow passing in an object that gets resolved to prompts like the test withPrompts option.

**Comment by sambaker** [comment]
For anyone who needs to support options or prompts - which could be desirable for any generator that might be used within another generator via composeWith, you can use this helper that I created:

https://github.com/artefact-group/yeoman-option-or-prompt

The reason I wrote that is that I created a generator that uses generator-node-webkit but the default of using prompts for user input means my generator's UI has the UI of generator-node-webkit embedded in the middle of it including a duplicate prompt for the same data (app name). This is not a good user experience so I'd like to see more generators supporting options.

The helper doesn't cover all of the functionality of prompts, such as validating the input but it does allow prompts to be skipped as necessary.

**Comment by surprisetalk** [comment]
@sambaker +1 thank you so much
