### ISSUE TITLE
composeWith return the answers from prompt

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator#553]
The answers from the prompt from the composed generator should be returned to the calling generator so they can be used there as well.

Example:

* My generator calls generator-angular
* generator-angular asks the user if they want to use sass and user says yes
* generator-angular should tell my generator the user said yes to sass
* My generator then installs sass things as well

**Comment by SBoudrias** [comment]
Hey, I'm going to close this issue because I really don't want to overload the prompts. I think the way to pass options is not so horrible and is more predictable.

**Comment by tjwebb** [comment]
> I think the way to pass options is not so horrible and is more predictable.

Maybe, but I had to spend 10 minutes googling various combinations of "yeoman composewith subgenerator answers return context etc etc" in order to locate this solution. Can this be added to the Composability docs?

**Comment by zckrs** [comment]
A good example of composition  https://github.com/yeoman/generator-node/tree/master/generators

**Comment by tjwebb** [comment]
I've looked through that code, since node-generator is actually the sub-generator I'm trying to do this with: https://github.com/trailsjs/generator-trailpack/blob/master/src/app/steps/default.js#L7

But for example, in my "writing" step, I'd like to say something like:

```js
this.subgenerators['node:app'].options.name
```

or something. How can I get at the values that the `node:app` generator saves from its prompts?

**Comment by SBoudrias** [comment]
@tjwebb the values only travel from top -> down.

You can see how `generator-generator` does it. It pass all the values it handles to generator-node https://github.com/yeoman/generator-generator/blob/master/app/index.js#L49

Generator node generates `this.props` from multiple entry points:

1. `this.options` (it'll skip prompts who's answer are provided through options - that's the `when` option)
2. Its own prompt answers

FWIW, I know this system is not always ideal and that it creates boilerplate. But this system was built primarily to be backward compatible (to a degree) with legacy generators and to fit in the current infrastructure. I hope I'll have a chance to eventually review the core design of some parts of Yeoman - but I'm still pushing yeoman-generator towards a stable 1.0 release that'll remove bad parts of our legacy system to improve end user experience. That's currently the priority. And also, the composability design have some solid bases to prevent coupling and keep the relation between generator maintainable - that's the main goal for now. Keep stuff maintainable so it's not too difficult to upgrade in the future.

For the documentation, help is warmly welcome to improve it. So please do send a PR.

**Comment by tjwebb** [comment]
> @tjwebb the values only travel from top -> down.

Then how do I get the name of the node module from the node-generator if I'm using it as a sub-generator? Surely I don't to prompt the user to enter the name twice just so I can get access to what's already been entered. I don't see a way to do this.

**Comment by SBoudrias** [comment]
@tjwebb your generator ask for the name and pass it down to generator-node.

Another option is to read that name from `package.json`.

**Comment by tjwebb** [comment]
> @tjwebb your generator ask for the name and pass it down to generator-node.

Just to confirm what you're saying: for all the values I want answers for, I need to copy the prompts from generator-node code and paste them into the main generator, and then pass them down. 

> Another option is to read that name from package.json.

Sure, but I need like 5 other fields as well. That's just an example.

**Comment by SBoudrias** [comment]
> I need to copy the prompts from generator-node code and paste them into the main generator, and then pass them down.

Yes, everything goes from top to bottom.

**Comment by tjwebb** [comment]
Ok, thanks. It makes sense to me to only pass *options* down the chain. But when the user provides input, those values need to be accessible anywhere. Would a modification of this sort be merged if I submit a PR?

**Comment by SBoudrias** [comment]
> Would a modification of this sort be merged if I submit a PR?

Honestly probably not, if we're changing this, this mean data doesn't flow top to bottom anymore. This is a very important point to keep any code maintainable.

**Comment by tjwebb** [comment]
@SBoudrias ok, so any suggestions on how I can solve my problem?

**Comment by jmls** [comment]
@tjwebb did you ever figure out a solution to this ? I have exactly the same problem. I need to run a sub-generator (not one I authored) and do some work based on the answers entered in the sub-generator

**Comment by Telokis** [comment]
Years pass but I'd like to know how to do something similar as well, please!

**Comment by tborychowski** [comment]
mee too!

**Comment by mshima** [comment]
The sub-generator must export it to a shared object.
I really don't see a reason to share them by default.

At the main generator:
`this.composeWith(namespace, {sharedAnswers: {}});`

At the sub-generator:
`this.prompt().then(answer => {this.options. sharedAnswers.subAnswer = answer;});`

I have created a sharedData at:
https://github.com/yeoman/environment/commit/35203ffcf48e1e6646b8404f396b523212e1c06f
But it's not released yet.
