### ISSUE TITLE
bowerInstall interactive false

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator#571]
Perhaps we should add `--config.interactive=false` to the bowerInstall so the silly prompts are ignored? per http://bower.io/docs/api/#running-on-a-continuous-integration-server

_edit (@sboudrias): updated link to bower doc_

**Comment by SBoudrias** [comment]
Is `npm` and `bower` still running concurrently in the latest version? I'm pretty sure they're now running one after the other, so it appears to me this fix this issue right?

**Comment by SBoudrias** [comment]
Oh the question is also in which order the should run by default: npm first then bower?

**Comment by eddiemonge** [comment]
I want to say the order doesn't matter but maybe npm should always go first. Although if there are post-install things in package.json that depend on bower things maybe it should go last. I don't know. Maybe a configuration to specify which goes when

**Comment by SBoudrias** [comment]
@eddiemonge you can call them independently in any order. I was wondering about the best default for `this.installDependencies()`.

**Comment by ruyadorno** [comment]
npm before bower makes much more sense, it's the same order in which you install them anyway...

**Comment by cameronjroe** [comment]
@ruyadorno definitely agree

**Comment by SBoudrias** [comment]
Ok so the only thing left to fix this one is to change the order from bower -> npm to npm -> bower.
