### ISSUE TITLE
Callback passed to conflicter.once never fires while copying a directory

### ISSUE THREAD

**Issue by osilviotti** [yeoman/generator#596]
I'm trying to copy the contents of a repo into the root of the project when a generator is run but am getting an `illegal operation on a directory` error. To try and combat it I tried generating a fresh generator and pasting the example given in the documentation into the `projectfiles` function (giving it this repo to download) like this:

```
this.remote('yeoman', 'generator', function(err, remote) {
    remote.copy('.', 'vendors/user-repo');
});
```

but still get the error

```
/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/node_modules/graceful-fs/polyfills.js:224
  throw er
        ^
Error: EISDIR, illegal operation on a directory
at Object.fs.readSync (fs.js:476:19)
at Object.fs.readSync (/usr/local/lib/node_modules/yo/node_modules/insight/node_modules/configstore/node_modules/graceful-fs/polyfills.js:218:23)
at module.exports (/Users/ollie/Documents/git/generator-adapt/node_modules/yeoman-generator/node_modules/isbinaryfile/index.js:14:17)
at _prepCopy (/Users/ollie/Documents/git/generator-adapt/node_modules/yeoman-generator/lib/actions/actions.js:50:16)
at copy (/Users/ollie/Documents/git/generator-adapt/node_modules/yeoman-generator/lib/actions/actions.js:83:19)
at Object.copy (/Users/ollie/Documents/git/generator-adapt/node_modules/yeoman-generator/lib/actions/actions.js:436:12)
at /Users/ollie/Documents/git/generator-adapt/app/index.js:53:14
at done (/Users/ollie/Documents/git/generator-adapt/node_modules/yeoman-generator/lib/actions/actions.js:492:5)
at /Users/ollie/Documents/git/generator-adapt/node_modules/yeoman-generator/lib/actions/actions.js:407:16
at Object.oncomplete (fs.js:107:15)
```

Running OSX 10.9.2 - output of the set of commands in the issue submission instructions:

```
1.2.0
~/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/ollie/android-sdk/platform-tools:/Users/ollie/android-sdk/tools
darwin { http_parser: '1.0',
  node: '0.10.26',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.25',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e' }
cat: Gruntfile.js: No such file or directory
```

**Comment by sthzg** [comment]
@SBoudrias FWIW, while trying to answer [Using yeoman to scaffold a template contained in a git-repo?](http://stackoverflow.com/q/35174347/870769) on SO I ran into this. Here is a Gist that leads to this error for me: https://gist.github.com/sthzg/e8fa2e0f769382474d9b

yeoman-generator: 0.20.3
node: 5.6.0
(on Mac OS X)

**Comment by SBoudrias** [comment]
@sthzg remote is an async action, you'll need to use `this.async()`

**Comment by sthzg** [comment]
@SBoudrias thanks for pointing out, that might have certainly triggered unexpected surprises. In the example it still only works for me with `bulkDirectory()`. 

However, as @ollie101 pointed out above, `copy()` might just be the wrong method to call when trying to recursively copy a whole directory from the Git repo (`remote.copy('.', 'dest')`) rather than a single file? If yes then that would be my point of confusion after reading the [JSDocs on remote actions](http://yeoman.io/generator/actions_remote.html). So, at least if this is true, the options in that case would be `remote.directory()` if I can specify all template variables or `remote.bulkDirectory()` for just copying the files over.

**Comment by SBoudrias** [comment]
@sthzg ideally, you'd use `mem-fs-editor this.fs.copy()` functions rather than the legacy `x.copy` ones.

**Comment by sthzg** [comment]
@SBoudrias I see, something like that?

```js
writing: function () {
  var done = this.async();
  this.remote('yeoman', 'generator', (err, remote) => {
    this.fs.copy(remote.cachePath, 'generator', { globOptions: { dot: true } });
    done();
  }); 
}
```
