### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by thaiat** [yeoman/generator#637]
Hi,

As I'm starting to write my second generator, I realized that there is some common functionnality that I would like to share in a custom base generator class.

So far the template code for inheritance i'm using with looks like that:

Let's say we have the following code :

``` javascript
var SuperGenerator = BaseGenerator.extend({
});
```

To override the constructor I use the following syntax:

``` javascript
constructor : function() {
   BaseGenerator.apply(this, arguments);
}
```

To override a method I use the following syntax:

``` javascript
myFun : function() {
   SuperGenerator.__super__.myFun.apply(this, arguments);
}
```

The syntax is kinda ugly. So i wrote this little helper 

``` javascript
callBaseFn : function(Parent, fnName) {
  if(_.isFunction(Parent.__super__[fnName])) {
    Parent.__super__[fnName].apply(this, arguments);
  }
},
```

and now i can do :

``` javascript
SuperGenerator = Base.extend({
//// other code not shown here ///

  // overriding end function
  end: function() {
    this.callBaseFn(SuperGenerator, 'end');
  }
});
```

Off course ideal situation would be to automatically infer the Parent and fnName but in strict mode you don't have accecss to `arguments.caller`...

Does this make any sense ?

**Comment by sdeering** [comment]
Did anyone work this one out?
