### ISSUE TITLE
Ability to copy whole folder

### ISSUE THREAD

**Issue by knownasilya** [yeoman/generator#642]
This might be very handy and cleanup some generators where first you do

``` js
this.dest.mkdir('folder1');
this.dest.mkdir('folder1/folder2');
this.src.copy('folder1/file1.f', 'folder1/file1.f');
//...
```

Which instead could be: 

``` js
this.src.copyFolder('folder1', 'folder1');
// or
this.src.copy('folder1', 'folder1', true);
```

**Comment by guiajlopes** [comment]
I'm trying to use .directory but it isn`t copy all files, just something. Everyone know's why?

**Comment by SBoudrias** [comment]
@guiajlopes use `this.fs.copy()` with glob patterns like `**/*`. Also, please refer to our documentation of handling the file system http://yeoman.io/authoring/file-system.html

**Comment by guiajlopes** [comment]
Thanks @SBoudrias . I didn't see the documentation of this functions, what's the params? Can you help me? thanks

**Comment by knownasilya** [comment]
Looks like the docs are here: https://github.com/sboudrias/mem-fs-editor#copyfrom-to-options

**Comment by guiajlopes** [comment]
thanks

**Comment by codeitagile** [comment]
I worked around my lack of knowledge to copy a directory en-masse whilst also applying template data to  files with leading underscores as follows: https://gist.github.com/codeitagile/19e7be070b6ef46c21d2

__NB:__ work-around derived from http://bit.ly/1WmHME0

**Comment by SBoudrias** [comment]
@codeitagile you should really look at the new file helpers based on `mem-fs-editor` http://yeoman.io/authoring/file-system.html - they support glob patterns, so that process would be trivial to implement.

**Comment by codeitagile** [comment]
@SBoudrias thanks for prompting me to revisit this. I took a closer look at the `mem-fs-editor` tests in particular http://bit.ly/1PAqcuD, and you are right there is a trivial implementation of what I was after.

**Comment by codekraft-studio** [comment]
I looked to the options listed in this page https://github.com/isaacs/node-glob#options, and I would like to recursive copy only folders and subfolders without files in it.
What can I do? Maybe using **ignore** options with a pattern for files like *.* would work? Any idea or suggestion?

Thanks!

**Comment by mischah** [comment]
@codekraft-studio 

I’d recommend to head over to one of our [Gitter rooms](https://gitter.im/yeoman/home) and ask for help. There is a broader audience.
