### ISSUE TITLE
remote() and extract() unzip wrong directory structure

### ISSUE THREAD

**Issue by mvilrokx** [yeoman/generator#664]
I just started creating my first generator.  I am fetching a zip file and try to copy it's content into a folder (/app) but for some reason, the unzipped directory structure does not match the one in the zipfile.  When I download the file in the browser and unzip it normally (using Archive Utility.app), I get the correct folder structure.  Also, when I run 'zipinfo' on the zipfile, it shows the correct directory structure.  This is the folder structure I am expecting:

```
/js
    /libs
/css
    /images
    /fonts
    /libs
/scss
    /oj
```

However, this is what I get instead:

```
    /libs
    /images
    /fonts
    /oj
```

It seems to loose the parent dir of each of these directories.  Here is the code in my generator that fetches the zip file:

```
this.remote('http://foo/bar.zip', function(err, remote) {
  if (err) {
    done(err);
  }
  remote.directory('.', './app');
  done();
});
```

I also tried using extract(), exact same result:

```
this.extract('http://foo/bar.zip', '.app', function(err, remote) {
  if (err) {
    done(err);
  }
  // remote.directory('.', './app');
  done();
});
```

Can anybody point out to me what I am doing wrong?

Cheers.

**Comment by fredo-wunder** [comment]
Sorry guys i think i have a similar problem, but just installed yesterday generator-generator so i'm pretty sure i'm running the fixed version. This is my writing function in the index.js file:

```
writing: function () {
    this.extract("https://github.com/myuser/myrepo/master.zip", this.destinationPath('./'), function (err){console.log(err)});
    this.fs.copyTpl(
      this.templatePath('dummyfile.txt'),
      this.destinationPath('dummyfile.txt'),
      { title: this.props.projectName }
    );
  },
```
the thing is i'm only getting a myRepo folder empty and without any permission set :(. Could you show me what am i doing wrong? :)
thanks :)

**Comment by SBoudrias** [comment]
@fredo-wunder `this.extract` is asynchronous.

**Comment by fredo-wunder** [comment]
sorry... so? :)

**Comment by iamstarkov** [comment]
So there is no way to be sure that next line will be executed after extraction. Either you need callback or promise there, either synchronous extraction

**Comment by fredo-wunder** [comment]
mhm... but i got an empty folder after everything was run. 

anyhow: got it working adding the repo to my package.json and copying it from node-modules. thanks!
