### ISSUE TITLE
bulkDirectory doesn't respect destinationRoot

### ISSUE THREAD

**Issue by rpfeifle** [yeoman/generator#716]
My generator plays around with destinationRoot, but bulkDestination doesn't respect this.

Looking at the code from the API pointer, it looks like the source adjusted to be relative to sourceRoot, but that nothing is done to the destination.

Thanks!
Ron

linux { http_parser: '1.0',
  node: '0.10.31',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.28',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1i' }
cat: Gruntfile.js: No such file or directory

**Comment by Mickey-** [comment]
+1

**Comment by SBoudrias** [comment]
`bulkDirectory` will be removed with the next 1.0 release. I'll close this issue.

**Comment by kianting** [comment]
@SBoudrias if bulkDirectory is removed what will be in it's place ? Is there a reference doc that talks about this ?

**Comment by SBoudrias** [comment]
@kianting it depends what you need. Most like you just want to glob a folder and copy everything: `this.fs.copy(this.templatePath('dir/**'), b)`

What's your use case?

**Comment by kianting** [comment]
@SBoudrias I want to copy everything from the template folder to the destination folder, this would include all its subdirectories and files.

**Comment by SBoudrias** [comment]
@kianting then `this.fs.copy(this.templatePath('**'), b)` should work. What's happening in your case?
