### ISSUE TITLE
inDir() property of helpers.run does not work as expected in version 0.18.0

### ISSUE THREAD

**Issue by ficheva** [yeoman/generator#718]
Hi,
I am opening a new issue related with our discussion in issue #699.
I am sending a zip file with our generators (have in mind that in the package.json file we fixed the version of yeoman-generator to 0.17.0 so that our test could pass) because the repo is in GitHub, but it is private. Let me know if you prefer to give you access to the repo.

**Comment by ficheva** [comment]
@stefanbuck <code>withGenerators()</code> is used together with <code>composeWith()</code> which is not my case.

**Comment by gruppjo** [comment]
@ficheva in case you haven't noticed. I'm trying to get a `withLocalConfig` method upstream that might help you decouple your tests and still have your generators depend on each other.
