### ISSUE TITLE
Avoid the use of process.chdir() in Base.js?

### ISSUE THREAD

**Issue by adenhertog** [yeoman/generator#731]
Base.js internally uses process.chdir() to set the application root. While this is fine for yo/cli.js, it causes a bit of an undesirable side effect when running via yeoman-environment in a long-running, hosted node.js process. 

Would there be any consequences of removing process.chdir() in favour of resolving src/dest paths during execution?

**Comment by sindresorhus** [comment]
Why are you running yeoman-environment in a long-running process? What's your use-case?

**Comment by blai** [comment]
I recently learned that some developers are turning yeoman into sort of a hosted service, where a web based client will trigger the generator on the server side. I think this is one of those cases.

**Comment by SBoudrias** [comment]
You could spawn yeoman generators in child processes.

**Comment by adenhertog** [comment]
I run node-webkit, and the client instructs the server to run a new yeoman generator. All messages and prompts are sent to the client using a custom adapter that emits them to the client via socket.io.

Spawning a new process would avoid the interference with the host process, but it wouldn't have visibility of the socket to communicate back to the client.

**Comment by SBoudrias** [comment]
@adenhertog yeoman-generator are blocking. As so, it just doesn't make sense to run them in the main process of a server.

I suggest you find a way to run them in child/sub processes. I don't see a point to change yeoman-generator to not use chdir as it doesn't make sense to run them as part of a persistent process.

There's a lot of ways to fix the communication issues you have (an advanced solution could be a message queue, but there's probably simpler ones).

**Comment by adenhertog** [comment]
No worries then, I'll put a comm layer over it and push it to a new process. Thanks.

**Comment by adenhertog** [comment]
FYI to anyone who hits this later, my approach was to fork a child process and pump messages back to the parent process in a custom adapter. eg:

Server
```coffeescript
ChildProcess = require "child_process"

module.exports = 
	runPublic: (destination, template, callback) ->
		runner = this.launchRunner { destination: destination, template: template, mode: "public" }
		runner.on "close", (code, signal) -> 
			# when the runner has completed
			callback() if callback?

	launchRunner: (args) ->
		child = ChildProcess.fork "../yeoman-runner/index.js"
		
		args.type = "run"
		child.send args
		
		child.on "message", (data) ->
			# triggered when the yeoman-environment has something to say

		return child
```

yeoman-runner/index.coffee
```coffeescript
path = require "path"
Environment = require "yeoman-environment"
ProcessAdapter = require "./adapters/processAdapter"

YeomanRunner = module.exports =

	adapter: ProcessAdapter process
	
	run: (args) -> 
		env = Environment.createEnv(null, args, this.adapter)
		env.lookup()

		process.chdir args.destination
		
		env.run args.template, null, ->
			process.exit()

	initialize: -> 
		# on messages from parent process
		process.on "message", (m) => 
			switch m.type
				when "run" then this.run m
	
YeomanRunner.initialize()
```

processAdapter.coffee (A custom adapter) would look something like:
```coffeescript
module.exports = (parent) -> 
	prompt: (questions, callback) ->
		parent.send { type: "prompt", value: questions }
		# TODO create a prompt callback 
				
	diff: (actual, expected) ->
		parent.send { type: "diff", actual: actual, expected: expected }
		# TODO create a diff callback
		return actual
				
	log: 
		create: (rfilepath) ->
			parent.send { type: "create", value: rfilepath }
					
		identical: (rfilepath) ->
			parent.send { type: "identical", value: rfilepath }
					
		log: (msg, ctx) ->
			parent.send { type: "log", value: msg }
```
