### ISSUE TITLE
Offers a way to mix-in generators

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#733]
ATM the only built-in way to reuse functionalities with Yeoman is inheritance:

``` js
var BaseGen = generator.Base.extend();
var myGenerator = BaseGen.extend();
```

That's fine, but it's hard to share multiple decoupled functionalities as prototypes only support single inheritance.

We could offer a way to easily mix-in functionalities in Yeoman. That's the API I have in mind:

``` js
var mixin = require('yeoman-mixin');

var myMixin = mixin({
  prompting: function () {},
  _someMethod: function () {}
});

var Generator = generator.Base.extend({
  prompting: function () {}
});
myMixin.mix(Generator);
```

Which would basically results in:

``` js
Generator.prototype.prompting.prompting1 = function () {};
Generator.prototype.prompting.prompting2 = function () {};
Generator.prototype._someMethod = function () {};
```

This can be done pretty easily. I wonder if we should make it more complex by separating scope between mixins and original prototype or something like that... Maybe something to consider later on?

**Comment by arthurvr** [comment]
I like that idea! :+1:
