### ISSUE TITLE
withLocalConfig() method for RunContext

### ISSUE THREAD

**Issue by gruppjo** [yeoman/generator#742]
I followed the discussion on issue #718 and have a suggestion to make, since I have a similar problem:

After generating the project with the main generator, some of the sub-generators depend on choices the users made while running the main generator. E.g. the project's module name is `myModule`. Later when generating controllers, views, etc... in the project using the sub-generators, the sub-generators need to know they're creating a component for `myModule`.

So naturally you would write the following in the main generator:
```
this.config.set('moduleName', userInput);
```
And the counterpart in the sub-generator:
```
this.moduleName = this.config.get('moduleName');
```

Unfortunately, as far as I know, this cannot be tested, since the tests always start in a fresh directory. Obviously this results in errors when testing sub-generators independently.

However if there was a possibility to provide the `.yo-rc.json` contents to the run context, it would be possible to run your tests independently in a decoupled fashion but also make adjustments based on previous choices the user made.

What do you think?

**Comment by SBoudrias** [comment]
I think this feature make sense. PR is welcomed.

**Comment by gruppjo** [comment]
I'd be happy to help, although I'm not very familiar with the generator source code yet. If you have any suggestions on where to start looking around, I'd be grateful since it would probably make this easier for me.

**Comment by SBoudrias** [comment]
This is the file you want to be looking at: https://github.com/yeoman/generator/blob/master/lib/test/run-context.js

Also, I'd name the method `withConfig` - even maybe `withLocalConfig`

**Comment by gruppjo** [comment]
I'll get to it as soon as I can find some time :)

**Comment by gruppjo** [comment]
I was able to get some work done on this today. I have a suggested implementation that seems to work. Since this is my first attempt to contribute I didn't want to issue a PR right away but rather hear you guys' comments/opinions first:

Here's what I've done so far - https://github.com/gruppjo/generator/commit/f8b7f3e3932a432c074c0613f3d9af36891899e8

- `test/run-context.js`: write unit test for `withLocalConfig()` method - https://github.com/gruppjo/generator/commit/f8b7f3e3932a432c074c0613f3d9af36891899e8#diff-2
- `lib/test/helpers.js`: write a `mockLocalConfig()` function, that uses the generator's store's `default()` method to provide the config. This seemed an easy way to implement it, however I'm not sure whether it's a good idea to do so. - https://github.com/gruppjo/generator/commit/f8b7f3e3932a432c074c0613f3d9af36891899e8#diff-0
- `lib/tests/run-context.js`: extend the `RunContext` constructor, its `_run()` method and added a `withLocalConfig()` method to put everything together. - https://github.com/gruppjo/generator/commit/f8b7f3e3932a432c074c0613f3d9af36891899e8#diff-1
  - notice how `helper.mockLocalConfig()`only gets called when `withLocalConfig()` was called? I needed to restrict this, since otherwise one of the tests would try to create a `.yo-rc.json` in `/` (root directory) and obviously would fail (I don't know why though...).

**Comment by SBoudrias** [comment]
Hey, can you send a PR - it'll be easier to discuss it over there.

**Comment by gruppjo** [comment]
Now that the PR is merged, I've been wondering whether and where I should document this method?

**Comment by SBoudrias** [comment]
On yeoman.io testing section, otherwise the jsdoc is updated from time to time and the method will appear over there.
