### ISSUE TITLE
Deprecate `wiring.js`

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator#743]
I think we should deprecate it and remove before 1.0.0.

It should rather be a more general purpose module users that actually need it can just require themselves.

**Comment by SBoudrias** [comment]
++ extract to an extra module.

**Comment by SBoudrias** [comment]
First step is done https://github.com/yeoman/html-wiring

Now we just need to add a deprecation notice.

**Comment by sindresorhus** [comment]
Awesome :)

**Comment by addyosmani** [comment]
Thanks @SBoudrias!

**Comment by kevva** [comment]
Sweet!
