### ISSUE TITLE
Every install method should respect --skip-install flag

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#745]
ATM only `installDependencies()` accept a manually passed argument, but doesn't use the global flag.

Also, this doesn't match on documentation on the subject: http://yeoman.io/authoring/dependencies.html

Code wise this mean moving to skip install flag check into `runInstall()`.

**Comment by hemanth** [comment]
That's like adding:

```
if (options.skipInstall) {
    return options.callback();
  }
```

or 

```js
if (!options.skipInstall) {
   // rest 
  }
```

[here](https://github.com/yeoman/generator/blob/beee56cd52291b30a8312d7643ed42eab2a9ca1a/lib/actions/install.js#L34) ?

**Comment by eddiemonge** [comment]
This is working a bit wonky on generator-webapp (gulp) when using it with composeWith as the target. Not sure if that generator-needs to be updated but it does install the version of this that has this fix. The `this.options.skipInstall` is false even though `this.options['skip-install']` is true in the main generator and the composed generator-webapp.

**Comment by SBoudrias** [comment]
Currently I guess you need to pass it down the stack manually.

We probably should automatize the global level options being passed down.

**Comment by eddiemonge** [comment]
In the generators that I've seen, they use `skip-install` instead of 'skipInstall`. Switch to the dash version fixes it

**Comment by eddiemonge** [comment]
I don't actually see where it gets camelCased like that

**Comment by SBoudrias** [comment]
@eddiemonge it's done by meow on the `yo` side.
