### ISSUE TITLE
Extract the diffing logic to another package

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#749]
Let's extract the file diff to another package.

This mean:
- Move binary diff outside yeoman-generator
- Move text diff outside of the yeoman-environment

The only thing to figure out is if we should still provide the diff interface through the terminal adapter or not. I haven't thought about it yet (cc @ruyadorno @stefanbuck)

**Comment by stefanbuck** [comment]
I don't want to drop support for non terminal environments (I guess you too) and the terminal adapter is a smart mediator for that. What is the problem to keep a tiny interface in `yeoman-environment`? 

Finally, it's similar to the logger implementation, or not? https://github.com/yeoman/environment/blob/2c78d8ae699e2fd6201b13c986c7ce06d4816edd/lib/adapter.js#L74-L78

**Comment by ruyadorno** [comment]
Does it also implies changes to `util/conflicter.js` on the [yeoman/generator](https://github.com/yeoman/generator)?

What are exactly the required changes to completely extract the file diff to another package?
