### ISSUE TITLE
this.installDependencies() just crashes silently

### ISSUE THREAD

**Issue by dnozay** [yeoman/generator#752]
I'm on OSX btw.

```
(jk)Damiens-MacBook-Air:foo damien$ npm list -g yeoman-generator
/Volumes/ramdisk/jk/lib
├─┬ generator-angular@0.10.0
│ └── yeoman-generator@0.16.0 
├─┬ generator-jekyllrb@1.4.1 -> /Users/damien/Work/github/generator-jekyllrb
│ ├─┬ generator-mocha@0.1.6
│ │ └── yeoman-generator@0.17.7 
│ ├── yeoman-generator@0.18.7 
│ └─┬ yo@1.3.3
│   └── yeoman-generator@0.17.7 
├─┬ generator-karma@0.8.3
│ └── yeoman-generator@0.17.7 
├─┬ generator-mocha@0.1.6
│ └── yeoman-generator@0.17.7 
├─┬ yeoman-environment@1.2.0
│ └── yeoman-generator@0.18.7 
├── yeoman-generator@0.18.7 
└─┬ yo@1.4.2
  └─┬ yeoman-environment@1.2.0
    └── yeoman-generator@0.18.7 

```

```

Generator.prototype.a = function a() {
  var done = this.async();
  var callback = function() {
    console.log('done??');
    done();
  };
  // Install Grunt and Bower dependencies
  this.installDependencies({
    skipInstall: this.skipInstall,
    callback: callback
  });
};
```

when running the generator I get:
```


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


```

however it does not continue onto the prompts and just exits there...

**Comment by SBoudrias** [comment]
Probably related to #751

**Comment by eddiemonge** [comment]
where are you calling `done()`?

**Comment by SBoudrias** [comment]
Oh yeah, don't block the generator process on the install task. That'll create a deadlock, see https://github.com/yeoman/generator/releases/tag/v0.18.0

**Comment by dnozay** [comment]
@eddiemonge, in the callback. fixed comment; however the issue remains.
@SBoudrias, even without the callback it still crashes silently.

**Comment by SBoudrias** [comment]
@dnozay don't call `this.async()`

**Comment by dnozay** [comment]
@SBoudrias, still the same issue without `this.async()`

**Comment by SBoudrias** [comment]
Is your generator on Github? Can we see some code?

**Comment by dnozay** [comment]
i'm trying to help iron out issues on someone else's:
https://github.com/robwierzbowski/generator-jekyllrb/blob/master/app/index.js#L53-L54

**Comment by SBoudrias** [comment]
`installDependencies` is pushed on the run loop. When the `end` event is triggered, then the run loop is over so the installation will never run.

**Comment by dnozay** [comment]
@SBoudrias, I guess `generator-angular` was just setting a wrong example.
https://github.com/yeoman/generator-angular/blob/198f8c46144bda40ab76038ee5a0f445776e97f4/app/index.js#L72-L104

I guess the fix is:
```javascript
// install dependencies -- needs to be at the end
// https://github.com/robwierzbowski/generator-jekyllrb/issues/137
Generator.prototype.install = function install() {
  // Install Grunt and Bower dependencies
  this.installDependencies({ skipInstall: this.skipInstall });
};
```

**Comment by eddiemonge** [comment]
angular is using an older version of the generator before things were switched.
