### ISSUE TITLE
Confusing install options

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#754]
Options passed to bowerInstall and npmInstall are hella confusing!

Actually, the issue is they're passed both as:
1. Command line arguments (where `{foo: 1}` become `--foo=1`)
2. As `child_process.spawn` options (like `cwd` or `stdio`)

This is very inconsistent, and should be divided in their own option group.

**Comment by addyosmani** [comment]
:+1: on switching to individual option groups. Sorry about the original form being less than ideal!
