### ISSUE TITLE
Using this.option after this.argument reverts arguments in generator constructor

### ISSUE THREAD

**Issue by peterchoo** [yeoman/generator#755]
First time writing a generator, so please excuse me if I'm doing something wrong.

I've been following http://yeoman.io/authoring/user-interactions.html to create my generator, and I've run into an issue.  Give the following code:

```
var generators = require('yeoman-generator');

module.exports = generators.Base.extend({
  constructor: function() {
    generators.Base.apply(this, arguments);

    this.log(this.folderName, this.options.type);
    /**
     * Optional folderName override
     */
    this.argument('folderName', {
      description: 'Optional folder name for this component, useful if nesting',
      type: String,
      required: false
    });
    this.folderName = this._.classify(this.folderName);

    this.log(this.folderName, this.options.type);

    /**
     * Optional Type for Controller
     */
    this.option('type', {
      desc: 'Controller type: Authenticated, Unauthenticated or Neutral',
      type: String,
      defaults: 'Authenticated'
    });

    var controllerTypes = ['Authenticated', 'Unauthenticated', 'Neutral'];
    this.options.type = (controllerTypes.indexOf(this.options.type) === -1) ? 'Authenticated' : this.options.type;

    this.log(this.folderName, this.options.type);
  },
  logStuff: function() {
    this.log(this.folderName, this.options.type);
  }
});
```

There are four `this.log` statements, and they output the following:

```
$ yo myGenerator testThing  --type=Neutral
undefined 'Neutral'
TestThing Neutral
testThing Neutral
testThing Neutral
```

Yet if I swap the order of the `this.option` an `this.argument` statements, I get the following output:

```
$ yo myGenerator testThing  --type=Neutral
undefined 'Neutral'
undefined 'Neutral'
TestThing Neutral
TestThing Neutral
```

It seems like there is either a lack of documentation (I couldn't find anything on http://yeoman.github.io/generator/Base.html#option ) or the tutorial style pages.

Thanks

**Comment by SBoudrias** [comment]
Hey @peterchoo, sorry for checking this out so late.

Going over your code I'm not sure what is your issue. From what I see, in both case you end up with the correct values in the two last logs (those after you've declared all your options and arguments). And in the logs before that, the value is either undefined or the expected value.

Can you elaborate on the result you expected?

**Comment by peterchoo** [comment]
Hi @SBoudrias,

The issue is that I found no documentation that says "all calls to `this.option()` must happen before any calls to` this.argument()`".

In the code in my first post, this.log is called four times with the `foldername` argument and the `type` option. The `foldername` is the first argument added.  It's then classified and changed from `testThing` to `TestThing`.  Then the option `type` is called and evaluated.  It appears that at this point the classification of `foldername` is undone, as in the subsequent `this.log()` calls, `testThing` is output (lower case first letter).

The last codeblock of the log calls is when the order is `this.option()`, `this.argument()`.

I hope that clears it up, let me know if you have nay more questions :)

**Comment by SBoudrias** [comment]
Oh no, that's because you modify the value `this.folderName = this._.classify(this.folderName);`.

Each time you define a new arguments or a new options, we need to reparse and reset all the values as some settings might change some arguments/options values.

I'd say, either set modified value with another name, or only modify them after all of them are declared.

This is an edgy behavior, but I don't see a better way to handle it.
