### ISSUE TITLE
composewith order, using the composed-with generator first?

### ISSUE THREAD

**Issue by scottnath** [yeoman/generator#757]
Hi there,

I'm creating some generators that will all use a common base generator, however, I'd like the prompts from the base generator to come first.

Is there a way to do this?

Right now, the questions from the generator *calling* the base generator with `composeWith` are asked first.

thanks,
Scott

**Comment by SBoudrias** [comment]
A composed generator will always be schedule after. Maybe move your prompts in another sub-generator?
