### ISSUE TITLE
composeWith: using shared utilities files

### ISSUE THREAD

**Issue by scottnath** [yeoman/generator#759]
Hi Yo team,

I have two generators. Generator1 contains a util.js file with various useful scripts, Generator2 is calling Generator1 via composeWith. Is it possible for Generator2 to use functions from the util.js file in Generator1?

Something like:
```
var commonUtils = require('???/util.js');
```

Any help greatly appreciated.

thanks,
Scott

**Comment by SBoudrias** [comment]
You can create a module with those utilities. Or require them `require('generator-1/utils.js')`

**Comment by scottnath** [comment]
@SBoudrias I tried creating that `require()` statement, but got the `cannot find module` error (which I expected)

1. should the file not be required at the top of the file? should it be set after the `this.composeWith` statement somehow?
2. -or- would I want to add Generator1 to my package.json file?

thanks,
Scott

**Comment by SBoudrias** [comment]
This is basic Node.js - it's not specific to yeoman or composeWith. You can google it or ask for support on StackOverflow.
