### ISSUE TITLE
empty generator assertion

### ISSUE THREAD

**Issue by olsonpm** [yeoman/generator#761]
I feel there is a valid use-case for generators which exist only as a composition of other generators.  The line found here:

https://github.com/yeoman/generator/blob/master/lib/base.js#L378

doesn't allow for that.  I am getting around it right now by having an empty method, but I was hoping to hear why that use-case may not be valid before sending the PR.

**Comment by SBoudrias** [comment]
Do you have the code of an example generator?

**Comment by olsonpm** [comment]
I'm currently building them.  I haven't uploaded them to github yet, so [here's a gist](https://gist.github.com/olsonpm/749ed04e08e92af025ff)

I'm not sure the gist itself will make too much sense.  The idea is just that a parent generator is composed of a bunch of smaller ones.  I may not want angular in every project, and in the projects that I don't want angular, I also don't want to be asked whether or not I want angular.  I would prefer my generator to only ask me about user-options for items that I know I want.

**Comment by SBoudrias** [comment]
Why not simply call composeWith() inside `initializing` method rather than overwriting the constructor. That'll be easier (no need to manually call super), and it doesn't require a hack around.

**Comment by olsonpm** [comment]
I guess I just thought it made most sense for them to be in the constructor.  You're right though, it also makes sense for them to exist in the initializing method.  Thanks much for your time, I really appreciate this library.
