### ISSUE TITLE
More flexible assert.fileContent() method

### ISSUE THREAD

**Issue by gruppjo** [yeoman/generator#763]
Hi,

I'm often finding myself testing several properties on the same files. For instance:

``` javascript
assert.fileContent([
  ['app/my-module/my-module.js', 'angular.module(\'myModule\','],
  ['app/my-module/my-module.js', '.state(\'my-module\','],
  ['app/my-module/my-module.js', 'url: \'/my-module\',']
]);
```

I'd like to see the `.fileContent(file, reg)` method definition extended so it accepts an array of Regexes or Strings as the second argument as well, thus it's possible to write:

``` javascript
assert.fileContent('app/my-module/my-module.js', [
  'angular.module(\'myModule\',',
  '.state(\'my-module\',',
  'url: \'/my-module\','
]);
```

What do you think?

**Comment by SBoudrias** [comment]
Seems like a good idea.

**Comment by eddiemonge** [comment]
Would this not work for you?
```javascript
[
  ['app/my-module/my-module.js', 'angular.module(\'myModule\','],
  ['app/my-module/my-module.js', '.state(\'my-module\','],
  ['app/my-module/my-module.js', 'url: \'/my-module\',']
].forEach(function(assertion) {
  assert.fileContent(assertion);
});
```

Not sure that does much good. The biggest reason against this I can think of is that it will make debugging that test case harder as you will have to figure out which part of the array failed.

**Comment by SBoudrias** [comment]
@eddiemonge have a valid point. But I guess we already jump the fence on this subject by allowing assertions on array; as so I don't see any strong reason against it.

**Comment by arthurvr** [comment]
> But I guess we already jump the fence on this subject by allowing assertions on array; as so I don't see any strong reason against it.

:+1: 

-

Shouldn't this move to the `yeoman-assert` repo by the way?

**Comment by addyosmani** [comment]
I agree with @arthurvr that this one might make more sense over on the assert repo.
