### ISSUE TITLE
this.fs.commit

### ISSUE THREAD

**Issue by olsonpm** [yeoman/generator#764]
So the documentation points any details from this.fs over to the mem-fs-editor.  Over in mem-fs-editor docs, it shows that to complete a file write you use the method fs.commit, hence that's what I did in my generator.  I noticed files were being overwritten without conflict checking, and realized this was the reason and that the generator must call commit internally.

Is there a reason to keep fs.commit open via the API?  Given yeoman's stance on being careful with overwrites, I would assume this method would be taken out.

**Comment by SBoudrias** [comment]
The generator uses commit internally, and it is a method making sense for a module. I see your point this might be confusing, but I don't think the suggested solution make sense.

**Comment by olsonpm** [comment]
Understood.  I'll close this and if you decide any work should be done regarding this item just let me know what you think makes sense and I'll send a PR.

**Comment by SBoudrias** [comment]
If you feel documentation could be clearer, please send a fix :)

**Comment by olsonpm** [comment]
Will do
