### ISSUE TITLE
[Towards 1.0] Handling deprecation

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#766]
## The issue

We've been pretty careful in every `yeoman-generator` release to stay as backward compatible as possible.

This mean through the months (even years now), legacy features have build up in our code core. I think it would be irresponsible from us to remove all of these features in one go with a 1.0.0 release. There would be a lot of deprecation all at once, and it might discourage users from upgrading their generators (ugh ugh python 3).

Considering this, I'm wondering what would be the most efficient way to slowly start deprecating features and help generator authors upgrade to latest versions?
## Proposed solution

Would it make sense to start slowly pushing minor version updates (as we're pre 1.0) where we start deprecating legacy features. We could remove one legacy feature per release, maybe at a pace of 1 release every 2 weeks.

The issue with this solution is that bug fixes happening on releases past 0.18 will be harder to integrate into generators as upgrading yeoman-generator might require code changes. Is this really an issue though? We haven't receive any serious bug report since the last 0.18 patch release.
## Deprecation list
- `file-utils` contexts (`this.src`, `this.dest`)
- `wiring` mixin
- `invoke` and `hookFor`
- `actions/actions` mixin (this is a major part though, we should probably just façade the less magical `mem-fs-editor` raw interface and remove any template handling weirdness from the file related methods)
- `NamedBase` constructor (it's so simple we could keep it, but frankly it's a bit useless IMO)
- `actions/string` mixin
- `this._`
- `actions/file` mixin
- a bunch of assertions and test methods (most of them have logged deprecation warning for a while, we'd be safe to remove them)

Let me know if you feel anything is missing here!

I'm not sure if we should add remote and fetch utilities to this list? Is there any task they solve that cannot be accomplished using npm?
## Please leave feedback

I'd really like to hear the opinion of maintainers of some major generators (ng-fullstack, mean, java-hipster, etc) who're not part of the core yeoman team.

Thanks for reading up to here!

**Comment by sindresorhus** [comment]
> Would it make sense to start slowly pushing minor version updates (as we're pre 1.0) where we start deprecating legacy features. We could remove one legacy feature per release, maybe at a pace of 1 release every 2 weeks.

I think that makes sense as long as we're transparent about it and do blog posts about how to migrate.

> Is there any task they solve that cannot be accomplished using npm?

Nope. We have way too much cruft in the API that could just be require'able modules.

> I'd really like to hear the opinion of maintainers of some major generators (ng-fullstack, mean, java-hipster, etc) who're not part of the core yeoman team.

@SBoudrias Can you mention the relevant people?

-

Sidenote: The result of this discussion should be put into a blog post on yeoman.io.

**Comment by SBoudrias** [comment]
cc'ing people this might interest @DaftMonk @jdubois @jmirc @LeovR @jrcryer @Swiip @zckrs @diegonetto @wesleytodd @robwierzbowski @seratch @Snugug @mrichard

Oh man, starting to feel like I'm a spam bot - so sorry!

**Comment by jdubois** [comment]
Thanks @SBoudrias !
Of course you need to deprecate stuff, no problem with that!
However, I must admit I have no idea which APIs we use, and where... In Java that would be easy to spot, but in JavaScript I'm lost (does JavaScript suck, or do I suck at JavaScript??). Maybe you could add some logging on top of each method that will be deprecated -> something like "warning, this is a deprecated method", so that when we run the generator we see straight away if there are some issues?

**Comment by sindresorhus** [comment]
@jdubois Yes, that's a good idea, we'll do that whenever possible.

**Comment by zckrs** [comment]
Thanks for mention.
No problem with deprecate :smiley:
Totally agree for a warning log before to remove a method.

Your "Deprecation list" is complete ? should evolve ?

Anyway we stand ready to receive releases.

**Comment by Swiip** [comment]
I remember the switch from the generator 0.17 to 0.18, it was not transparent (something about the paths in the new file system helper). As it's our main dependency I don't consider being able to change the version without worrying a bit about the impacts.

So, I don't mind if there is a lot of deprecations in a new version, especially if there is some sort of documentations helping the migration, even more if it's a major version. I would just plan a task of migration. In fact, I even prefer a big cleanup of the API better than having to fix things every two weeks.

Also, like @jdubois, whenever it's possible, I like the idea of a warning log.

To be honest, I prepare myself for the release of Gulp 4 which will be a lot harder to deal with, I think :)

**Comment by wesleytodd** [comment]
Thanks for looping me in.  I am also going to ping a contributor who has been adding a lot to the wordpress generator @toddses.

A ton of issues that get filed on my generator are for warning messages that beginning users don't understand.  So having depreciation messages in the main-line branch is going to generate a bunch of pointless GitHub issues.  Maybe we could start with a `--development-warnings` flag or something to enable them.  At least for the current major version branch.

Secondly, I agree with @jdubois that I am not entirely sure which of that list we are using.  I have recently found the documentation to be difficult to follow.  JSDoc makes some seriously weird structure on their generated output.  We tried at my company to wrangle that beast and have mostly given up.  So I understand the plight, but still cannot determine for sure which we are using.

Thirdly, and related to the "secondly", documentation on the migration would be greatly helpful.  When @toddses updated the generator to 0.18 I really had no insights into the change.  Just like @Swiip said.  So it would really be helpful to have a clear explanation as to what features are deprecated and what should take their place.  Preferably with examples :)

**Comment by eddiemonge** [comment]
Some of us from core could make ourselves available from time to time to help with the migrations as well to ease the transition.

**Comment by SBoudrias** [comment]
First deprecation release https://github.com/yeoman/generator/releases/tag/v0.19.0

All deprecated methods will log a message to the console and should work just as before. (Exception: `this.src` and `this.dest` won't work, but will log a warning to the console).

**Comment by addyosmani** [comment]
Thanks for driving the move towards trimming and cleaning up the codebase, Simon. I agree with Sindre that in general this all sounds fine as long as we're being transparent about what is being deprecated and this indeed seems to be the case with the first deprecation release. 

Perhaps my only suggestion here is it might be useful to publish a deprecation roadmap so it's clear to authors when features may no longer be available to them. As with any API deprecations, providing guidance around the replacement "way to do things" is probably also appreciated by authors.

**Comment by zenorocha** [comment]
Just noticed that `withPrompt` has been removed in favor of `withPrompts`. I think these kind of test helpers should also be listed here since I had to look over the source code to find this change.

/cc @SBoudrias

**Comment by jdubois** [comment]
@SBoudrias 

I have an error (not just deprecation warning, it fails) with:

(!) #_ is deprecated. Require your own version of Lodash or underscore.string

-> I'm doing a "require" on underscore.string and it doesn't work, but I'm really a beginner on this... Do you have any working example? I tried to copy on generator-angular, but I'm not sure it uses the new API.

**Comment by zenorocha** [comment]
@jdubois remember to remove `this` once you import your own version of lodash, which means `_.` instead of `this._`.

**Comment by SBoudrias** [comment]
@jdubois @zenorocha have the first part. Also FWIW, lodash now provide String utilities, so `underscore.string` might not even be necessary for your use case.

A tricky thing about `_` I found while updating one of our core generator is that it is often abused in templates files. `this.template` make the generator instance the context of each templates, which make it very hard to fix.

IMO the solution is to stay away from `this.template` (or `this.copy` if used for templating) and move to the [new file system helpers](http://yeoman.io/blog/release-0.18.html): `this.fs.copyTpl()`. With this method you manually pass the data you want in a template which make it very easy to search and debug.

If you want an example, check the [update commit made to generator-generator](https://github.com/yeoman/generator-generator/commit/f2a2aab4d4fd38b959918fa8ec5cdd3103f01f2c)

**Comment by jdubois** [comment]
Thanks @zenorocha but I'm already using ```_.```
@SBoudrias I am indeed abusing this, and it's awful to debug. However I have so many templates, this is going to be hard to migrate!!!

**Comment by jdubois** [comment]
@SBoudrias OK this is working, but now I have to pass all parameters as arguments, and not use ```_.``` inside my template, but I have something like 300 templates... Can't we have a way to make it work as before?

**Comment by SBoudrias** [comment]
@jdubois yes, you can manually do `this._ = _`  in your constructor.

**Comment by sondr3** [comment]
Just throwing my two cents into the fold here, would it be possible to have an example generator (maybe even generator-generator) where with each release you update it to follow best practices and remove/update deprecated features and such so you can actually look at the changes and such. This is mostly how I've been able to piece together how things work and it would be neat to have a up-to-date simple place to look for how to do things properly.

**Comment by SBoudrias** [comment]
Hey @sondr3, we actually did update generator-generator to 0.19. You can see the update diff here: https://github.com/yeoman/generator-generator/commit/f2a2aab4d4fd38b959918fa8ec5cdd3103f01f2c

It is not our most complex generator, so it might not cover every case, but it's a place to start. We're in the process of updating generator-node currently.

**Comment by sondr3** [comment]
Whelp, I thought I looked hard enough, thanks! I'll take a look.

**Comment by jdubois** [comment]
I got it working, using yeoman-generator 0.20.1

Excepted from the annoying issue I mentioned earlier, no problem at all. Not even one deprecation warning!! @SBoudrias did you deprecate a lot of things? Or is it me just using a small part of the generator?

**Comment by jdubois** [comment]
Sorry, I see all the warnings now!!! Hell, lots of work!

**Comment by SBoudrias** [comment]
@jdubois can you explain why you couldn't see the warnings? It might be helpful if other people also run into this issue.

**Comment by jdubois** [comment]
@SBoudrias it's just that I forgot to do a "npm link" to fetch the new dependencies. Usually I don't touch them, so my code is always at the right version without doing it.

**Comment by jdubois** [comment]
@SBoudrias I still have one issue left, with a method that is not behaving like it used to do. I opened up a [Stackoverflow question](http://stackoverflow.com/questions/30592237/preparing-for-yeoman-1-0-this-installdependencies-not-working-anymore) about it, if you can help me it would be greatly appreciated, as I'm really stucked.

**Comment by SBoudrias** [comment]
Hey everyone, today I published the beta `v1.0.0-rc1` that'll hopefully become our first v1.

We've been documenting the changes in a [blog post](https://github.com/yeoman/yeoman.github.io/blob/a87b3452377b1b232145f910d6a945804bf84d2c/app/_posts/blog/2016-12-03-hello-generator-1.0.md) and [updated documentation](https://github.com/yeoman/yeoman.github.io/pull/700/files). We'll publish these resource on yeoman.io as soon as we have a stable 1.0

Let us know what you think and how 1.0 works for you!

**Comment by SBoudrias** [comment]
Full 1.0 is out today. Open issues if you ran into any problems updating.
