### ISSUE TITLE
Writing generators in ES2015

### ISSUE THREAD

**Issue by jamesallardice** [yeoman/generator#767]
It could be nice to have the ability to write generators in ES2015 `class` syntax. For example:

```js
import { Base } from 'yeoman-generator';

export default class MyGenerator extends Base {
  constructor( ...args ) {
    super(...args);
  }
  someMethod() {
    console.log('Do something');
  }
}
```

This is not currently possible because methods defined in the above way are non-enumerable properties of the constructor prototype and the `Base` generator will [only find](https://github.com/yeoman/generator/blob/v0.18.9/lib/base.js#L377) those that are enumerable:

```js
var methods = Object.keys(Object.getPrototypeOf(this));
```

This appears like it could be easily fixed by using `Object.getOwnPropertyNames` instead of `Object.keys` but I'm unsure if it's something that can or should change as I guess it could affect any existing generators that rely upon non-enumerable properties on the object passed to `Base.extend` for example.

**Comment by SBoudrias** [comment]
I don't think this will cause any major break. Feel free to send a PR with this fix.
