### ISSUE TITLE
setting generator.conflicter.force from within generator doesn't work

### ISSUE THREAD

**Issue by boopathi** [yeoman/generator#768]
Im setting `generator.conflicter.force = true`, and it doesn't work. It shows me the conflict and requires me to input. While `yo mygen --force` passes the options.force to generator.conflicter.force and works.

Is this the design decision for 0.18 ? I migrated from 0.17 to 0.18, and how do I use `--force` programmatically within the generator/sub-generator without requiring the user to pass the param ?

**Comment by boopathi** [comment]
generator.write was the issue. Changed it to generator.writeFileFromString and it worked. The new Conflicter doesn't care about appending changes to file. Nice!. So I don't have to `--force` write.

**Comment by mraible** [comment]
I'm having a similar issue. Setting `this.conflicter.force = true` works when I do it in my Yeoman generator, but it makes it so my generator doesn't complete. I tried adding `this.conflicter.force = false` at the end, and wrapping the whole thing in a promise. Neither seems to work.

**Comment by mraible** [comment]
I ended up using `process.exit(0)` as a workaround to complete the generator.
