### ISSUE TITLE
How to run a child process after all files generated and wait it completes?

### ISSUE THREAD

**Issue by evil-shrike** [yeoman/generator#770]
Hi.
I known that SO is more suitable for asking questions so please excuse me.
But I'm struggling with Yeoman for several hours and encountered an issue which I'm sure should not take some much time to resolve. I read all docs, api docs, source code but still cannot understand how to do a simplest thing:
How to run an async command  (via spawnCommand) after all files generated and make Yeoman to wait till the command completes?

Full question on SO: http://stackoverflow.com/questions/28838386/yeoman-generator-how-to-run-async-command-after-all-files-copied

**Comment by SBoudrias** [comment]
Answered to you over SO.
