### ISSUE TITLE
mockPrompt with invalid data passes validation

### ISSUE THREAD

**Issue by brettm523** [yeoman/generator#775]
mockPrompt seems to ignore validation. How can I test if validation is working?

**Comment by SBoudrias** [comment]
That is correct, mockPrompt is a mock. It only passes the data, bypassing Inquirer.

If you want to test your validations functions are working, just call them directly in a unit test.

**Comment by brettm523** [comment]
How would I do that given that the prompt requires user interaction?

**Comment by brettm523** [comment]
Ah, I suppose I could refactor my validations into a separate validator object instead of including them as anonymous functions in the prompt declaration. Could then unit test those separately. That's a cleaner approach anyway. Thx!

**Comment by SBoudrias** [comment]
Yeah, that's what I meant :) Good luck!

**Comment by mfdeveloper** [comment]
Hello guys @bmayen and @SBoudrias. Can you post a code example with this test approach? I'm using the code below:

```javascript

//generators/app/index.js file
 module.exports.Filters = {
  rawValue: '',
  addonName: function (value) {
    this.rawValue = value;

    //Do a filter value here using lodash
    var str = _.camelCase(value);
    return Promise.resolve(str);
  }
};

/*tests/app.js file
*
* ...prompt mocks, arguments here...
*/
it('filter addon name', function () {
    //Loads the generator exports
    var generator = require(path.join(__dirname, '../generators/app'));
    generator.Filters.addonName('my-value').then(function (value) {

      assert.textEqual(value, 'myValue');
    });
  });

```

This is work for me, but, I'm not sure if this is a good approach. Before, I tried create a `filter()` generator method, but I couldn't access him in my specs to call separately.

What do you think about this implementation?

**Comment by SBoudrias** [comment]
@mfdeveloper lgtm
