### ISSUE TITLE
No documentation about the process argument

### ISSUE THREAD

**Issue by totty90** [yeoman/generator#776]
In [actions](http://yeoman.github.io/generator/actions.html), let's take "directory(source, destination, process)". This is the docs about the "process" argument: "process	function	". Yes, only a function:
 - Is called with what args? body, source, destination, data.encoding
 - Is expected to return something? return the body

I've found the answers here: http://yeoman.github.io/generator/actions.js.html#line57

**Comment by SBoudrias** [comment]
PR is welcomed :)

Just need to update the function comment and it'll be reflected in our API doc.
