### ISSUE TITLE
run.withLocalConfig does not work

### ISSUE THREAD

**Issue by johannesjo** [yeoman/generator#784]
I know it might be to early, but I really would want to use this feature to work :) 

The .yo-rc.json file gets created correctly, but the config is never available inside the generators. `this.config.getAll()` returns undefined inside the generator file for the test, while normally working like a charm. I'm using v0.19.1.

**Comment by SBoudrias** [comment]
Was it working fine for you under 0.18?

**Comment by johannesjo** [comment]
Not sure. Haven't tested it back then. My code-base is hugely refactored since then, so it makes not too much sense to go back to test it there.

**Comment by SBoudrias** [comment]
Mind linking to your repository?

**Comment by johannesjo** [comment]
Sure: https://github.com/johannesjo/generator-modular-angular

**Comment by johannesjo** [comment]
I'll push the latest version so you can check it out, one sec.

**Comment by johannesjo** [comment]
I created a branch with the latest files: https://github.com/johannesjo/generator-modular-angular/tree/local-config-issues

**Comment by SBoudrias** [comment]
I believe the issue is you're reading file in the constructor. Try moving them to the initializing step.

**Comment by johannesjo** [comment]
You mean in the test itself, or in the actual generator-file?

**Comment by johannesjo** [comment]
Ok this seemed to fix the issue. If I may ask a question: How would you go about always executing a function for all sub-generators? When inheriting the only method which is called, is the constructor function.

**Comment by johannesjo** [comment]
Sorry for posting so much. Seems like I got a lot of things wrong about how yeoman works. Actually all the functions get executed.. 

Thanks for helping me out. Keep up the good work =)
