### ISSUE TITLE
Deprecated method is breaking the subgenerator src() and dest() are deprecated

### ISSUE THREAD

**Issue by xtianus79** [yeoman/generator#785]
Here is the console error:

     PS C:\Projects\Foundation5Application> yo aspnet-xtianus:PackageJson
     You called the aspnet subgenerator with the arg package.json
     (!) #src() and #dest() are deprecated. Please read the documentation to learn about
     the new ways of handling files. http://yeoman.io/authoring/file-system.html
     events.js:85
      throw er; // Unhandled 'error' event

Here is the subgenerator code:

    'use strict';
    var util = require('util');
    var yeoman = require('yeoman-generator');
    var ScriptBase = require('../script-base-basic.js');

    var Generator = module.exports = function Generator() {
	ScriptBase.apply(this, arguments);
    }

    util.inherits(Generator, ScriptBase);

    Generator.prototype.createItem = function(){
	this.generateStandardFile('package.json', 'package.json');
    };

---------

    'use strict';
    var util = require('util');
    var path = require('path');
    var yeoman = require('yeoman-generator');
    var chalk = require('chalk');

    var Generator = module.exports = function Generator() {
      yeoman.generators.Base.apply(this, arguments);

      var sourceRoot = '/templates/';
      this.sourceRoot(path.join(__dirname, sourceRoot));
    }; 

    util.inherits(Generator, yeoman.generators.Base);

    Generator.prototype.generateStandardFile = function(sourceFile, targetFile){
     this.log('You called the aspnet subgenerator with the arg ' + sourceFile);

      this.src.copy(sourceFile, targetFile);

     this.log(targetFile + ' created.')
    }

Any thoughts how to fix these errors?  I have tried the new methods without any luck.

**Comment by SBoudrias** [comment]
Hi, like the log said. `this.src` and `this.dest` are deprecated. So you need to update them. Like the log said, please read http://yeoman.io/authoring/file-system.html to learn about the up to date file utilities.

**Comment by xtianus79** [comment]
I thought this wasn't supposed to break anything?

**Comment by SBoudrias** [comment]
Some stuff are breaking.

**Comment by xtianus79** [comment]
in the context of the code that is written could you give some better documentation on what would fix that exactly?  I don't mind updating things but I have no clue what is going on in total context of the changes.
