### ISSUE TITLE
Unclear mkdir deprecation warning

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#786]
Rel: https://github.com/yeoman/generator-generator/issues/107

Let's add a link to the npm module in the warning.

**Comment by addyosmani** [comment]
:+1:

**Comment by arthurvr** [comment]
@SBoudrias Didn't https://github.com/yeoman/generator/commit/4602d81943a618d0422bd07a15b097eb4b2fde63 fix this?

**Comment by SBoudrias** [comment]
Oh, it did. Let's close :D
