### ISSUE TITLE
alias for generator name

### ISSUE THREAD

**Issue by yonatanmn** [yeoman/generator#788]
My generator name is quite long, is there a way for making 
`yo tooLongName appName` be less tedious? 
If so - how yeoman prevent collisions with other installed generators with the same name?

BTW, I believe the workaroung proposed [here](https://github.com/yeoman/generator/issues/663) will not be relevant for the main generator

**Comment by SBoudrias** [comment]
A generator name is the name of the npm packages. That's just the way it works, you can name your generator a shorter name if that make more sense for you.

**Comment by WooodHead** [comment]
I have the same problem, try to add bash alias `alias yt='yo tooLongName ` to ~/.bash_profile
