### ISSUE TITLE
Is it possible to set copyTpl to have multiple options so that this.template can be included

### ISSUE THREAD

**Issue by xtianus79** [yeoman/generator#789]
So this directive works great: 

    this.fs.copyTpl(
      this.templatePath('index.html'),
      this.destinationPath('public/index.html'),
      { title: 'Templating with Yeoman' }
    );

However, I would like to include the this.template method work too along with the option { title: 'templating with Yeoman' } 

So far I can only have one or the other actually function.

**Comment by SBoudrias** [comment]
Your request is not clear...

**Comment by xtianus79** [comment]
if I take the above code and replace the option { title: 'templating... '} with - this.template - and everything in the file will generate from the prompts binded to this.template.  However, to do the method below... lets say title: 'message here' I may want to set up a condition that uses a variable set from this.template.  I can't do that in the index.html file because it hasn't been set.  I need somehow to also use this.template along with the option as described above.  

Yes I can run multiple keys but I cant set overall this.template to allow for conditions to be set.

**Comment by SBoudrias** [comment]
Hey, I don't mean to be rude, but... Honestly learn to program and learn JavaScript.

I'm reading all the comments you posted in the last two days and try to be helpful. But I can't tell if you're just trolling me with non-sense or are serious.

Now, please stop opening issues everywhere and take some time to work on your programming knowledge.

**Comment by xtianus79** [comment]
you are beyond rude. did you not understand what it was that I was asking?  it is a serious question and I wouldn't of taken the time to ask it if it wasn't serious. trolling? what are you 12?

**Comment by xtianus79** [comment]
if the answer is... It can't be done then just say it can't be done or that is not a parameter that is set to give that functionality.  I have taken the time to ask the lodash people as well and they stated it is the way the template is handling the escaping... 

>> Looks like this isn't a lodash issue as I verified the newlines do work. Look for whatever is handling your template as it's probably performing the extra escaping.
