### ISSUE TITLE
not trolling just trying to figure out these breaking changes... and new methods from deprecated ones. 

### ISSUE THREAD

**Issue by xtianus79** [yeoman/generator#790]
I don't appreciate being called a troll for trying to use this product and fix changes that ended up breaking generators. 

recently yeoman did a breaking deprecating change via .19... and that's ok as I have tried to learn and revisit some methods the correct way to fix them.  So, I went to the github issues page and opened a few issues.  Now I understand the importance to close and issue quickly and act as if there was never an issue in the first place... 

This is illustrated here via this issue. https://github.com/yeoman/generator/issues/787

Yes I was having a problem but pinpointing it sometimes is difficult. ok fine.  

With that said I presented a problem with the new methodology behind the copyTpl directive over using the this.template method.  

I simply stated that using that method didn't allow for blanket statement changes to occur which is not useful for conditional statements.  

this was the example here. 

http://yeoman.io/authoring/file-system.html

Now this is supposedly the new way of doing things as opposed to legacy methods such as copy and template... i.e. the deprecating changes that broke my generator in question.  

The main point I was making and asking if there was a solution to is that when you set the option i.e. {title: 'your message here' } that is great for semantics but if there is a conditional statement elsewhere in the index.html file it won't be met... something like the blanket this.template would have covered it if the condition was met previously.  

hence is there a way to fix this or get around this?  that is all that I was asking... sorry that was such a bother to anyone. 
<html>
  <head>
    <title><%= title %></title>
  </head>
</html>
generators.Base.extend({
  writing: function () {
    this.fs.copyTpl(
      this.templatePath('index.html'),
      this.destinationPath('public/index.html'),
      { title: 'Templating with Yeoman' }
    );
  }
});
<html>
  <head>
    <title>Templating with Yeoman</title>
  </head>
</html>

**Comment by SBoudrias** [comment]
We use Lodash template syntax. Everything should work fine.

If you're updating my guess is that you use `_` inside your templates. There's no `this._` anymore, so just pass the value in the template context object.

Now, please use StackOverflow for any further questions. Github is used to report bug, not support.

**Comment by xtianus79** [comment]
ok

**Comment by addyosmani** [comment]
@xtianus79 Thanks for approaching us with your questions about deprecated features and `copyTpl`. I wanted to personally apologise for the experience you've had on the tracker. As Simon mentioned, StackOverflow tends to be our preferred channel for support questions as the whole community can collaborate on input there.

That said, everyone on the team care a lot about making sure you're able to navigate the waters around breaking releases as easily as possible. Given the volume of tickets we receive, the core team try their best to address them quickly but in this case we could definitely have communicated help to you more clearly. 

We'll do our best to do a better job of this in the future.

**Comment by xtianus79** [comment]
@addyosmani & @SBoudrias So I took one part of my question to stack and it was answered so I will make a better utility out of that resource.  Thanks for the advice.  

Would it be possible however to get an answer to the question above.  I think this is specific to Yeoman but I may be wrong. 

I can use { title: 'this message here } or I can use this.template ... but I can't use both or haven't figured out how to.  Is it possible to utilize both?  There is a very specific reason why I want to do this.
