### ISSUE TITLE
generator not listed

### ISSUE THREAD

**Issue by lukemadera** [yeoman/generator#793]
My MEAN seed generator was listed and now it's no longer listed.
http://yeoman.io/generators/
https://github.com/notorii/generator-mean-seed

I confirmed `package.json` has the "yeoman-generator" keyword and the repo has a description.

How can I ensure the generator gets / stays listed?

Thanks!

**Comment by SBoudrias** [comment]
I'm not sure this line is correct https://github.com/notorii/generator-mean-seed/blob/master/package.json#L38

**Comment by SBoudrias** [comment]
(Also this unrelated comment, but I think it's time for [an update](https://github.com/notorii/generator-mean-seed/blob/master/package.json#L44) :fast_forward:)

**Comment by hemanth** [comment]
But `generator-mean-seed` is available at [skimdb](https://skimdb.npmjs.com/registry/_design/app/_view/byKeyword?startkey=[%22yeoman-generator%22]&endkey=[%22yeoman-generator%22,{}]&group_level=3) with `yeoman-generator` as the keyword.

**Comment by lukemadera** [comment]
Thanks @SBoudrias - updated. How long does it take for the community generators search to pull in updates?

**Comment by SBoudrias** [comment]
I'm not sure about the time it takes... Pretty sure it's instantaneous as we don't cache results ourselves. (that's a very dummy heroku free app)

Anyway, I can see you generator now, so I'll close this one.

**Comment by lukemadera** [comment]
Great, thanks for the speedy reply @SBoudrias !
