### ISSUE TITLE
fetch.extract generates empty tarball due to .use()

### ISSUE THREAD

**Issue by Yahosh** [yeoman/generator#794]
While attempting to use the extract method, I found that the script would generate an empty (0 bytes) tarball file and would not extract it. The issue seems to be linked to line 63 in fetch.js:

```.use(function (res) {
      res.on('data', function (data) {
        log.write('.');
      });
    });```

By commenting that block out the method works as expected, downloading and unzipping the provided tarball. I'm guessing that the data needs to be streamed to files when using the "use" method of the download module. As is, it seems the data is being intercepted and not getting streamed to files.

**Comment by Toddses** [comment]
I wonder if the way `data` is emitted has changed in one of the plugins. If you do this

```
.use(function (res) {
        log.write('.');
    });
```

it works fine.

**Comment by Yahosh** [comment]
Interestingly, when I try that my console shows ".." for each extract, which would indicate it's being called twice.

Currently I'm overwriting the extract method with my own that removes the .use() call and it works fine. Ugly, but I don't want to rely on updating the fetch.js module after npm installing.

**Comment by SBoudrias** [comment]
cc @kevva

**Comment by Toddses** [comment]
Okay I think I've nailed down a solution. Possibly something has changed with the way streams work in node. But referencing https://nodejs.org/api/stream.html#stream_event_data 

```
Attaching a data event listener to a stream that has not been explicitly paused will switch the stream into flowing mode. Data will then be passed as soon as it is available.
```

Clearly we don't want to turn the stream into flowing mode. So replacing the line `res.on('data' ...` with `res.on('readable' ....` solved the issue, and maintained the whole `.` output as was originally designed.

**Comment by SBoudrias** [comment]
@Toddses Can you send a fix PR? (with unit test)

**Comment by kevva** [comment]
Yeah, it changed in streams2 but it's weird that nobody has reported this before.

**Comment by Toddses** [comment]
Well, I'd like to. Honestly, I'm not sure how I would modify the existing unit test. The `extract` function doesn't return an error in these cases, and the test as is passes.

**Comment by Yahosh** [comment]
@Toddses Ah, yeah that's it, great find. I would send a PR but I'm in the same boat, not sure how to write a failing test. In any case, good to know about the stream behavior. Thanks for digging.
