### ISSUE TITLE
I am trying to use a while loop with inquire.js prompt with my yeoman generator results in node emitter error

### ISSUE THREAD

**Issue by xtianus79** [yeoman/generator#797]
perhaps this should be in the inquire.js issues board but the error is occuring while running my yeoman generator.  

this is the loo (I am trying to repeat the question):

    askForTest1: function () {
        if (this.type == 'foundation5') {
        	do {
            var cb = this.async();
            var prompts = {
                type: 'input',
                name: 'test1',
                message: chalk.yellow('  What is your favorite movie'),
                default: 'Star Wars!'
            };

            this.prompt(prompts, function (props) {
                this.templatedata.test1 = props.test1;

                cb();
            }.bind(this));
        	} while(this.templatedata.test1 != "");
        }
    },

this is the output after:

    (node) warning: possible EventEmitter memory leak detected. 11 keypress listeners added. Use       emitter.setMaxListeners() t
  o increase limit.
   Trace
       at ReadStream.addListener (events.js:179:15)
    at ReadStream.Readable.on (_stream_readable.js:671:33)
    at new Interface (readline.js:131:11)
    at Object.exports.createInterface (readline.js:39:10)
    at Object.Interface.createInterface                 (C:\Users\username\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\no

**Comment by SBoudrias** [comment]
Hey, you're triggering multiple async actions inside a while loop (which is synchronous).

I'm not sure what your goal is, but that's not a bug, that's an issue in your code.

Please refer to StackOverflow if you need further help to understand your issue here.

**Comment by xtianus79** [comment]
thanks that is what I was looking for.
