### ISSUE TITLE
npmInstall does nothing

### ISSUE THREAD

**Issue by totty90** [yeoman/generator#798]
I have this sub generator:

    'use strict';
    var yeoman = require('yeoman-generator');

    module.exports = yeoman.generators.Base.extend({
      initializing: function () {
      },

      installing: function(){
        this.npmInstall(['react#0.13.1'], { 'save': true });
        this.npmInstall(['fluxmax#0.13.0'], { 'save': true });
        this.npmInstall(['smart-css#0.0.2'], { 'save': true });
        this.installDependencies()
      }
    });

Which does nothing. I would expect to run the `npm install` commands.

**Comment by kevva** [comment]
Use `@` instead of `#`.

**Comment by totty90** [comment]
Tried both doesn't work.

**Comment by totty90** [comment]
Please reopen the issue.

**Comment by SBoudrias** [comment]
Which version of yeoman?

**Comment by totty90** [comment]
last version

**Comment by eddiemonge** [comment]
which is what as the version can change over time

**Comment by totty90** [comment]
The  version at the time of submission

**Comment by SBoudrias** [comment]
Does it work if you define it this way: `this.npmInstall(['react@0.13.1'], { 'save': true });`. I don't think npm support `#` syntax.

**Comment by kevva** [comment]
@SBoudrias

> Use @ instead of #.

**Comment by totty90** [comment]
As I've said it didn't worked...

**Comment by SBoudrias** [comment]
Just tested that out and it's working fine.

Make sure you're not passing the `--skip-install` flag (that's default in tests). And make sure you're really using the latest version.

Closing this issue as non reproduce-able.
