### ISSUE TITLE
is it possible to create some files for the testing environment?

### ISSUE THREAD

**Issue by markusfalk** [yeoman/generator#799]
I have a subgenerator that reads the package json to get the name. When testing this sub-generator it always fails on reading this file.

In the docs I read that I can use inDir() to setup the environment but it seems this is all cleared out before the generator is run. 
```javascript
before(function (done) {

  helpers.run(path.join( __dirname, '../addcomponent'))
  .inDir(path.join( __dirname, './tmp'), function(dir) {

    fs.copyTpl(
      path.join(__dirname, '../app/templates/_package.json'),
      dir + 'package.json',
      { ProjectName: 'foo' }
    );

    var test = fs.readJSON(dir + 'package.json');
    console.log('test: ' + test); // returns the object
    console.log('test.name: ' + test.name); // returns the correct name

  })
  .withArguments(['foo'])
  .withPrompts(prompts)
  .withOptions(options)
  .on('end', done);

});
```

In the generator:
```javascript
init: function() {
  this.pkg = this.fs.readJSON('package.json');
  console.log('this.pkg: ' + this.pkg); // returns undefined

  this.on('end', function () { ... });
}

```

The test run: https://travis-ci.org/markusfalk/generator-kickstart/builds/58907790

The question can also be found here: http://stackoverflow.com/questions/29697724/how-to-setup-yeoman-test-for-subgenerator-that-reads-package-json

Thanks :)

**Comment by SBoudrias** [comment]
Answered to you on stackoverflow.

I'll leave this issue open as multiple people have been asking about this and we probably could improve the ordering to prevent reads from the constructor from failing.

**Comment by addyosmani** [comment]
It looks like Simon answered the follow-up clarifications you made in the SO thread. Is there anything else outstanding here? We covered the newer file system utils over in http://yeoman.io/blog/release-0.18.html.
