### ISSUE TITLE
Yeoman cache breaks when updating from 0.18.x to 0.19.x

### ISSUE THREAD

**Issue by wesleytodd** [yeoman/generator#800]
It looks like the problem is that there was a change in how extracting works, and the new code is not backward compatible.  When I upgrade to current master for `yeoman-generator` the file's are not extracted from the tarball correctly.  I have not been super thorough in my examination and frankly don't have time to be right now (yeah OSS!!), so I may be wrong :)

It seems like we should expire/clear the cache on upgrades.  Is this feasible or even a good idea?  Anyway, just wanted to post this to try and get to the bottom of the problem.

**Comment by SBoudrias** [comment]
Can you test latest master? A fix for #794 just landed

**Comment by wesleytodd** [comment]
Latest master is what I tested.  @Toddses, the author of that patch, is a a core dev on `generator-wordpress`, which is the generator I was talking about.  

Really what it looks like is the fix works, but something else broke backwards compat before that fix was made.

**Comment by SBoudrias** [comment]
> Really what it looks like is the fix works, but something else broke backwards compat before that fix was made.

So it is working now?

**Comment by wesleytodd** [comment]
Yes, the fix works, but is not backwards compatible.  So anyone with cache from before the fix will continue to see the error until they clear their cache.

**Comment by SBoudrias** [comment]
That's unfortunate, but that seems reasonable to me.

I'll close this issue.

**Comment by SBoudrias** [comment]
Also, FWIW, you might want to use npm to fetch the wordpress repo rather than `this.extract`.

**Comment by wesleytodd** [comment]
Technically it should require a major version bump right?  I mean I am on board with the changes, but it was unexpected because it broke backwards compat.

For the extract thing, is this not the recommended way to get a github repo?  https://github.com/wesleytodd/YeoPress/blob/develop/app/index.js#L215

Has that changed?  I mean we just did find a serious issue with it on our end so we can take a look for sure.  But the docs should probably change if this is not the recommended way.

**Comment by SBoudrias** [comment]
This was a bug, not a compatibility change. As so, I don't see why it'd require a major bump.

For the recommended way, we haven't deprecated extract as I'm not sure what the best way is. But I do feel like fetching the repo using npm and copying from the node_modules folder is probably the best way. I'd like your take on this, maybe try and see how it looks/goes.

**Comment by wesleytodd** [comment]
Ok, I'm on board with that.

For the npm thing, I made an issue to track it.  As I said in the initial message, I am not capable of working on it right now, but hopefully someone can pitch in.
