### ISSUE TITLE
Unit tests update the global prompt store

### ISSUE THREAD

**Issue by MethodGrab** [yeoman/generator#803]
If you have prompts that get stored globally to `~/.yo-rc-global.json` using the `store: true` property, when you run unit tests with `generator.test.run`, the global values get updated.

Is it possible to change this behaviour? Is there an option that can be passed to `generator.test.run` that will ignore the `store: true` properties or a way for unit tests to have a separate `.yo-rc-global.json`?

**Comment by SBoudrias** [comment]
Not at the moment, I don't think anyone realize because only generators authors would be subject to this issue.
