### ISSUE TITLE
Switch underscore.template to ejs/handlebar

### ISSUE THREAD

**Issue by yangchenyun** [yeoman/generator#804]
Hi Yeoman team,
     Thanks for the work of yeoman! I've migrated some codegen tool into yeoman framework, and it is a pleasure to do so. 
     After some development in yeoman, I found the template engine (underscore.template) lacks some important feature to write a template in maintainable format while output right format target file:

- Lack of whitespace controls.   Underscore's engine is by nature string replacement, thus it lacks precise whitespace controls which you will find in modern template engine such as [jinja2](http://jinja.pocoo.org/docs/dev/templates/#whitespace-control), [handlebar](http://handlebarsjs.com/expressions.html#whitespace-control).  Missing of this feature makes it is very [hack-y](http://stackoverflow.com/questions/13169885/underscorejs-removing-unwanted-spaces-for-logic-part/13170456#13170456) to get the output right.  For a complex template, it means less maintainable source code. 
   
- Lack of raw output. Through, it is possible to configure the engine to use other keywords then "<%=", "<%" as syntax; it doesn't avoid the problem to output these syntax as raw string instead of interpreting them as source code. 

     So I suggest a switch from underscore.template to a real template engine such as ejs / handlebar. I prefer [ejs](https://www.npmjs.com/package/ejs) for its similar syntax as underscore.template. If you think it is the right way to advance for 1.0 milestone, I could work to create PR for it.

Best,

**Comment by SBoudrias** [comment]
You've describe some issues with underscore templates. Can you describe how another template engine would handle the issue you described?

**Comment by yangchenyun** [comment]
Yes, that's why I think we could switch the `this.engine` interface with a more robust template engine. As mentioned in the beginning, [ejs](https://www.npmjs.com/package/ejs) is a good candidate for syntax similarity. 

Some [hacky](https://github.com/yeoman/generator/blob/master/lib/util/engines.js#L14) has been going on in the source already to solve part of the "raw string" issue I described above.

**Comment by SBoudrias** [comment]
These methods are old and deprecated and we have no plans to continue supporting them. The new FS is using `mem-fs-editor`.

**Comment by SBoudrias** [comment]
But what I was asking is for you to explain how ejs or handlebars are technically fixing the issue you described with underscore. Because I don't see how these two template engine would fix these issues.

**Comment by yangchenyun** [comment]
I saw the issue to deprecated the `this.engine` and use the interface provided by `mem-fs-editor` directly.

I could send PR to that repo of yours as well :smiley: 

## ejs
whitespace control issue: solved by "Trim-mode ('newline slurping') with -%> ending tag"
raw text output issue: solved by "Tags<%% Outputs a literal '<%'"

## handlebar
[Whitespace control is built in to syntax](http://handlebarsjs.com/expressions.html#whitespace-control)
[The raw block is there since 2.0](https://github.com/jezell/handlebars.js/commit/494acd01366a2cdbd47ee93a5967da37abe026fa) but not documented, only available in [source](https://github.com/wycats/handlebars.js/blob/master/src/handlebars.l#L67)

## mustache

**Comment by SBoudrias** [comment]
So, if I read this correctly, ejs use basically the same syntax as underscore, so switching would be almost seamless?

**Comment by yangchenyun** [comment]
Yes, and the hack we had right now in the `this.engine` is mimic ejs's behavior to output raw string; so the transition should be transparent for users. 

But if we do patch `mem-fs-editor`, do you think this a good idea to create a configurable layer for `copyTpl`, and leave an option for user to pick the engine they want to use. 

If the goal of `mem-fs-editor` is to be used as a module for code generation or mocks of file system in testing, it might be useful to allow user to pick them own template engine in setup.

**Comment by SBoudrias** [comment]
Maybe... But I don't want to bloat the project with not very useful feature.

I think we should just switch to ejs, and revisit later if we want to make this configurable.

**Comment by SBoudrias** [comment]
Created a branch on mem-fs-editor starting this work.

I've also seen this related question today on StackOverflow. Leaving a note to update the answer while we have a good partial story. http://stackoverflow.com/questions/26832192/in-custom-yeoman-generator-include-one-template-inside-another/30065880#30065880

**Comment by yangchenyun** [comment]
Indeed! Cheers for yeoman about to have a robust template engine.

**Comment by SBoudrias** [comment]
Let's keep open for now. We'll need some update on yeoman-generator side too.

**Comment by SBoudrias** [comment]
This is done on `next` branch.

**Comment by yangchenyun** [comment]
Great, I am upgrading to use code at master head now.

**Comment by SBoudrias** [comment]
Let me know how that goes. I'll try to carve a release soon-ish.
