### ISSUE TITLE
Setting TMPDIR Environmental Variable Breaks Testing Generators

### ISSUE THREAD

**Issue by destroyerofbuilds** [yeoman/generator#808]
I'm currently looking into an issue with using `export TMPDIR="$(pwd)/.tmpDir"`, `pwd` being the root of my generator project, that is causing my generator tests to fail. The error I get is `Uncaught TypeError: Cannot read property 'defaultEncoding' of undefined`. Not very helpful, but that's because the error is really just a symptom, not the cause. The actual cause is because the generator is failing to scaffold files into the new `tmpDir` directory as part of the tests.

Assuming `generator-javascript-common` is the root of the generator project, and that the new `tmpDir` directory should be found in `generator-javascript-common/.tmpDir` (which is actually created, and is populated with lots of folders with names consisting of numbers and letters), I would assume that the `destinationPath` would match those folders. However, that's not the case. Something like `this.destinationPath('.gitattributes')` actually outputs `generator-javascript-common/.gitattributes`.

`console.log(os.tmpdir())` outputs `generator-javascript-common/.tmpDir`, which is expected

Looks like `destinationRoot` just defers to `process.cwd()`, which would explain why it thinks the destination root is the root of the generator project. So the question becomes, why does the test runner not cwd into the `tmpDir` directories.

`inTmpDir()` seems to output a `tmpdir` path correctly: generator-javascript-common/.tmpDir/fa8547893cdad4a56d1eff1dad1737f4f7a307d9

`process.cwd()` goes from `generator-javascript-common/.tmpDir/3209bee6601db8d25509d3fb8560d6398e74d216` to `generator-javascript-common/` after the call to `this.env.create` on line 84 of `run-context.js`

Any thoughts why this might be the case?

(ping @tacotuesday)

**Comment by SBoudrias** [comment]
You almost certainly have a `.yo-rc.json` file in `generator-javascript-common/`.

That's why the destination path is changing.

**Comment by destroyerofbuilds** [comment]
For anyone that encounters this issue as well, here's a little more context:

It's well documented under [Destination Context](http://yeoman.io/authoring/file-system.html) that `The destination context is defined as either the current working directory or the closest parent folder containing a .yo-rc.json file.`. In my situation, I was attempting to run my unit tests within a temporary directory that was a sub-folder of my generator, which just happened to have a `.yo-rc.json` file. Therefore, during my tests, my generator was crawling up the directory tree to the root of my project and using that as the directory for running the tests.

Since this was undesired behavior, I needed to scaffold a temporary `.yo-rc.json` file at the root of the temporary directory assigned to each test.

Thankfully this is documented under [Test Helpers](http://yeoman.io/authoring/testing.html); albeit, the documentation should probably include a reference to `inTmpDir` alongside `inDir`.

The difference being the two is that `inDir` expects you to pass in a directory to use for scaffolding out a project using your generator. In my case, I was perfectly fine allowing Yeoman to make that decision. All I needed was the full temporary directory path so that I could bootstrap an empty `.yo-rc.json` file before the generator ran. That's where `inTmpDir` comes into play.

`inTmpDir` provides a callback in which you can, as documented, bootstrap files before your tests run.

To create my dummy `.yo-rc.json` file prior to the tests, and thereby prevent the yeoman generator from crawling up the directory tree to the root of my project, I added the following code to a `beforeEach` block in my test suite.

```
             runGenerator = helpers.run(path.join(__dirname, '../../../generators/app'))
+                .inTmpDir(function () {
+                    var done = this.async();
+                    var fs = require('fs');
+
+                    fs.open(process.cwd() + '/.yo-rc.json', 'w', function (err, fd) {
+                        if (err) {
+                            throw err;
+                        }
+
+                        fs.write(fd, '{}', function (err) {
+                            if (err) {
+                                throw err;
+                            }
+
+                            fs.close(fd, done);
+                        });
+                    });
+                })
```

**Comment by SBoudrias** [comment]
Feel free to send a PR to clarify some documentation :)
