### ISSUE TITLE
No more `this.engine`

### ISSUE THREAD

**Issue by pauldijou** [yeoman/generator#809]
I just updated to 0.20 to enjoy the new in memory file system and the new great EJS template engine but I got a problem: it seems the engine is no longer exposed in `this.engine`. I'm doing some manual templating inside my generator, so I need an engine. I could add a dependency on EJS or whatever template engine I want but I would rather use the exact same engine at the same version as Yeoman.

Is there any chance to have `this.engine` back?

By the way, I also checked if the `engine` was still used inside the current Yeoman code and I found one occurrence [here](https://github.com/yeoman/generator/blob/master/lib/actions/remote.js#L155), of course, I got `TypeError: undefined is not a function` when trying to call `remote.template` inside my code .

**Comment by SBoudrias** [comment]
Thanks for the bug report. We'll fix the remote issue.

For the engine, there's no plan to expose it back. From now on the recommended way is to require it manually yourself.

**Comment by jdubois** [comment]
Same issue here -> @SBoudrias how can I require it manually? I have no idea how this method used to work

**Comment by pauldijou** [comment]
Add `"ejs": "^2.3.1"` to your `devDependencies` and then use `require('ejs')` in your code. You can do `this.engine = require('ejs').render` when extending Yeoman base generator if you need to keep using `this.engine`.

**Comment by jdubois** [comment]
Thanks @pauldijou I have it working!!! I didn't even know the name of our template engine :-)

**Comment by jdubois** [comment]
And now the appendScripts() is not working... I'm tired of this upgrade, method names just disappearing or behaving differently...

**Comment by kevva** [comment]
Well, API changes is expected when you're upgrading a `0.x.x` minor or a `x.x.x` major.

**Comment by jdubois** [comment]
Yes, but on JHipster we document our changes and deprecate our methods cleanly before removing them, instead of letting our end-users struggle with broken applications.

**Comment by thierrymichel** [comment]
Just to say that `this.engine` still used [here](https://github.com/yeoman/generator/blob/master/lib/actions/remote.js#L155) (as mentioned above) and not working.
@pauldijou's solution works well…
