### ISSUE TITLE
.gitignore isn't copying

### ISSUE THREAD

**Issue by ghaiklor** [yeoman/generator#812]
Hi, everyone.

I have issue with copying `.gitignore` file. My structure is simple - I have templates folder where located `.gitignore` file and others like `.editorconfig`, etc...

When I call `this.directory(this.sourceRoot(), this.destinationPath());` it's copy all the files what I need except `.gitignore`.

But, if I start generator after `npm link` (local dev) it works fine. When I published to npm then not.

Hope you can help me with that issue.

**Comment by dustinspecker** [comment]
You'll either need to rename the template file or add a .npmignore file next to the .gitignore. npm looks for a .npmignore file in each directory. If it doesn't find one, but finds a .gitignore it will rename that file to .npmignore.

**Comment by ghaiklor** [comment]
@dustinspecker I have both gitignore and npmignore and it's still not work. But I caught your idea, so this issue is not related to yeoman.

I've just renamed template files and use `this.copy` and works fine.

I hope that I can call once `this.directory(this.sourceRoot(), this.destinationRoot())` without copying each of files.

**Comment by SBoudrias** [comment]
Unfortunately that's not possible with the way npm handle things.

**Comment by raoulus** [comment]
@SBoudrias can you explain what npm has to do with it? I am trying to find what package exactly is causing it.
It looks like people still need to do workarounds to copy a gitignore :(

**Comment by SBoudrias** [comment]
@raoulus that answer wasn't very descriptive 😝 

The issue is that npm removes the `.gitignore` files (and a few other common ones) when publishing a package. So the problem is that those files are simply missing as they've never been published.

**Comment by loopmode** [comment]
I have the feeling that resource files - files whoe name starts with a dot - are silently ignored altogether.

In my template, I have a whole bunch of dot-files (`.editorconfig`, `.eslintignore`, `.eslintrc`, `.prettierrc` and several more), and none of them gets copied to the target  using `this.fs.copyTpl`, it's not just gitignore or npmignore.
