### ISSUE TITLE
this.option -> type doesn't coerce

### ISSUE THREAD

**Issue by olsonpm** [yeoman/generator#813]
So I would expect that by setting an option to a type, that any values passed via that option would at least get coerced.  Instead what happens is the type turns into whatever the passed in value seems to be (didn't look at the code for how a type is figured).

For example

```
git clone https://github.com/olsonpm/generator-option-type
cd generator-option-type
npm install
npm link

# now make a temporary directory - assume the below doesn't exist
mkdir -p ~/tmp.d/yeoman
cd ~/tmp.d/yeoman

# typeof aBoolOpt is undefined - makes sense since we never passed it
yo option-type
> typeof aBoolOpt: undefined

# typeof aBoolOpt is a boolean - also expected
yo option-type --aBoolOpt
> typeof aBoolOpt: boolean

# typeof aBoolOpt is a string, then a number
yo option-type --aBoolOpt=false
> typeof aBoolOpt: string

yo option-type --aBoolOpt=0
> typeof aBoolOpt: number
```

If this is the behavior, then what exactly is the point of declaring an option type?

**Comment by jridgewell** [comment]
> It seems as if you wrote the code regarding my issue at #813 . Mind giving some input?

All type parsing/validating is [handled](https://github.com/yeoman/generator/blob/master/lib/base.js#L332-L348) by [`nopt`](https://github.com/npm/nopt). We're either not passing in type data correctly, or this is an upstream bug.

**Comment by olsonpm** [comment]
Hey thanks a lot. I'll dig in today and reply with what I find.

**Comment by olsonpm** [comment]
@jridgewell - Got around to it.  The problematic line is in generator's [lib/base.js here](https://github.com/yeoman/generator/blob/master/lib/base.js#L343)

The issue is that this._args will receive non-option arguments from [yo](https://github.com/yeoman/yo/blob/master/lib/cli.js#L98)
[(args variable instantiated here)](https://github.com/yeoman/yo/blob/master/lib/cli.js#L16-L22)

due to the [meow](https://www.npmjs.com/package/meow#api) package

My proposed fix is PR #814

**Comment by olsonpm** [comment]
Well forget that.  Just ran through the tests - many of them depend on buggy behavior.  I don't have the time to go through and fix them.  I will close this issue and someone in the future can re-open if they want to take a stab at it.

Just to give an example:
test ['set options based on nopt arguments'](https://github.com/yeoman/generator/blob/master/test/base.js#L98-L105)
passes in options via the [arguments](https://github.com/yeoman/generator/blob/master/lib/base.js#L68) parameter.  As explained above, this is not how yo passes in options into the generator.

**Comment by SBoudrias** [comment]
Let's keep this one open.

**Comment by olsonpm** [comment]
Ah sorry - I'm so used to issue trackers where 'cases' are open and closed dependent upon whether someone is working on them.

**Comment by dszymczuk** [comment]
Next example
-----
Results of:

    yo --version && node -e "console.log(process.platform, process.versions)"

    1.4.7
    win32 { http_parser: '1.0',
      node: '0.10.33',
      v8: '3.14.5.9',
      ares: '1.9.0-DEV',
      uv: '0.10.29',
      zlib: '1.2.3',
      modules: '11',
      openssl: '1.0.1j' }

**This code:**

    this.argument('arg1', {
        type: String
    });
    console.log(this.arg1);

WORKS:

    $ yo szkolenieyeoman test

WORKS (show error):

    $ yo szkolenieyeoman 123


**This code:**

    this.option('opt1',{
        type: Number
    });
    console.log(this.options.opt1);

WORKS:

    $ yo szkolenieyeoman --opt1 123


THIS:

    $ yo szkolenieyeoman --opt1 test

show "test" on console but it shouldn't (type is number)

**Comment by olsonpm** [comment]
@dszymczuk - The issue is that all options are treated via nopt as 'unknown', thus their type is essentially ignored.  This is due to a discrepancy between how yo passes arguments, and how this portion of the code expects them to be passed.

**Comment by Panthro** [comment]
I'm using a generator with all options being passed and when I pass an option like `--opt 1.0` in my code I receive a `1` even tough my option type is a `String` can it be due to this bug?

**Comment by olsonpm** [comment]
It is possible and likely though you'd have to look into the code to know for sure.   A quick check with nopt shows that the 1.0 is kept:

```javascript
// file: test.js
var nopt = require('nopt');
var parsed = nopt();
console.log("one is '" + parsed.one + "' with typeof = '" + typeof parsed.one + "'");
```
```shell
$ node test.js --one=1.0
one is '1.0' with typeof = 'string'
```
Meaning it is not nopt's fault for parsing undefined types.  It might be due to whatever yeoman is doing to coerce types though - because I'm pretty sure if the type is left undefined then nopt just parses them as a string (save for true/false/null).

> When parsing unknown fields, "true", "false", and "null" will be interpreted as their JavaScript equivalents.

This means that somewhere yeoman is parsing these unknown fields according to its own rules.  I did not look into where this happens.

**Comment by binduwavell** [comment]
@olsonpm, as you mentioned in one of your comments on May 31, 2015, the issue seems to be related to meow. 

The issue appears to be that yeoman actually process arguments/options through two different libraries. First it pushes them through meow/minimist which is doing the yucky type coercion and is not honoring the configured types, then it is passing them through nopt which should handle the configured types correctly. 

Unfortunately since meow/minimist has messed them up before passing them along to nopt, it can't really do the right thing.
