### ISSUE TITLE
Templating Jade

### ISSUE THREAD

**Issue by adammockor** [yeoman/generator#815]
I'm using yo genarator (0.20.1) to prepare Jade templates and I got line like this:
```
<% if (condition) { %> include ../mixins/_mixin <% } %>
```
And it gives me this error:
```
Error: ENOENT, no such file or directory 'generator-lb/app/templates/views/mixins/_mixin.ejs'
```
If I put there: `_mixin.jade`, generator will inline the mixin which is also not desired.

**Comment by SBoudrias** [comment]
Can you open an issue on [ejs tracker](https://github.com/tj/ejs)

**Comment by arthurvr** [comment]
ping @adammockor

**Comment by adammockor** [comment]
https://github.com/yeoman/generator/issues/815

**Comment by SBoudrias** [comment]
EJS issue is here https://github.com/mde/ejs/issues/98

It looked resolved, so I'm closing this issue.
