### ISSUE TITLE
[ migration to 0.20.1 ] commiting files in the filesystem

### ISSUE THREAD

**Issue by jdubois** [yeoman/generator#816]
[this code](https://github.com/jhipster/generator-jhipster/blob/9dbdb0642c49786be5bfcbd94d954157566ea00e/cloudfoundry/index.js) used to work before we migrated to version 0.20.1

The issue is that we:

1. [create a file](https://github.com/jhipster/generator-jhipster/blob/9dbdb0642c49786be5bfcbd94d954157566ea00e/cloudfoundry/index.js#L79)
2. [run a process that uses that file](https://github.com/jhipster/generator-jhipster/blob/9dbdb0642c49786be5bfcbd94d954157566ea00e/cloudfoundry/index.js#L160)

As the file is in fact created in the in-memory filesystem, it is not available (yet) when the process is launched. It is indeed created, but after the process has been run. And of course the process fails if it doesn't have this configuration file.

I have tried to commit that file to the filesystem, but it is clearly written in the documentation that I should not do it.
Besides, I couldn't find a way to do it (I had JS errors when doing `this.fs.commit()`, so I guess the API prevents me to do it.

So, with this new version, how can I use a generated file in a separate process, that reads from the filesystem?

**Comment by jdubois** [comment]
[Here is the solution I implemented](https://github.com/jhipster/generator-jhipster/commit/746fcad7a071d882a37b2ceaf553d10d13815ad7) : I'm waiting for the "end" event to execute my command.

Any feedback on this?

**Comment by SBoudrias** [comment]
@jdubois This is a good alternative. Although, try to never use events, the best is to use the run loop priorities. In this case, you can run your command in the `end` priority.
