### ISSUE TITLE
Warn about project root

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator#817]
(not sure if this is just a warning or an actionable item)

It'd be nice if the system throws a prompt asking for confirmation to create the project in the parent directory that contains a 'yo-rc.json` file if it exists. Not sure how this would interact with composability though.

**Comment by SBoudrias** [comment]
I believe this would need to be handled on the yo side.

**Comment by eddiemonge** [comment]
Yeah. Not sure why I did it here.
