### ISSUE TITLE
trouble in file copying when use action.copy method

### ISSUE THREAD

**Issue by kidddddd1984** [yeoman/generator#818]
hello everyone

I'm using 0.20.x  releases in my generator project and got some troubles in file copying. seems you rewrote the  `action.copy` to match whether a file is text or not and all text files will be compiled through ejs engine. 

I use ejs engine in my express templates which means some ejs marks in `.html template` file are not desire to be compiled when scaffold. I think i can use `this.fs.copy` to avoid this issue. but as a alternative could i do something to tell `yo` don't compile these files.

**Comment by SBoudrias** [comment]
Use `this.fs.copy` and specify custom template delimiters.
