### ISSUE TITLE
this.fs.delete shows "create" when deleting files

### ISSUE THREAD

**Issue by vganapat** [yeoman/generator#820]
As per Simon's comment: https://github.com/SBoudrias/mem-fs-editor/issues/32#issuecomment-112965110, 

Assume my folder structure is :

```
dir
src
test
HelloWorld.txt


```

For instance, if I do this.fs.delete("dir/src/test"); in my Yeoman generator:

I get prompted about a conflict (why?). But anyways,

conflict dir/src/test
? Overwrite dir/src/test? overwrite
force dir/src/test
create dir/src/test/HelloWorld.txt

I assume the force statements refers to deletion of the outer test folder.

But, why, when deleting dir/src/test/HelloWorld.txt, does it say "create"?

This "create" behavior as well as the "overwrite" prompt happens for this.fs.move as well.

For reference, I am on:

yo --version
1.4.7

**Comment by SBoudrias** [comment]
This should've been fixed inside `mem-fs-editor`.

**Comment by reeslo** [comment]
I have the same issue, yo version : 1.6.0

**Comment by SBoudrias** [comment]
@reeslo This is related to the yeoman-generator and mem-fs-editor version.

**Comment by miguelsmuller** [comment]
any news ?

**Comment by paulmdorr** [comment]
Is there a solution for this? Both issues were closed a year ago, but I'm still getting this behaviour when trying to delete files with this.fs.delete() (yeoman 2.0.1).
