### ISSUE TITLE
Convenience `fs` methods

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator#824]
This is a very common operation, but it's very verbose.

``` js
this.fs.copy(this.templatePath('editorconfig'), this.destinationPath('.editorconfig'));
```

Would be nice to have a yeoman specific convenience wrapper that called `templatePath` and `destinationPath` for you:

``` js
this.fs.copyFoo('editorconfig', '.editorconfig');
```

Where `copyFoo` gets a better name.

Same with `copyTpl`.
## 

Example of how verbose it gets:

https://github.com/sindresorhus/generator-gulp-plugin-boilerplate/commit/d7503c081f025e6ce2f8665638d353e444ffc6e6#diff-2018087f584c4398b5c3a23fc0e5f9dbR53

**Comment by kevva** [comment]
Same with `.copyTpl`?

**Comment by arthurvr** [comment]
:+1:

**Comment by SBoudrias** [comment]
Sorry for the late answer, but here it is!

I considered this when designing this initial API and decided to not do anything about it at this point. There's in my opinion a pretty high complexity cost to automatically combine paths in files methods.

The main issue here is being consistent in our API. As it's very easy to see how useful it would be in the case of copy, it doesn't really make sense for the read/write methods. Can we really assume someone would always want to read from their template folder? Probably not.

Considering this, it would be very inconsistent to have different behavior between our file system helpers.

Without a better idea, I decided to go the verbose paths for now. I hoped globbing support (e.g. `fs.copyTpl(this.templatePath('**'), this.destinationPath())`) would help making this a minor annoyance.

An option I also considered is to rename `this.templatePath()` to `this.tpl()` or `this.src()` so it would be more brief in release 1.0. I'm open to any other suggestions. The only thing is that I'm sure having implicit path prefix on some methods is a bad idea as it'll break our API consistency.
