### ISSUE TITLE
Yeoman generator throws the error “Object has no method 'templatePath'”

### ISSUE THREAD

**Issue by SergeyAlexeev** [yeoman/generator#826]
According this [article](http://yeoman.io/authoring/file-system.html), I want to write some content to the html file. I use the following code:

    writing: function() {
        this.fs.copyTpl(
            this.templatePath("index.html"),
            this.destinationPath("public/index.html"),
                { title: "My template" }
        );
    }

But when I run my generator, I have the error: `TypeError: Object [object Object] has no method 'templatePath'` 

My yeoman version is 1.4.7

Related question on stackoverflow - http://stackoverflow.com/questions/31124053/yeoman-generator-throws-the-error-object-has-no-method-templatepath

**Comment by arthurvr** [comment]
> My yeoman version is 1.4.7

I think that's your `yo` version. What's the yeoman-generator version you're using?

**Comment by SergeyAlexeev** [comment]
I'm using yeoman-generator v.0.17.7

**Comment by SBoudrias** [comment]
@SergeyAlexeev You need yeoman-generator 0.18 or higher.

**Comment by arthurvr** [comment]
The `fs` methods were introduced in 0.18. http://yeoman.io/blog/release-0.18.html

**Comment by arthurvr** [comment]
and @SBoudrias was quicker :p

**Comment by SergeyAlexeev** [comment]
Thanks!
