### ISSUE TITLE
Normalize this.option/argument with this.prompt default

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#829]
`generator#option()` and `generator#argument()` are taking `defaults` as a key for a default value. Inquirer (`generator#prompt()`) takes `default`.

We should normalize this to prevent confusion.

Note that we need to be careful to handle backward compatibility when changing these names.

**Comment by eddiemonge** [comment]
Should it be default or defaults? I know some people use defaults since default is a JS keyword and might throw some editors off but that is silly reason to begin with.
