### ISSUE TITLE
Did someone break spawn.sync() on node 0.10

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#831]
I have a failing generator here: https://travis-ci.org/yeoman/generator-node/jobs/71030187

**Comment by kevva** [comment]
Seems like we're using a version of `cross-spawn` that doesn't have the sync method.

**Comment by SBoudrias** [comment]
Heum, weird, doesn't work better with the new version: https://travis-ci.org/yeoman/generator-node/jobs/71051980

(double checked we're on yeoman-generator 0.20.2 and cross-spawn 1.0)

**Comment by kevva** [comment]
@satazor, do you know why this happens?

**Comment by satazor** [comment]
Yes, check https://github.com/IndigoUnited/node-cross-spawn/issues/20
