### ISSUE TITLE
irrelevant files in log

### ISSUE THREAD

**Issue by iamstarkov** [yeoman/generator#833]
why yeoman shows irrelevant files? For example generator [nm](https://github.com/sindresorhus/generator-nm#readme) should have only relevant files like in image from readme:

expected:
![screenshot](https://cloud.githubusercontent.com/assets/559321/8730583/ed254e4a-2bf1-11e5-8d2b-a42cf2779d9f.png)

irl:
![screen shot 2015-07-16 at 19 37 03](https://cloud.githubusercontent.com/assets/559321/8730594/1574504e-2bf2-11e5-8f89-a2c96b9365db.png)

As you can see in real life post-install log contain a lot of irrelevant files, like `_package.json` or `gitignore` (without dot). Its quite confusing.

**Comment by arthurvr** [comment]
This is because we're using a really tricky way to copy the files in generator-nm.

**Comment by iamstarkov** [comment]
so it is not problem of yeoman itself, more likely it is a problem for generator-nm, right?

**Comment by kevva** [comment]
No, it's a problem with mem-fs.

**Comment by arthurvr** [comment]
Yep, FYI: https://github.com/sindresorhus/generator-nm/pull/18.

**Comment by iamstarkov** [comment]
subscribed to that issues

**Comment by SBoudrias** [comment]
Should be fixed with https://github.com/SBoudrias/mem-fs-editor/releases/tag/v2.1.0
