### ISSUE TITLE
copyTpl not skipping files.

### ISSUE THREAD

**Issue by hemanth** [yeoman/generator#834]
```js
this.fs.copyTpl([
  this.templatePath() + '/**',
  '!**/cli.js'
], this.destinationPath(), tpl);
```
`!**/cli,js` is not respected.

More info at [nm](https://github.com/sindresorhus/generator-nm/issues/20) 

//cc @SBoudrias

**Comment by SBoudrias** [comment]
Can you open this issue on [mem-fs-editor](github.com/sboudrias/mem-fs-editor)? Thanks

**Comment by hemanth** [comment]
Done.
