### ISSUE TITLE
this.fs.copyTpl undefined

### ISSUE THREAD

**Issue by reintroducing** [yeoman/generator#838]
Hello,
I'm trying to write my first generator and followed the Getting Started guide to get set up from scratch.  I'm now at a point where I have templates and want to copy them.  When I run my generator and answer the prompts I have a "writing" method that runs this:

```
writing: function() {
    var config = {title: 'Templating with Yeoman'};

    this.fs.copyTpl(this.templatePath('index.html'), this.destinationPath('index.html'), config);
}
```

This results in the following:

```
/Users/mprzybylski/Work/Personal/generator-threshold/app/index.js:64
        this.fs.copyTpl(this.templatePath('index.html'), this.destinationPath(
               ^
TypeError: Cannot read property 'copyTpl' of undefined
    at module.exports.generators.Base.extend.writing (/Users/mprzybylski/Work/Personal/generator-threshold/app/index.js:64:16)
    at /Users/mprzybylski/Work/Personal/generator-threshold/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

this.fs is undefined. I was under the impression that mem-fs-editor is built into the generator and I don't need to require/install it separately.  Is this incorrect? If not, what am I doing wrong?

Appreciate any help with this.

**Comment by SBoudrias** [comment]
Install the latest version of yeoman-generator in your project. Looks like you're using an old version.

**Comment by reintroducing** [comment]
@SBoudrias wow, you're absolutely right. That's what I get for blindly copy/pasting and not following through myself.  Apologies for wasting your time on this, rookie mistake :)
