### ISSUE TITLE
general question about tests coverage

### ISSUE THREAD

**Issue by iamstarkov** [yeoman/generator#840]
I wrote several generators and by default test coverage is near 25%, which is very low. This percentage have [nm](https://github.com/sindresorhus/generator-nm/) and [tiny-es-nm](https://github.com/iamstarkov/generator-tiny-es-nm). Is there any tips to increase test coverage?

**Comment by arthurvr** [comment]
Ref https://github.com/yeoman/yeoman/issues/1178 and https://github.com/yeoman/generator/issues/211. We know that the testing story isn't fantastic but we hope to work on it.

**Comment by SBoudrias** [comment]
We have documentation on unit testing: http://yeoman.io/authoring/testing.html

There's issue with testing the code generators as they are kind of "slow-ish" processes. But nothing stopping you from getting 100% code coverage if you so wish.

**Comment by iamstarkov** [comment]
@arthurvr @SBoudrias thank you for responses
