### ISSUE TITLE
problems w/ subgenerators in unit tests

### ISSUE THREAD

**Issue by boneskull** [yeoman/generator#842]
Hi,

So I'm trying to use `node:git` in my own generator:

```js
git: function() {
  this.composeWith('node:git', {}, {
    local: require.resolve('generator-node')
  });
}
```

as per the [example](http://yeoman.io/authoring/composability.html):

```js
this.composeWith('backbone:route', {}, {
  local: require.resolve('generator-bootstrap')
});
```

Regardless of whether or not I stub the generator with this (again per the docs):

```js

    beforeEach(function(done) {
      helpers.run(path.join(__dirname, '../generators/node'))
        .withOptions({
          skipInstall: true
        })
        .withPrompts({
          moduleName: 'foo',
          website: 'boneskull.com',
          email: 'president@whitehouse.gov',
          cli: false
        })
        .withGenerators([[helpers.createDummyGenerator(), 'node:git']]) // <--- THIS
        .on('end', done);
    });
```

I receive the error:

```
     Uncaught TypeError: object is not a function
      at Environment.instantiate (/Volumes/alien/projects/boneskull/generator-boneskull/node_modules/yeoman-generator/node_modules/yeoman-environment/lib/environment.js:297:10)
      at composeWith (/Volumes/alien/projects/boneskull/generator-boneskull/node_modules/yeoman-generator/lib/base.js:620:26)
      at module.exports.yeoman.generators.Base.extend.configuring.git (/Volumes/alien/projects/boneskull/generator-boneskull/generators/node/index.js:100:12)
      at /Volumes/alien/projects/boneskull/generator-boneskull/node_modules/yeoman-generator/lib/base.js:429:16
      at processImmediate [as _immediateCallback] (timers.js:371:17)
```

I was able to get it working with:

```js
this.composeWith('node:git', {}, {
  local: path.join(__dirname, '..', '..', 'node_modules', 'generator-node', 'generators', 'git')
});
```

However, the generator is *not* stubbed, and Git repos are created in the temp dir.

Am I doing something wrong, or does something need to be fixed, or the documentation updated, etc?

**Comment by SBoudrias** [comment]
Pretty sure you're not exporting your generator correctly. Make sure `module.exports = generators.Base.extend()`

**Comment by boneskull** [comment]
@SBoudrias That's not the issue..hmm.  Thought it might have something to do with the `files` prop of `package.json`.  Anyway, my code [boneskull/generator-boneskull](https://github.com/boneskull/generator-boneskull).  The relevant module is [here](https://github.com/boneskull/generator-boneskull/blob/master/generators/node/index.js) and also the [package.json](https://github.com/boneskull/generator-boneskull/blob/master/package.json).
