### ISSUE TITLE
suppressing `this.generator.run()` log while testing

### ISSUE THREAD

**Issue by iamstarkov** [yeoman/generator#843]
Is there any docs for suppressing `this.generator.run()` log while testing?

I found that `this.generator.run()` declared with [settings](https://github.com/yeoman/generator/blob/master/lib/test/run-context.js#L35) has only one [prop `tmpdir`](https://github.com/yeoman/generator/blob/master/lib/test/run-context.js#L35) and then generator is runing wo/ options. Ask about help, because I dont need "create" logs while testing

logs take a lot of space at the screen 
![screen shot 2015-08-04 at 13 08 36](https://cloud.githubusercontent.com/assets/559321/9059406/f185c5a2-3aa9-11e5-9785-579f1d5036f2.png)

**Comment by SBoudrias** [comment]
You need to pass a test adapter that'll mute the logging.

But really, just use our test utilities, it'll be done automatically: http://yeoman.io/authoring/testing.html

**Comment by iamstarkov** [comment]
sorry for this confuision, but [i’m already using mocha and yeoman’s test utilities](https://github.com/iamstarkov/generator-tiny-es-nm/blob/master/test.js). Am I doing it wrong?

**Comment by SBoudrias** [comment]
> Am I doing it wrong?

Yes.

Please read the documentation I linked. http://yeoman.io/authoring/testing.html

**Comment by iamstarkov** [comment]
thank you
