### ISSUE TITLE
Tests with conflicting content crash

### ISSUE THREAD

**Issue by Pinpickle** [yeoman/generator#844]
I'm re-running generators over existing generated content in a temp directory to save some testing time - for installing dependencies mainly.

When I do this and there is a conflict, I run into this error:

    Uncaught TypeError: this.adapter.log[result.action] is not a function

Mocha is decidedly difficult to debug with, but I managed to track down the culprit code in [Conflicter.js](https://github.com/yeoman/generator/blob/v0.20.2/lib/util/conflicter.js#L193)

    this.adapter.log[result.action](rfilepath);

I did a check to see what the value of `result.action` is in this conflict. It's `undefined`. I think that this is due to the way the conflict prompts are being mocked.

This is related to #825, but my use-case is in the OS's tmp directory, just like Yeoman does by default. I'm just not emptying them before testing in some cases.

Running `yeoman-generator@0.20.2` and `iojs@3.0.0`

**Comment by SBoudrias** [comment]
Yes, we don't support prompting using our test helpers - basically because there's no user to answer them.

Your best bet is to set `--force` flag to force conflict overwrites.

But FWIW, you shouldn't re-run all your unit test in the same folder, there's no reason to do so - and it's not faster.

**Comment by Pinpickle** [comment]
@SBoudrias it *is* faster if you need to run tests with the dependencies installed - especially if you're using Composer which is really slow on the first run in a directory. I want to run a comprehensive set of tests that cover a variety of different options so things could quickly get out of control.

Force flag is a much better fix than what I had in mind for a fix though, so thanks!
