### ISSUE TITLE
this.async() not working in environment callback

### ISSUE THREAD

**Issue by paulvanbladel** [yeoman/generator#846]
Following code is not working
```
initializing : function(){
    var done = this.async();
    this.env.register('generator-loopback','lb');
    this.loopbackGenerator = this.env.create('lb',{ options: { 'skip-install':this.options['skip-install'] } });
  this.loopbackGenerator.run(function(){
    this.log("run callback");
    this.done();
  }.bind(this));
  },
```
When I move the this.done() to the end of the initializing queue method, the loopback generator is doing it's work, but of course the other queue methods (e.g. writing) are executed in parallel.
So, I want to suspend procesing until the loopback generator has done it's work.
this.async() seems to work inside other callback methods but not in a callback method from 'Environemt'.
thanks.

**Comment by SBoudrias** [comment]
You're calling `this.done()` rather than `done()`.

Also, you can use `this.invoke()` to call a generator without keeping the loop running. But either way, using composition is always the better option. http://yeoman.io/authoring/composability.html

**Comment by paulvanbladel** [comment]
Sorry that was a typo.
Done () doesnt work.

**Comment by paulvanbladel** [comment]
Would love to use composewith, but i want also to wait until generator finished.
How!?

**Comment by SBoudrias** [comment]
@paulvanbladel You should re-conceptualize the issue you're trying to fix so it fit with the way composition works. Might require you to rethink the way you see your program, but in the end it'll work better.

**Comment by SBoudrias** [comment]
@paulvanbladel About the done not working, must be something to do with starting another generator on the same environment. This is not possible and break your code (I would've assume this would create a deadlock).

You can use the legacy [invoke](http://yeoman.github.io/generator/invoke.html) to do what you want, but this feature is deprecated and will be removed. Your best bet is to re-architecture your generator to make use of composability.

**Comment by paulvanbladel** [comment]
The code above, as such (with done() and not with this.done()) is failing. So, there is only one generator involved and this is failing. But indeed, I want to start a second generator in a subfolder of the result output of the first generator. If ALL this is finished, the process continues with the actual generation work of the master generator, so the one currently running.
If I use ComposeWith I didn't find a way to run the second generator in a subfolder.
Your help would be very very much appreciated. Thanks in advance!
Here is draft version: https://github.com/paulvanbladel/generator-aurelia-loopback/blob/master/generators/app/index.js
