### ISSUE TITLE
generator in es6

### ISSUE THREAD

**Issue by iamstarkov** [yeoman/generator#847]
sorry for bothering you with a lot of questions in the last few weeks. I wrote [generator](https://github.com/nordnet/generator-nordnet-es-module) for nordnet, based on mine, which is based on [nm](https://github.com/sindresorhus/generator-nm). So I rewrite generator in es6 in last commits, and tests are fines, but then I need to transpile and here ["deeply linking to the file system"](http://yeoman.io/authoring/index.html) came into the game. With current setup tests are green, but generator is broken, because its not transpiled yet. Ok, I can rename app folder to src and transpile it too, but then tests are red. So I have working transpilation or green tests at the same time, But I want both of them. I read docs, sorry If I missed something. Can you help me?

generators already written in es6 with tests, missed docs or some useful tips will be great.

**Comment by SBoudrias** [comment]
Can't help you much about your setup. `yeoman-generator` works fine with ES6. This is an issue with your setup, not a bug on our side.

Please refer to StackOverflow for support question. (Obviously ask a question about babel - not Yeoman - if you want an answer)

**Comment by iamstarkov** [comment]
@SBoudrias yep, I have no problem with yeoman-generator. I have an problem with compiling and testing my generator at the same time, because I have no idea how to deal with "deelpy linking to the file system"

**Comment by iamstarkov** [comment]
And its not about babel, because I can use it for other modules.

**Comment by iamstarkov** [comment]
and yep, its not a problem, its just not clear how to create and maintain testable generator which, also should be compiled

**Comment by iamstarkov** [comment]
only one way I found is to transpile generator before test it.

**Comment by SBoudrias** [comment]
You can checkout https://github.com/yeoman/generator-node and a related issue https://github.com/yeoman/generator-node/issues/162
