### ISSUE TITLE
Composed generators and prompts

### ISSUE THREAD

**Issue by wwhurley** [yeoman/generator#850]
I'm separating out a somewhat monolithic generator into a series of smaller sub-generators. Right now they are included inside a ```this.prompt()``` command from the main generator which loops through the included sub-generators and calls ```this.composeWith()```. And then in each sub-generator I have a separate ```prompting``` implementation that calls ```this.prompt()```. For some reason I'm getting prompts from multiple sub-generators appearing on the same line and basically overwriting each other, but still responding to the same key strokes. For example I'll get a confirm from one sub-generator appearing on the screen, but hitting Enter will cause that to be the answer for both the confirm but also an input from another sub-generator that shares the same array index.

So a couple of questions:

1. Are multiple composed generators supported?
2. Is there anything in particular I should be aware of when using ```this.prompt()```?

**Comment by SBoudrias** [comment]
I think you're just not waiting for the user answer before asking more prompt; e.g. `var done  = this.async()`

**Comment by wwhurley** [comment]
So from my main generator I have:

```
  prompting : {
    plugins : function() {
      var done = this.async();
      var that = this;
      
      this.prompt(questions, function (answers) {
        _.each(answers.plugins, function(plugin) {
          that.composeWith(plugin, {
            options : {
              parent : that
            }
          }, {});
          done();
        });
      }.bind(this));
    }
  },
```

And then in each of the sub-generators there's:

```
  prompting : function() {
      var done = this.async();
      
      this.prompt(questions, function (answers) {
        this.config.set(answers);        
        done();
      }.bind(this));
  },
```

Is there someplace else I should be calling ```this.async()```?

**Comment by SBoudrias** [comment]
Well on any asynchronous action. But that code looks right.

**Comment by wwhurley** [comment]
Found my problem. Wasn't watching my scopes correctly and had the ```this.async()``` inside the _.each loop. Once I moved it out everything works as intended.
