### ISSUE TITLE
Base generator destinationPath is based on process.cwd() instead of env.cwd

### ISSUE THREAD

**Issue by JulienCabanes** [yeoman/generator#861]
I'm working on a non-CLI Yeoman integration following [this documentation](http://yeoman.io/authoring/integrating-yeoman.html) and as I tried to setup the generator's `destinationPath` it appears to be impossible.

Actually I think I know why : looking at [this code](https://github.com/yeoman/generator/blob/master/lib/base.js#L125) it seems that the base generator never uses `env.cwd` as it should (right?) but `process.cwd()`.

**Comment by SBoudrias** [comment]
What is the `env` you're referring to?

**Comment by JulienCabanes** [comment]
@SBoudrias I'm referring to [`this.env`](https://github.com/yeoman/generator/blob/master/lib/base.js#L50)

**Comment by SBoudrias** [comment]
Okay, so if we were to use `this.env.cwd`, we'd still CD into that folder. Is that what you'd expect?

**Comment by JulienCabanes** [comment]
Yes, by default `this.env.cwd` is the same as `process.cwd()` but this is an option of the environment constructor.
May I submit [this PR](https://github.com/JulienCabanes/generator/commit/d44ef03a404b89cecf1d52f23ef2de31b368b0c1) ?

**Comment by SBoudrias** [comment]
Yes, submit it :) I'll review it in the next few days.

**Comment by JulienCabanes** [comment]
OK, [one test](https://github.com/JulienCabanes/generator/blob/master/test/base.js#L68) is not passing anymore but I think the test is wrong : it's doing a `process.chdir()` before Dummy generator instanciation instead of before environment instanciation. Don't know what to do :)

**Comment by SBoudrias** [comment]
@JulienCabanes can you submit your PR here, having the travis run and simply the branch handy will help troubleshoot what's going on here.

**Comment by JulienCabanes** [comment]
@SBoudrias https://github.com/yeoman/generator/pull/879

**Comment by SBoudrias** [comment]
Fixed with #879 - closing
