### ISSUE TITLE
composedWith generator prompts

### ISSUE THREAD

**Issue by kingcody** [yeoman/generator#862]
I'm not sure if this is a bug (with yeoman-generator|inquirer) or an issue with my implementation.

My setup is that I'm writing a sub-gen that is composed with another (smaller) sub-gen. Both have prompts which are fully configurable via options, and their prompts use `when: () => !self.options.PROMPT_NAME`. The initial gen calls `composeWith` after it's prompts so that it can pass prompt values as options to the composedWith gen. All of the required options/prompts for the composedWith gen are supplied by the initial gen. This allows the composedWith gen to skip it's prompts, which in this case are identical to the initial's prompts.

The problem is that after both gens are done running (after their end phase) the console is still waiting for some form of input. A simple CR will return you to the console prompt.

Currently my fix is to manually check the `prompt[].when` conditions and skip `this.prompt` when all are false. I wouldn't say that its a terrible amount of work, but it would be nice to defer that logic to `this.prompt`.

If anyone, familiar with inquirer and/or its implementation in yeoman-generator, has any suggestions or ideas, I would love to hear them.

**Comment by SBoudrias** [comment]
Looks like an async issue. You probably forgot to call `this.async()` somewhere.

**Comment by kingcody** [comment]
@SBoudrias thanks for the quick reply. I'm not exactly sure that is the problem. I've created a [sample project](https://github.com/kingcody/generator-test) which demonstrates my issue. Would you be so kind as to take a quick glance and see if I have miss used anything? Thank you for your time.
