### ISSUE TITLE
Cannot replace local sub-generator with stub for testing

### ISSUE THREAD

**Issue by mdotasia** [yeoman/generator#863]
I wrote a generator `generators/app/index.js` that calls a local sub-generator `generators/editorconfig/index.js` via `composeWith`:

```
configuring: function () {
  if (this.options.editorconfig) {
    this.composeWith('mdotasia-theme:editorconfig', {}, {
      local: require.resolve('../editorconfig/')
    });
  }
}
```

I wrote a test for sub-generator `editorconfig` separately in `test/editorconfig.js`. Then I wrote a `test\app.js` in which I want to check if sub-generator `editorconfig` is called. I googled an came across this post: http://stackoverflow.com/questions/27643601/testing-yeomans-composewith. It suggests to replace the sub-generator with a dummy generator that executes a `sinon` spy.

My `test/app.js` basically looks like this:

```
describe('run with defaults', function () {
    before(function (done) {
      this.spy = sinon.spy();
      var GeneratorStub = yeoman.generators.Base.extend({
        spy: this.spy
      });

      helpers.run(path.join(__dirname, '../generators/app'))
        .withGenerators([
          [GeneratorStub, 'modotasia-theme:editorconfig']
        ])
        .on('end', done);
    });

    it('run sub-generator editorconfig', function () {
      assert(this.spy.called);
    });
  });
```

However, when I run it, the test shows that the dummy generator is never called. So I checked what `composedWith` actually does (see https://github.com/yeoman/generator/blob/master/lib/base.js#L613-L633) and it looks like the moment `settings.local` is set, `composeWith` just instantiates the local sub-generator and ignores the dummy generator that has already been registered under the same namespace `mdotasia-theme:editorconfig` in the `Environment`'s store.

Shouldn't `composeWith` first check if there is already a generator with the same namespace registered in the `Environment` and instantiate the local sub-generator only if there is none?

Or how else can I test that my sub-generator has been invoked?

**Comment by SBoudrias** [comment]
Duplicated by https://github.com/yeoman/generator/issues/704

There's also manual fix you can do explained in that issue.
