### ISSUE TITLE
Replacement for generator.engine after update

### ISSUE THREAD

**Issue by johannesjo** [yeoman/generator#865]
After updating from 0.19.1 to 0.20.3 i get the following error:
```
Object [object Object] has no method 'engine'
```
when calling:
```
this.indexFile = this.engine(this.read('index.html'), this);
```

**Comment by SBoudrias** [comment]
You can use `_.template` directly. We removed this feature as you can only use the root module for the same result.

**Comment by johannesjo** [comment]
Thank you very much. Thats it.
