### ISSUE TITLE
Question/doc request: is there funtionality for "user initiated composition"

### ISSUE THREAD

**Issue by sthzg** [yeoman/generator#867]
I am coming from this [question on SO](http://stackoverflow.com/questions/33291455/what-does-composition-initiated-by-an-end-user-mean) about the "user initiated composability" mentioned in [the docs](http://yeoman.io/authoring/composability.html).

Based on @SBoudrias comment from 2014 #551 this second option back then was something planned. Has this changed by now or is it still up for discussion? If it is not in already or may take a little longer I would vote for explicitly mentioning that in the docs.

+1 btw. for user initiated composability, but I guess this is technically a sophisticated topic. :)

**Comment by SBoudrias** [comment]
This is still only a far planned feature. Feel free to send a PR to clarify the documentation!

**Comment by sthzg** [comment]
Great, thanks for your reply. Sent a PR, but I think its not optimal since the very next paragraph below mentions:

> Note: The User composability feature landed in core in version 0.17.0. It is a work in progress but is stable enough to start using. Further documentation will come after a few refinements to the process and can be expected sooner rather than later!

Maybe it would be better to reject my PR and rephrase this paragraph instead? (I guess the generator-based composition landed in 0.17 as well? if yes, it might be enough to split that note into two parts about that user initiated comp. is planned and generator-based composability landed in 0.17?).

**Comment by SBoudrias** [comment]
Sorry I kind of dropped the ball on that one. I've been working on other aspect of the Yeoman project for the last few months.

So, as it is documented further, I think I'll close this issue. If you want to submit a PR to yeoman.io to discuss improving the documentation further, please do :)
