### ISSUE TITLE
Question/doc: how to proper mock dep generators?

### ISSUE THREAD

**Issue by iamstarkov** [yeoman/generator#868]
I wrote [babel-init](https://www.npmjs.com/package/generator-babel-init) and to be able to test it I need to run `$ npm install` which works fine, but it affects testing outer generators (generators which are composed with it). [Here I add timeout](https://github.com/iamstarkov/generator-babel-init/blob/master/package.json#L14) to tests in `babel-init`, then I tried to run tests in [tiny-es-nm](https://github.com/iamstarkov/generator-tiny-es-nm) but they are obviously failed due to timeout, so I [had to add timeout here](https://github.com/iamstarkov/generator-tiny-es-nm/blob/master/package.json#L6) too. And its not consumer friendly at all.

I tried to [mock](http://yeoman.io/authoring/testing.html) `babel-init` but it doesn’t work: [pr from demo branch](https://github.com/iamstarkov/generator-tiny-es-nm/pull/14/files) and [travis log with still installing deps](https://travis-ci.org/iamstarkov/generator-tiny-es-nm/jobs/89465972#L212-L279). It doesnt work. Can you help me?

```js
.withGenerators([
  [helpers.createDummyGenerator(), 'generator-babel-init/generators/app']
])
```

**Comment by SBoudrias** [comment]
Well, if you only want to not run `npm install`, then just respect the `--skip-install` command line flag.

This flag is automatically passed during tests unless specified otherwise.

About `withGenerators`, my guess is that you're running into #704

**Comment by iamstarkov** [comment]
im trying 

```js
var skipInstall = this.options['skip-install'];
var needInstall = !skipInstall;
if (needInstall) {
  this.npmInstall(this.devDepsToInstall, { 'save-dev': true });
}
```
but its not working, am i doing it right? testing docs doesn contain anything about `skip-install` option

**Comment by SBoudrias** [comment]
@iamstarkov did you logged the value of skip-install?

Also, if sub-generators are running installs, you'll need to passthrough the skip-install option

**Comment by iamstarkov** [comment]
yep, i logged it
```
if (needInstall) {
  console.log('install babel deps');
  this.npmInstall(this.devDepsToInstall, { 'save-dev': true });
}

…

  generator
Initialized empty Git repository in /private/var/folders/qg/65nsk96n2t9cwjgsn9h31h0h0000gp/T/15d6bc0d87921c578a7663c1f313c87902994cb8/.git/
needInstall true
install babel deps
```

what do you mean by passthrough skip-install options while im running sub-generators?

**Comment by SBoudrias** [comment]
Like:

```js
this.composeWith('gen', {
    options: {'skip-install': this.options['skip-install']}
});
```

**Comment by iamstarkov** [comment]
Thank you, it is working
