### ISSUE TITLE
How to tell if bower isn't installed

### ISSUE THREAD

**Issue by grawk** [yeoman/generator#871]
I'm experimenting with the variable of bower not being installed for a user who is using my generator. It seems like `installBower` will not report this condition. Is there a recommended approach to handle this scenario?

**Comment by sindresorhus** [comment]
That method should probably check first if Bower is installed and warn if not.

**Comment by SBoudrias** [comment]
We could totally change our install method to do:

1. Check if install tool is installed
2. No? Then we post install information
3. Yes? Run tool install

**Comment by mischah** [comment]
mhmm. Isn’t that already implemented over here? 
https://github.com/yeoman/generator/blob/master/lib/actions/install.js#L48-L53

**Comment by sindresorhus** [comment]
@mischah Wild guess, maybe the exit code isn't always 127 and the code path isn't hit.

**Comment by eddiemonge** [comment]
Looks like its throwing 0 currently.

Maybe just a general message like: `There was a problem running installer. Make sure it is installed and the install command works.`

**Comment by mischah** [comment]
I’m going to try to fix that :octocat:

**Comment by addyosmani** [comment]
Thanks!

**Comment by mischah** [comment]
> Thanks!

My Pleasure. PR over here: #967
