### ISSUE TITLE
Set a local destinationPath to a composed sub-generator with `#composeWith()`

### ISSUE THREAD

**Issue by canercandan** [yeoman/generator#872]
I have done some quick search among the submitted issues, but didnt find anything about passing a specific `destinationPath` when we call the `#composeWith()` method that makes the value local to the sub-generator.

I am trying to find the best way to reuse as many existing generators as possible but here it is I am facing an issue, most of the generators cf. `generator-travis` will generate their files based on its default `destinationPath` path.

It's right we can still redefine the `destinationPath` thanks to `#destinationRoot()` method but it could quickly become error-prone since it remains a global value to the whole generators (composed one too).

The `RunContext` design calls the generator methods according to ordered groups (default, writing, …), meaning if set a path at the top of the run-loop and set another path meanwhile we will get a collision and only the last one will be considered, the explanation is a bit confused but I guess you are getting the point.

For the yeoman designers, do you think it could be a valuable enhancement ?

**Comment by SBoudrias** [comment]
> For the yeoman designers, do you think it could be a valuable enhancement ?

Yes, this would be very useful.

Although there's some historic reasons as to why destination root is globally shared.

Basically, we have a lot of generators who're not relying on the built-in files utilities. We got a lot of people using some raw `fs` methods with paths relative the the current working directory. To allow destination root to work, we had to bind this virtual path with the actual CWD.

This have been working well to get older generators to update to new versions of the generator framework more easily, and to allow some amount of composition with legacy generators.

Binding the destination roots to the CWD, just makes bad generators harder to break.

That being said, we should totally reconsider this for 1.0. It'd be way easier if you could just tell a generator to run inside of x folder.

For now though, you could ask the author of `generator-travis` to take a path parameter and base themselves of that path to know where to generate their files.

**Comment by canercandan** [comment]
@SBoudrias Thanks for your answer it's much more clear now. I dont have enough knowledges regarding the yeoman-generator code structure to provide a PR for now so I will follow your recommendation to request a PR for the sub-generators I am using with a path option.

**Comment by iamstarkov** [comment]
@canercandan can you give me some insight why do you need this feature?

**Comment by canercandan** [comment]
Sure, let says you are using the travis generator twice on two sub-directories of the generated project, that means the resulting files hierarchy may look like:
```
/folder1/.travis.yml
/folder2/.travis.yml
```

The easiest way to accomplish this is by adding a `path` option in the used generator in order to set the destination path of the copied file.

**Comment by iamstarkov** [comment]
okay, is there any real life use cases for this?

**Comment by canercandan** [comment]
Sure consider a fullstack project repository including frontend and backend
(client and server).

**Comment by res63661** [comment]
Anybody ever figure this out?  I am having the devil's own time figuring out how to overtly set the destinationPath on a subgenerator

**Comment by mshima** [comment]
`this.composeWith(gen, {destinationRoot: subDir})`?

**Comment by kalbert312** [comment]
> `this.composeWith(gen, {destinationRoot: subDir})`?

This doesn't seem to be working for me. yo@next-4. After passing `{ destinationRoot: this.destinationPath("client") }` to my subgenerator compose calls the subgenerators are still running in the original `this.destinationPath`)

**Comment by mshima** [comment]
@kalbert312 please open a new bug report specifying which generator version you are using.
