### ISSUE TITLE
`run` event not working?

### ISSUE THREAD

**Issue by SamVerschueren** [yeoman/generator#874]
Hi, I'm not sure about this issue but it looks like the `run` event is not received by my application.

I am using `yeoman-environment` to run a generator as I am developing a VS Code plugin. The user picks a generator from a list and 1 second later, the first question pops up. Between picking a question and showing the first question, I want to show a progress bar. But in order to do that, I have to know when the first question is poping up (e.g. when the generator is fully resolved).

I couldn't find any documentation, but it looks like the `run` event is the one I need.

```js
this._env.run(generator, this.done)
	.on('run', () => {
		console.log('run')
	})
	.on('npmInstall', () => {
		this.setState('install node dependencies');
	})
	.on('bowerInstall', () => {
		this.setState('install bower dependencies');
	})
	.on('end', () => {
		this.clearState();
		console.log(`${EOL}${figures.tick} done`);
	});
```

But it is never emitted (at least, my log is never shown). Am I missing something here?

**Comment by SBoudrias** [comment]
I don't think so. Just went through the code and the run event should be correctly fired https://github.com/yeoman/generator/blob/master/lib/base.js#L392

FWIW, the run event should be triggered almost immediately. You can probably just run your code for the progress bar without waiting for the event to be triggered.

**Comment by SamVerschueren** [comment]
I debugged it with breakpoints and it indeed fires, but it's strange that my `console.log('run');` is never executed.

**Comment by SBoudrias** [comment]
I'll close then. Maybe the environment you're running into is doing some funky stuff with console.log.

**Comment by SamVerschueren** [comment]
That's not it, because when I put a breakpoint there, it's not working either.

I don't need that event anymore, however wanted to share this information. It seems that `environment.run()` is a synchronous operation.

So this (dummy) code works:
```js
progress.start();

environment.run('generator-generator', done);

progress.stop();
```

While in the beginning, I thought I had to do this

```js
progress.start();

environment.run('generator-generator', done)
    .on('run', () => {
        progress.stop();
    });
```

This is my implementation: [yo.ts#L89-L105](https://github.com/SamVerschueren/vscode-yo/blob/master/src/yo/yo.ts#L89-L105)
