### ISSUE TITLE
Remove `process.exit` when aborting a conflict

### ISSUE THREAD

**Issue by SamVerschueren** [yeoman/generator#876]
A core team member of Visual Studio code reported that `process.exit()` is used when the user aborts during a file conflict. This should be avoided and should be replaced by something else.

More information: https://github.com/SamVerschueren/vscode-yo/issues/23

**Comment by SBoudrias** [comment]
How about we replace by raising an error (like `throw new Error('user aborted the process')`)

Also note that any changes here won't fix any generator who don't update to the last version of yeoman-generator.

**Comment by SamVerschueren** [comment]
I'm ok with the error approach. 

> Also note that any changes here won't fix any generator who don't update to the last version of yeoman-generator.

So be it :)

**Comment by SamVerschueren** [comment]
Awesome! Thanks @SBoudrias :)
