### ISSUE TITLE
How to install dependencies sequentially

### ISSUE THREAD

**Issue by unional** [yeoman/generator#878]
In my generator I want to run `npm i` and `jspm i` sequentially so that the log output won't mixed together. How do I do that?

Currently, if I put them together:

````
install: function() {
    this.npmInstall();
    this.spawnCommand('jspm', ['install']);
}
````

or

````
install: {
    npm: function() { this.npmInstall(); },
    jspm: function() { this.spawnCommand('jspm', ['install']); }
}
````

the will be run at the same time.

I'm aware that I can put `jspm i` in the `end` queue, but I want to use it for post-install code and it has the same problem (i.e. all codes in `end` queue runs in parallel).

http://stackoverflow.com/questions/33862275/yeoman-how-to-install-dependencies-sequentially

**Comment by SBoudrias** [comment]
Yeoman is only Node.js and JavaScript. You'll handle this in the same way you'd handle any asynchronous action.

**Comment by SBoudrias** [comment]
Meaning forcing waiting for the action to be done before starting the next.

Something like that:

```js
install: {
    npm: function() { this.npmInstall(this.async()); },
    jspm: function() { this.spawnCommand('jspm', ['install'], this.async()); }
}
```

**Comment by unional** [comment]
thanks! Not really familiar with node and the `this.async()` syntax.

**Comment by unional** [comment]
When I do what you suggest, it gives the following error:

````
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: paths.split is not a function
    at install.runInstall (E:\hwong\codes\p4\projects\generator-panda\node_modules\yeoman-generator\lib\actions\install.
js:33:58)
    at install [as npmInstall] (E:\hwong\codes\p4\projects\generator-panda\node_modules\yeoman-generator\lib\actions\ins
tall.js:160:15)
    at module.exports.generators.Base.extend.install.npm (E:\hwong\codes\p4\projects\generator-panda\generators\app\inde
x.js:76:32)
    at E:\hwong\codes\p4\projects\generator-panda\node_modules\yeoman-generator\lib\base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
````

**Comment by SBoudrias** [comment]
You actually want `this.spawnCommand('jspm', ['install']).on('close', this.async());`.

Note you can also use `this.spawnCommandSync`

**Comment by unional** [comment]
The error is thrown on `this.npmInstall(this.async());` thou.

`yo --version && echo %PATH% %NODE_PATH% && node -e "console.log(process.platform, process.versions)" && type Gruntfile.js`:
1.5.0
C:\ProgramData\Oracle\Java\javapath;C:\Ruby22-x64\bin;C:\Python27;C:\Windows\sys
tem32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\
v1.0\;C:\Program Files\Perforce;C:\Program Files\nodejs\;C:\Program Files (x86)\
Git\cmd;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Windows Kits\8.1\W
indows Performance Toolkit\;C:\php5.6\;C:\Program Files\Perforce\DVCS\;C:\Progra
m Files (x86)\nodejs\;C:\Users\hzhang\AppData\Roaming\npm\;C:\Users\hwong\bin\Se
ncha\Cmd\6.0.0.202;C:\Users\hwong\AppData\Local\atom\bin;C:\Program Files (x86)\
Microsoft VS Code\bin;C:\Users\hwong\AppData\Roaming\npm %NODE_PATH%
win32 { http_parser: '2.5.0',
  node: '4.2.2',
  v8: '4.5.103.35',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2d' }
The system cannot find the file specified.

**Comment by SBoudrias** [comment]
You don't actually need to pass `this.async()` to npm install

**Comment by unional** [comment]
Um... in that case `jspm` is run before `npmInstall`. `npmInstall` needs to run first.

**Comment by unional** [comment]
Same result for:
````
    install: {
        npm: function() {
            this.npmInstall();
        },
        jspm: function() {
            this.spawnCommand('jspm', ['install']).on('close', this.async());
        }
    },
````

**Comment by SBoudrias** [comment]
Okay, help yourself a little.

Here's some documentation http://yeoman.io/authoring/dependencies.html

And `paths.split` make it looks like we expect and Array but we get an undefined type.

**Comment by unional** [comment]
This, that what I figured. 
Seems like a feasible solution is to not using `this.npmInstall()`:

````
    install: function() {
            this.spawnCommandSync('npm', ['install']);
            this.spawnCommandSync('jspm', ['install']);        
    },
````
