### ISSUE TITLE
Generator not being listed?

### ISSUE THREAD

**Issue by khalwat** [yeoman/generator#880]
I wrote a generator that has a GitHub repository description, and has `yeoman-generator` keyword and a description in `package.json`, but it's not being listed.  What did I do wrong?

https://www.npmjs.com/package/generator-nystudio107

https://github.com/khalwat/generator-nystudio107

**Comment by SBoudrias** [comment]
@eddiemonge any ideas?

**Comment by eddiemonge** [comment]
Looks like there is an issue with the list being updated this week. I'm looking into it.

**Comment by khalwat** [comment]
Okay thanks.  I also noticed that the sorting on this page:

http://yeoman.io/generators/

...doesn't seem to do anything...?

**Comment by khalwat** [comment]
Looks like something was done (there are more generators listed now than yesterday), but mine still isn't appearing.

**Comment by eddiemonge** [comment]
Closing this as it should be opened in the generator-list repo. Will hopefully get the list updated today
