### ISSUE TITLE
How to get the answers from my composed generators?

### ISSUE THREAD

**Issue by lnmunhoz** [yeoman/generator#884]
I'm trying to create a generator that calls another subgenerators, but I need the `props` of some subgenerators to use in the main generator. This is possible using the `composeWith` method?

Example:
```js
module.exports = yeoman.generators.Base.extend({
  firstGenerator: function() {
    // I know the API is not like this. Its just an example...
    this.composeWith('generator-foo:bar', {}, {}, function(props) {
      this.props.something = props.something;
    })
  }
}
```

There's a way to do this without much pain?

**Comment by SBoudrias** [comment]
Nope. Data in generators flows one way, from the top to the bottom.

There's no way for a children generator to communicate with the parent.

This is to keep them maintainable and easy to reason about. Composed generators must be self contained.

What you'll usually do, is get most of the relevant information from the top generator, and pass all those values through options to sub-generators.
