### ISSUE TITLE
NamedBase deprecation message is confusing

### ISSUE THREAD

**Issue by gruppjo** [yeoman/generator#886]
Hi and thanks for the new release :)

I just upgraded to `yeoman-generator v.0.22.1` and got deprecation warnings.
```
(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly
```
I kept looking for lines of code that used `generators.Base` but there were none. It took me a while to find out that `generators.NamedBase` is also deprecated. Turns out that they were the cause for the deprecation warnings, which I found misleading, since `generators.Base` was mentioned in the deprecation warnings.

**Comment by dreamypixy** [comment]
I also encountered that when I installed <code>npm i -g generator-webapp</code>.

**Comment by SBoudrias** [comment]
a PR to make the message more helpful is welcomed!

**Comment by mischah** [comment]
I’m going to submit a PR to fix that :octocat:
