### ISSUE TITLE
Arrow function in constructor breaks generator

### ISSUE THREAD

**Issue by hugohil** [yeoman/generator#887]
I was updating my generator when I noticed that this code works just fine:

```javascript
'use strict'

const generators = require('yeoman-generator')

module.exports = generators.Base.extend({
  constructor: function () {
    generators.Base.apply(this, arguments)
  },
  initializing: () => {
    console.log('initializing')
    // You can go all the way to the 'end' method like this
  }
})
```

while this one won't

```javascript
'use strict'

const generators = require('yeoman-generator')

module.exports = generators.Base.extend({
  constructor: () => {
    generators.Base.apply(this, arguments)
  },
  initializing: () => {
    console.log('initializing')
    // You can go all the way to the 'end' method like this
  }
})
```

Difference is that the `constructor` method is overrided in the first case by an arrow function, and in the second by a regular anonymous function.

node version is `v4.2.4`, yo is `1.5.1`, and os is OSX 10.11.1.

This is not blocking at all, just has aroused my curiosity :)

**EDIT:**

When changing first example to:

```javascript
// 'use strict', const declarations etc ...

module.exports = generators.Base.extend({
  constructor: function () {
    generators.Base.apply(this, arguments)
  },
  initializing: () => {
    this.log('initializing')
  }
})
```

Generator also breaks, where following code won't:

```javascript
// 'use strict', const declarations etc ...

module.exports = generators.Base.extend({
  constructor: function () {
    generators.Base.apply(this, arguments)
  },
  initializing: function () {
    this.log('initializing')
  }
})
```

After reading back the [doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), I still have no clear answer. Closing this as this is not really relevant for the module development, but if anyone have answers, I'm all ears.

**Comment by SBoudrias** [comment]
Yeah, arrow functions are not a shorter way to write a function. They have a different behavior, and in your case, they're breaking your constructor.

With es2015, it'd be better to write it this way:

```js
class MyGenerator extend generators.Base {
  constructor() {
  
  }

  // etc
}
```
