### ISSUE TITLE
way to access whole string for cli option

### ISSUE THREAD

**Issue by iamstarkov** [yeoman/generator#892]
i want to use cli option like this: `$ yo eslint-init --plugins meow purr` and have plugins option as `meow purr`. Right now a working workaround is to separate plugins with comma and split it in the generator. Can i adress this issue in better way?

**Comment by sindresorhus** [comment]
That's not how CLI arguments parsing works. `purr` is a positional argument, while `meow` is the value of  `--plugins`. You'll have to quote them, `'meow purr'` for it to work as you want. You really shouldn't try to work around this.

**Comment by iamstarkov** [comment]
thank you

**Comment by SBoudrias** [comment]
Yeah, working around this would also mean your generator won't work on the GUI implementation of yeoman.

**Comment by iamstarkov** [comment]
so, quoting a string like `-p "purr meow"` and then `.split(' ')` inside my generator is a bad idea?

**Comment by SBoudrias** [comment]
@iamstarkov no that's fine as it's using the system at your disposition.
