### ISSUE TITLE
[discussion] Next major generator API iteration

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#894]
### Current state and issues

So over the last few year, we've been maintaining the same old yeoman-generator API. For the past few release, I've been trying to get rid of legacy feature that made for bad user experience and hard to maintains generators.

I think we're getting to the end of what we can do to improve the current API. And maybe the way forward is to rethink the way yeoman-generator works.

Notably, I can think of a few features that would be hard to implement in the current state:
- Merging/duplication between prompts, arguments and options (#552)
- Opening the system to custom vinyl adapter (#720)
- Unit testing (right now we really only support integration tests)
- Composability ordering and sharing is hard to reason about

Also, there's been some complaint the API was more complex than the alternatives.

So I've been thinking a little bit about what our next goal should be. I don't quite yet have a full flushed out API in my mind, but here are some pointers:
#### Composability

The current system is really patching our current system to allow composability. It's hard to coordinate generators together and share context between them.

There's also some good point with the current system: it enforce decoupling and it enforce strict top-down value sharing.

So I think we need to update our view of composability to view each generator as a **layer**. Each generator add a layer on top of another one.

Another important point is that generators must be able to order layers. (compared to the current API where scheduled tasks are mangled together)
#### Goodbye class base system

Maybe it's me, but I really dislike class base anything. I'd like each generator ("layer") to be define in a single function. I don't know if it'd be possible as we also need to consider how to handle important lifecycle events (scheduling install phase, running commands, logic related to the composability, etc)

Having a single function would be great as it'd encourage separation of concerns in different reusable layers and it'd be easier to unit test.
#### Single input definition

I wish to be done with prompt, arguments and options. I want a single definition of input, then the user can specify them all as either options or he'll be prompted for the values. 

This will require a better validation system.
### Your feedback

Please let us know what else you want to see in the future.

**Comment by sindresorhus** [comment]
@SBoudrias Probably a good idea to tweet about this to get community eyes on it.

My biggest want is to make generators just normal node modules with a main entry point and a loose API contract/protocol to run them. That way generators become generic scaffolds and the community can easily make other runners if they wish. We would still provide a utility module, but it would be optional.

I too dislike the current class system and personally wish the whole thing was a lot simpler.

**Comment by iamstarkov** [comment]
my want is to be less coupled to file system, its hard to write generators in es6

**Comment by iamstarkov** [comment]
i also dislike complicated class system

like a wish to be able to write generators as normal node modules

**Comment by iamstarkov** [comment]
Dont like idea of generatos as layer on top of above others, i see next gen generators in another way.

There will be small modules focused on one thing, which take some input and work on its own and there will be another type of generators: more suited for different environment or needs, which will be a composition of modular ones. Bigger generators will gather anything they need from consumer and pass this information to composed smaller generators. I would say my ideal generator will look something like this:

```js
module.exports = yeoman.generators.Base.extend({
  init: function () {
    var cb = this.async();
    this.prompt([ 
      /* kinda */
      'person', 'email', 'website', 'github',
      'name', 'desc', 'license', 'keywords', 'license'])
    ])
  },
  writing: function () {
    [ 'pkg',
      'readme',
      { 'copy': { files: [ 'index.js', 'test.js' ] } },
      { 'license': { license: this.options.license } },
      { 'travis': { config: { after_script: ['npm run coveralls'] }}},
      { 'eslint-init': { config: { extends: 'airbnb' } }}
      { 'babel': { config: { plugins: [ 'add-module-exports' ] },        
      'git-init',
    ].forEach(composeGenerator.bind(this));
  },
  install: function () {
    this.npmInstall();
  }
});
```

**Comment by stephanebachelier** [comment]
@iamstarkov far more easier to read / use / write / debug :)

**Comment by SBoudrias** [comment]
@iamstarkov What is the difference between this structure and what we have now? This could totally be done with everything we're having currently.

Roughly

```js
[
  ['travis', {'versions': ['v4', 'v5']}]
].forEach((...args) => this.composeWith(...args));
```

That's just a structure which is harder to debug and inspect by setting breakpoints.

**Comment by SBoudrias** [comment]
FWIW, here's a rough draft of what I have in mind:

```js
yeoman.defineGenerator({
  input: [
    {name: 'foo'}
  ],

  layers: [
    layer.fromGenerator(require('generator-node').app),
    layer(function (props) {
      this.fs.copyTpl(
        this.templatePath('index.js'),
        this.destinationPath('index.js'),
        {name: props.name}
      );
    }),
    layer.fromGenerator(require('generator-travis/app'), function (props) {
      return {
        versions: ['0.10', '0.12']
      };
    })
  ],

  transforms: [
    beautify()
  ],

  postProcess: [
    'npm install'
  ]
});
```

**Comment by iamstarkov** [comment]
@SBoudrias 

> What is the difference between this structure and what we have now? This could totally be done with everything we're having currently.

its true, the reason why i show this piece of code, to illustrate to illustrate my "next-gen-yo" idea of small modular generators used by bigger ones suited for projects and companies

**Comment by ejohnsonw** [comment]
I currently use  a couple of yeoman generators as 'surrogates' for www.generatron.com to scaffold a project and then generate other stuff on top of it. This could be a question with an already existing answer  OR  feature request. A way to feed options to the generator without having to respond to prompts.

**Comment by iamstarkov** [comment]
@ejohnsonw cli arguments?

**Comment by ejohnsonw** [comment]
@iamstarkov yes, cli arguments,

**Comment by tangoabcdelta** [comment]
Yo retards (sorry, I'm furious now, you can delete this un-helpful comment later)

**Comment by tangoabcdelta** [comment]
- How do you think of preventing caching on html templates?
- Why there is still no/little support for apps made with requirejs?
- Is there a generator with requirejs? Certainly not.
- Will you please move to lib-sass or anything that saves us from that 100sec compass compilation horror?

**Comment by iamstarkov** [comment]
@tangoabcdelta your first comment is pretty much unproductive and doesnt relate to discussion, please moderate it. thanks!

@tangoabcdelta 

> How do you think of preventing caching on html templates?

i dont get it, what do you mean?

> Why there is still no/little support for apps made with requirejs?
> Is there a generator with requirejs? Certainly not.

I'm almost sure that yeoman generator API have nothing to do with requirejs in particular and this issue belongs to userland

> Will you please move to lib-sass or anything that saves us from that 100sec compass compilation horror?

dont you confuse yeoman-generator with any userland custom generators? there are no compass dependency in this project

**Comment by iamstarkov** [comment]
today I found that it would be great if yeoman generators will be just functions which take virtual file system snapshot as an argument and return another snapshot. in this case they will be easily composable and really decoupled

**Comment by SBoudrias** [comment]
ccing @Swiip and @zckrs as this might interest you in regard to how you're building FountainJS

**Comment by zckrs** [comment]
Looking forward to this future iteration:

* goodbye class base system :100: 
* a better unit test integration (with AVA :smile:?)
* "make generators just normal node modules with a main entry point and a loose API contract/protocol to run them" :100: 
* "generators will be just functions which take virtual file system snapshot as an argument and return another snapshot." :100: (like [Metalsmith](https://github.com/metalsmith/metalsmith)?)
* single input definition :100: 

I notice @SBoudrias have start the next iteration https://github.com/yeoman/generator/compare/master...SBoudrias:layers

About [FountainJS](https://github.com/FountainJS) we will follow this discussion but at moment we will continue development based on [v0.22.5](https://github.com/yeoman/generator/releases/tag/v0.22.5). 
When the next major version is released in a beta state obviously we will migrate with enthusiasm :smile:

**Comment by SBoudrias** [comment]
Yeah, we have the base system working. The main remaining part is to re-add every helpers people would expect, path handling and then mostly test it out. I'm fairly busy in the coming weeks, so it's still probably at least a month away before a first beta version.

**Comment by deepu105** [comment]
how about using a vinyl-stream kind of stuff for the files so that it can be processed similar to gulp?

Another pain point I currently see is the prompt system, hence a better input system that can be used from cli as well as programatically without having to write equivalent cli flags would be welcome

Also better composability please, the current mechanism feels like voodoo sometimes, so yes something thats simpler and more debuggable

A global context between all the composed generators would be very nice to have, so that properties and functions can be shared and reused. We kind of do these using workarounds in generator-jhipster [here ](https://github.com/jhipster/generator-jhipster/blob/master/generators/modules/index.js)

**Comment by iamstarkov** [comment]
@SBoudrias is this issue still relevant?

**Comment by SBoudrias** [comment]
@iamstarkov Yeah, it's still a good vision IMO. I just don't think anyone really have time to work on it right now.

**Comment by nevir** [comment]
Re: confusion about composed generator ordering - one behavior that really caught me off guard is that any actions in a composed generator run _after_ the generator that called `composeWith`.  This makes overriding composed behavior rather difficult

**Comment by SBoudrias** [comment]
@nevir yes totally, that's going against the expected flow. The run-loop fixed a scheduling issue we had, but it might've gone a bit too far. The next major iteration would ideally address that issue which is I think a major pain for authoring composable generators.

**Comment by nevir** [comment]
Huh, actually - that specific problem seems pretty straightforward to fix: https://github.com/yeoman/generator/pull/1017

**Comment by Tim15** [comment]
Any updates on this? Is it still on a roadmap?
