### ISSUE TITLE
feat: save default answers from prompts

### ISSUE THREAD

**Issue by iamstarkov** [yeoman/generator#895]
I [found that if i choose default value for prompt, then yeoman doesnt save it to storage](https://github.com/yeoman/generator/blob/fdcf6fb99ddf22fc73a70662bba8272b1acaa634/lib/util/prompt-suggestion.js#L72-L88). and this doesnt fit in my case.

Let me explain, I want to ask consumer about preferred license and version to start from, in following attempts i dont want to ask these questions even if consumer decided to go with default answers.

I understand that it made sense to not keep default values as far as they already default and they will be automatically picked up from `this.prompts.item.default`, but as far as I understand (use cases and codebase) it will be the same way if yeoman will save default values.

What do you think? and i can create pull-request for this fix

**Comment by iamstarkov** [comment]
(

**Comment by SBoudrias** [comment]
Stored prompts are never skipped. The value is simply used as default the next time we ask the same question.

It's important for the end user to be able to change their answer if at any points they change their mind.

**Comment by SBoudrias** [comment]
I'll close this issue due to no answer. Feel free to continue the discussion if you had something further to add.
