### ISSUE TITLE
Super nitpicky suggestion: use "&&" as command separator in yo output

### ISSUE THREAD

**Issue by erikkemperman** [yeoman/generator#899]
Currently [this line](https://github.com/yeoman/generator/blob/master/lib/actions/install.js#L127) inserts a single ampersand as command separator. But for copy/pastability wouldn't it be better for this to be `&&`?

**Comment by sindresorhus** [comment]
`&` is used to spawn the first command in a subshell, so both of them are run concurrently, for performance reasons.

**Comment by erikkemperman** [comment]
@sindresorhus Aha, thanks for clearing that up. I knew about the & separator to run commands in background, but kind of thought that `bower install` might sometimes require `npm install` to have completed with exit code 0.
