### ISSUE TITLE
Breaking change in 0.22.5 in relation to 0.22.0

### ISSUE THREAD

**Issue by evil-shrike** [yeoman/generator#901]
My generator starts malfunctioning with yeoman-generator@0.22.5
I have the following code:
```
	writing: function () {
		process.chdir(this.clientProjectDir);

		mkdirp.sync('vendor_components');

		this.copy('bowerrc', '.bowerrc');
```
The code changes current dir then does all work inside it.

It worked fine with 0.22.0 but not with 0.22.5!
With 0.22.5 all generator's methods for files/folders manipulations (like `template`, `copy`, etc) ignore cwd changed with `process.chdir`. That is the cwd is changed (`process.cwd` returns new folder), but generator's methods create files/folder in a folder where we were before `process.chdir` call.

Why did you break behavior?
Anyway it's not a good idea to this such a change in with a revision version change.

**Comment by SBoudrias** [comment]
This is a long time functionnality. Not sure this ever worked on 0.22 - if it did then it was a bug.

Any files actions are done related to your template root toward your destination root.

If you need to change these values, then you can set them up with `this.sourceRoot(newRoot)` or `this.destinationRoot(newRoot)`. But the best way really is to just pass correct paths in your functions:

```js
this.fs.copy(
  this.templatePath('bowerrc'),
  this.destinationPath(this.clientProjectDir, '.bowerrc')
);
```

See http://yeoman.io/authoring/file-system.html

**Comment by evil-shrike** [comment]
> Any files actions are done related to your template root toward your destination root.

This is not true. Please see #1037
