### ISSUE TITLE
Allow to skip template while using `remote.directory()` 

### ISSUE THREAD

**Issue by Plou** [yeoman/generator#902]
Hi, I'm writing a generator to install and clean a existing repository ([generator-dummies](https://github.com/dummy-team/generator-dummies)). The files i'm scaffolding may contain template tags, is there a way to skip templating while copy a whole directory with `remote.directory()` ?

```javascript
this.remote('user', 'repo', 'branch', function (err, remote) {
  remote.directory('grunt', './grunt');
}
```

A file in the grunt folder contains this string: `'/*! uglified <%= grunt.template.today("yyyy-mm-dd HH:MM:ss") %> */'` which generator tries to parse.

Similar to #877, but remote don't have the `fs` methods. I tried `bulkDirectory`but it don't work well with an empty / outdated cache.

**Comment by SBoudrias** [comment]
These methods are deprecated. Use `this.fs.copy`/`copyTpl`.

An option is to copy everything and delete what you don't want. Or provide a complex glob pattern to the fs copy methods.

See http://yeoman.io/authoring/file-system.html

**Comment by Plou** [comment]
Thanks for the quick reply.

Is the remote method is deprecated too ? if it is, what is the right method to fetch a github repo ?

**Comment by SBoudrias** [comment]
@Plou Ideally, you'd load your git repository with npm. Then you copy it from the `node_modules` folder.

**Comment by Plou** [comment]
Thanks
