### ISSUE TITLE
this.remote async execution order

### ISSUE THREAD

**Issue by julmot** [yeoman/generator#903]
A part of a yeoman generator:
```javascript
loadingFiles: function(){
	var done = this.async();
	this.remote('xyz', 'xyz', 'master', function(err, remote){
		remote.directory('src', 'src');
		done();
	}, true);
},
something: function(){
	this.log("FINISHING");
},
finishing: function(){
	this.installDependencies();
}
```
will print the following:
```
Fetching...
FINISHING
I'm all done. Running npm...
create "...."
....
```
`Fetching...` and `create "..."` is related to `this.remote`.
So what I expect is:
```
Fetching
create "..."
FINISHING
I'm all done. Running npm...
```
What is going on here?

**Comment by SBoudrias** [comment]
What version are you on?

**Comment by julmot** [comment]
NodeJS: 4.2.2
Yo: 1.6.0

**Comment by SBoudrias** [comment]
I meant `yeoman-generator` version.

**Comment by julmot** [comment]
Sorry, in Germany it was late :bowtie: 
yeoman-generator: 0.22.5

**Comment by julmot** [comment]
Bump

**Comment by benitolopez** [comment]
Same issue here. `yeoman-generator` v.0.22.5

**Comment by julmot** [comment]
@SBoudrias bump

**Comment by benitolopez** [comment]
Personally I’ve solved the issue using an NPM module instead of the built-in remote utility. And I agree with @SBoudrias (https://github.com/yeoman/generator/issues/766#issue-59199797) regarding the remote and fetch utilities: those tasks can be accomplished with other NPM modules.

By the way, is just my opinion :)

**Comment by julmot** [comment]
@benitolopez What npm module?

**Comment by benitolopez** [comment]
@julmot [download](https://www.npmjs.com/package/download) and [download-status](https://www.npmjs.com/package/download-status)

**Comment by julmot** [comment]
@benitolopez Thanks for letting me know. How are you handling remote fetches where you only want to download a single file or directory, not the entire zip?

**Comment by benitolopez** [comment]
I'm using that module to download the whole zip so I've never tried with a single file. But the example in the [download](https://www.npmjs.com/package/download) page downloads a zip and a single file. Just delete the "zip" line.

**Comment by julmot** [comment]
@benitolopez I can confirm it shows an example to download a single file. However, since GitHub doesn't provide download links for single folders of a GitHub repo I would need to download the entire repo, extract it into a temporary folder and copy the things from there. Seems to be not a really profit instead of debugging `this.remote`.

**Comment by SBoudrias** [comment]
@julmot I'll get to it, but I'm fairly certain it's an issue with your code specifically as you're the only one who reported this issue - or any issues regarding asynchronous execution. As such, it's not really to the top of my todo list currently.

If you can create a reducer test case generator reproducing this issue, it'll help me look into it faster. Also, it might just help you figure out the issue if it's effectively related to your own code.

**Comment by julmot** [comment]
@SBoudrias on your wish

## Demo generator
Here is a ZIP containing a demo generator:
[generator-demo.zip](https://github.com/yeoman/generator/files/130547/generator-demo.zip)


## Steps to reproduce
All you need to do is extract it and run `$ npm link` inside `./app/`. Then create a temporary folder and run `$ yo demo` inside. 

## Expected behaviour
This will output:

![log](https://cloud.githubusercontent.com/assets/8310677/13046763/19eb7bfc-d3db-11e5-88e6-c2393073e212.jpg)

I have framed the wrong part. All `remote` related logs should be after the `Fetching` statements.

**Comment by SBoudrias** [comment]
Oh, I totally misunderstood your issue.

The `create x` logs are all shown at the end of the process because any files operations happens on a memory store. As so, they're not commited to the user disk until the generator is done running. So effectively, all file writes happens all at once at the end of the process.

**Comment by julmot** [comment]
@SBoudrias  Thanks for letting me know.  
Even if yeoman-generator writes files to a buffer and only stores them in the destination if the generator is finished, then the log should still be in the same order as the commands were called?  
If this is not possible due to internal reasons, is there a way to hide those "create" statements for better understanding?

**Comment by SBoudrias** [comment]
@julmot what is really the issue you want to fix?

**Comment by julmot** [comment]
@SBoudrias I would like to have a console output that shows the tasks in the same order they are processed in the background. If an action like `remote` is handled before `this.installDependencies()` then this should be printed before.

**Comment by julmot** [comment]
@SBoudrias Bump

**Comment by SBoudrias** [comment]
Hey, you could manually use `this.log()`, but we have no plans to change the way we log stuff than in the actual real order they are happening.

**Comment by julmot** [comment]
I find the current log behavior confusing and I think others too. Is there a way to hide those "create x" statements?

**Comment by SBoudrias** [comment]
No. We haven't had complaint from end users and we want to keep the experience consistent across our ecosystem.
