### ISSUE TITLE
#runInstall expose command if failed

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/generator#906]
If the #runInstall spawn fails (or skipInstall is set) it should log what the command would have run so the user can run it on their own. This would include things like `--save-dev`

**Comment by rgroothuijsen** [comment]
I'm interested in doing this one, but in [the relevant part of the code](https://github.com/yeoman/generator/blob/master/lib/actions/install.js) I see a variety of logging methods and formats being used. What is the currently recommended way?

**Comment by SBoudrias** [comment]
@rgroothuijsen you'd want to use `this.log()` when logging the message after failure.
