### ISSUE TITLE
single or double quotation not being converted by yoeman generator

### ISSUE THREAD

**Issue by AquiburRKhan** [yeoman/generator#907]
" or ' is not being generated in the output file after using yoeman generator! They get converted to `&#39` or `&#34` instead of " or ' . I have tried using \' , \" and "&quot";

**Comment by SBoudrias** [comment]
Where? How? What were you doing? Step to reproduce? I need detail if you want help on this issue. For now I don't have anything.

**Comment by eddiemonge** [comment]
I did experience this as well recently but cannot remember where it was.

edit: found it. @AquiburRKhan are you seeing this in your template? I saw it when doing this: https://github.com/yeoman/generator-karma/commit/958b78559620ea06ce3022b0d140b34a02f16789#diff-f44b11585ce2da3624f63aa8051c237fL7

I think underscore might have changed that somewhere or fixed a bug that enforces it.

**Comment by AquiburRKhan** [comment]
@eddiemonge  @SBoudrias  Thank you for your response.

i am trying to get a model field generated for ex: 

name: {
type: String,
default: \' \'
}

Thus in my index file i have this code, 

var name = this.fieldName+": { \n type: String,  default: \'  \'   \n}, \n";

but instead of showing me my desire output the , file is giving me the code: 

name: {
type: String,
default:  &#39;  &#39
}

I mentioned above, the things i have tried and i also tried ' \' ' based on what i understood by the link given by @eddiemonge 

its still not working.

thank you for your response again and hope you can help out :)

**Comment by eddiemonge** [comment]
How are you writing that to a file?

**Comment by AquiburRKhan** [comment]
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var <%= module_name%>Schema = {

......................

<%= texts%>

 ......................

module.exports = <%=module_name%>;


The "<%=texts%>"   is where the code is written

**Comment by SBoudrias** [comment]
Did you try with `<%-`?

**Comment by AquiburRKhan** [comment]
It worked. Thank you so much, been stuck with it for a while now.
