### ISSUE TITLE
Array argument

### ISSUE THREAD

**Issue by ferllings** [yeoman/generator#909]
Hello,

According to the documentation, you can pass an array as command line arguments (http://yeoman.io/authoring/user-interactions.html)

What is the exact format for the command line?

Thanks,

**Comment by iamstarkov** [comment]
i [faced](https://github.com/yeoman/generator/issues/892) the same issue, so convenient way is `--param "key1,key2"` and then  `.split(',')` inside your generator or use [split-keywords](https://github.com/iamstarkov/split-keywords), because there are few caveats with pure `.split` approach

**Comment by ferllings** [comment]
Thanks,

that sounds like a good solution.
