### ISSUE TITLE
Prompt Chinese message appears weird tab?

### ISSUE THREAD

**Issue by dickeylth** [yeoman/generator#911]
![](https://gw.alicdn.com/tps/TB18utGLVXXXXcNXXXXXXXXXXXX-300-250.gif)

As show in the gif above, for inquirer prompts with Chinese message, when input characters, there would appear weird tab before the input string, however for English message, the weird phenomenon won't appear.

I also tried node tools that depends `inquirer` alone, no such question occured, so I guess the bug was in yeoman.

I've submitted the source code to <https://github.com/dickeylth/yeoman-generator-bug> for your convenience.

- System: OS X El Capitan 10.11.3 (15D21)
- node: v4.2.4

**Comment by SBoudrias** [comment]
We just need to bump inquirer dependency in yeoman-generator. We fixed utf8 letters spawning more than one byte in the latest inquirer release.

**Comment by SBoudrias** [comment]
This should be fixed with the latest release.
