### ISSUE TITLE
Enabling stdout during testing

### ISSUE THREAD

**Issue by apowers313** [yeoman/generator#912]
I see that #472 disabled stdout during testing, but now I have a test that is hanging and I have no idea why. Is there any way to optionally re-enable stdout during testing?

**Comment by SBoudrias** [comment]
This request should go into this repo https://github.com/yeoman/yeoman-test

You could probably add a flag or something to turn the logging on or off. PR welcomed.

**Comment by SBoudrias** [comment]
Specifically these are the lines you want to look at https://github.com/yeoman/yeoman-test/blob/master/lib/adapter.js#L52
