### ISSUE TITLE
actions.copy ignores passed process function.

### ISSUE THREAD

**Issue by dazld** [yeoman/generator#913]
The `actions.directory` method allows passing a `process` function that is called on every file copied. 

Unfortunately, `this.directory` delegates to `this.copy` - which does nothing with the passed `process` function. 

actions.directory invoking copy with all options -> https://github.com/yeoman/generator/blob/master/lib/actions/actions.js#L165

actions.copy only takes two arguments -> https://github.com/yeoman/generator/blob/master/lib/actions/actions.js#L35

**Comment by SBoudrias** [comment]
You should rely on the newer `this.fs` functions. See:

- http://yeoman.io/authoring/file-system.html
- https://github.com/SBoudrias/mem-fs-editor

These will work as you want.

**Comment by dazld** [comment]
ok! a deprecation message would be useful - silently ignoring the passed function threw me a little.

**Comment by SBoudrias** [comment]
@dazld is that function thing a documented feature? I think it's just an inconsistency between the two methods.

**Comment by dazld** [comment]
I ended up looking at http://yeoman.io/generator/actions_actions.js.html - (line 176 etc), which was linked from 'full api documentation' in the creating a generator menu... for me, it looked like a current method, and is referenced in stackoverflow etc. Is this the most current documentation..?

**Comment by SBoudrias** [comment]
@dazld it is, it's just we still have a lot of depreciated methods on the API documentation. JSDoc is not really great - but it might be better than nothing?
