### ISSUE TITLE
How to access global store?

### ISSUE THREAD

**Issue by unional** [yeoman/generator#917]
I know that you can use `store: true` in `prompt()` to store value to the global store.

Is there a way to get value from the global store programmatically?

I want to create some template / global config for the generator so I want to first determine if it exists in the first place.

**Comment by iamstarkov** [comment]
```js
this.savedAnswers = this._globalConfig.getAll().promptValues || {};
```

though, its internal API and you should not rely on it

**Comment by unional** [comment]
Thanks. 

Any plan on making it public? I think it is pretty useful

**Comment by iamstarkov** [comment]
I'm not in yeoman team so can't answer

**Comment by eddiemonge** [comment]
`this.config.getAll()`

http://yeoman.io/authoring/storage.html

**Comment by unional** [comment]
`this.config.getAll()` does not get data from the global store.

**Comment by unional** [comment]
```js
// this.config.getAll()
{}
// this._globalConfig.getAll()
{ promptValues: { username: 'me' } }
```

**Comment by eddiemonge** [comment]
You shouldn't be trying to use the global store but the local store that your generator actually created

**Comment by unional** [comment]
> I want to create some template / global config for the generator so I want to first determine if it exists in the first place.

This is what I want to do. Besides the global config, I can't think of another place to do this.

**Comment by SBoudrias** [comment]
@unional then don't rely on the yeoman global config store. Use your own.
