### ISSUE TITLE
[Bug] Storage#save method doesn't work

### ISSUE THREAD

**Issue by adoyle-h** [yeoman/generator#919]
My code is:

```js
module.exports = generator.Base.extend({
    configuring: function() {
        var props = {a: 1, b: 2};
        this.config.save(props);
    },
});
```

Result: 
![image](https://cloud.githubusercontent.com/assets/1998490/14410444/79025586-ff62-11e5-9c56-45210032ba00.png)

Refer to  https://github.com/yeoman/generator/blob/master/lib/util/storage.js#L58

It seems that the param `val` is missing.

node: v5.10.0
yeoman-generator: 0.22.5

**Comment by iamstarkov** [comment]
i would say its not a bug.

as you can see from the code `save` doesnt take any arguments.

**Comment by iamstarkov** [comment]
> Also note that the save method is called automatically each time you set a configuration option. So you usually won't need to call it explicitly.
> http://yeoman.io/authoring/storage.html

**Comment by SBoudrias** [comment]
Yeah, that's a JSDoc bug. You want to call `this.storage.set({foo: 'bar'})`

**Comment by adoyle-h** [comment]
Thanks @SBoudrias , `this.config.set({foo: 'bar'})` works.

I thought that the `save` method is used to write configuration because of I saw that `save(val) → {null}`.

> This method will write the configuration to the .yo-rc.json file. If the file doesn't exist yet, the save method will create it.

And currently the `set` function signature is `set(key, val) → {*}`, not `set(obj) → {*}`.

![image](https://cloud.githubusercontent.com/assets/1998490/14415933/f8e2e224-ffd6-11e5-9ed5-c0513d423d60.png)

I would be grateful if you could modify the document and JSDoc more accurate.

Thanks all.
