### ISSUE TITLE
The error thrown from generator is swallowed

### ISSUE THREAD

**Issue by adoyle-h** [yeoman/generator#921]
## Situation

I am using `yeoman/environment` to build my scaffolding tool for private project. I find that the error thrown from generator is always swallowed. But `yo` commands such as `yo node` looks correct even when I modify the `generator-node` to throw an error intentionally.

The error actually is thrown by ejs when it find a syntax error during compiling. For brief description, I will throw the `new Error('!!!!');` intentionally.

This is my yeoman generator:

```js
// g.js
var generator = require('yeoman-generator');

module.exports = generator.Base.extend({
    initializing: function() {
        this.log('Welcome to the generator!');
        throw new Error('!!!!');
    },

    writing: function() {
        console.log('For writing');
    },
});
```
Here is how I use yeoman-environment:

```js
// env.js
var yeoman = require('yeoman-environment');

var env = yeoman.createEnv();

// see https://github.com/yeoman/environment/blob/master/lib/util/log.js
var log = env.adapter.log;

process.on('uncaughtException', function(err) {
    log.error('Uncaught exception occurred in application!', err.stack || err.message || err);
    process.exit(2);
});

env.on('error', function(err) {
    log.error('[Error]', process.argv.slice(2).join(' '), '\n');
    log.error(err.stack);
    process.exit(1);
});

var generator = require('./g');
env.registerStub(generator, 'g');

env.run('g', function(err) {
    if (err) {
        log.error(err);
    }
});
```

In fact, the error listener on `env` is never invoked. And run `node env` will only print that

```
Welcome to the generator!
```

The error stack and `For writing` are missing.

## Reason

I find that the main reason lies in [yeoman/generator](https://github.com/yeoman/generator/blob/master/lib/base.js#L441).

I add two lines for debug:

```js
runAsync(
  function () {
    self.async = function () {
      return this.async();
    }.bind(this);

    return method.apply(self, self.args);
  },
  function (err) {
    if (err) {
      debug('An error occured while running ' + methodName, err);
      console.log('1. check error listeners', self.listeners('error'));   // Just for debug
      self.emit('error', err);
      console.log('2. does it go on?');   // Just for debug
      cb(err);
      return;
    }

    completed();
  }
)();
```

run `node env` will print that:

```
Welcome to the generator!
1. check error listeners []
```

`2. does it go on?` is missing, and `cb(err);` never be invoked.
Because of `self.listeners('error')` is an empty array.

Refer to the [EventEmitter API document](https://nodejs.org/dist/latest-v5.x/docs/api/events.html#events_error_events).

> If an EventEmitter does not have at least one listener registered for the 'error' event, and an 'error' event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits.

So `self.emit('error', err);` throw an error, again. While the `runAsync` is a [run-async](https://github.com/SBoudrias/run-async/blob/master/index.js) function, which using a promise inside, `self.emit('error', err);` throw an error in the onRejected function, but there is no catch for it. Therefore, the error thrown from generator is swallowed.

I suggest the rejected promise should be caught:

```js
runAsync(
  function () {
    self.async = function () {
      return this.async();
    }.bind(this);

    return method.apply(self, self.args);
  },
  function (err) {
    if (err) {
      debug('An error occured while running ' + methodName, err);
      self.emit('error', err);
      cb(err);
      return;
    }

    completed();
  }
)().catch(function(error) {
  // pass the error to the caller
});
```

There is another question: why `yo` commands print the error stack correctly?

Finally, I find that `yo` requires the [meow](https://github.com/sindresorhus/meow), which makes unhandled rejected promises fail loudly instead of the default silent fail. Refer to its [feature](https://github.com/sindresorhus/meow#promises).

I think uncaught rejected promise is a potential bug in program.

## versions

- os: Mac OS X 10.11.3 15D21
- node: v5.10.0
- yeoman-environment: 1.5.2  (local installed)
- yeoman-generator: 0.22.5  (local installed)
- yo: 1.7.0  (global installed)

**Comment by SBoudrias** [comment]
Hey, thanks for this very detailed investigation. Sorry for being so slow at answering, I was focusing on other projects and play catch up with the issues right now.

> I think uncaught rejected promise is a potential bug in program.

This is effectively a bug.

Would you mind sending a PR? I guess eventually we'd want to move more and more of the yeoman API to use promises. This would prevent these conflicts between callback and promise backed API (not that they're specifically exclusive, more that it's easy for the programmer to get mixed up with the behavior.) That being said, a minimal fix to correctly emit the error would be totally sufficient.

**Comment by adoyle-h** [comment]
The unit test action#bulkDirectory() sometimes fail because of mocha timeout. Maybe my computer run slowly. Can I set the timeout limit to 3000ms? @SBoudrias
