### ISSUE TITLE
Access inquirer.Separator through yeoman

### ISSUE THREAD

**Issue by gruppjo** [yeoman/generator#922]
Currently I'm using `inquirer.Separator` in [Generator-M-Ionic](https://github.com/mwaylabs/generator-m-ionic) and the only way I managed to do that is to explicitly include inquirer as an explicit and additional dependency and then:
`package.json`
```js
// ..
"dependencies": {
  "yeoman-generator": "^0.22.1",
  "inquirer": "^1.0.0",
   // ..
}
```
```js
var inquirer = require('inquirer');
// ..
choices: [
  new inquirer.Separator('---- Description here ----'),
  {
     name: 'some choice'
     value: 'some value'
  }
]
```

Is there a better way to do this? Would it make sense to expose the full Inquirer API through yeoman?

**Comment by SBoudrias** [comment]
You can pass it as `{type: 'separator', line: '--------------- Description --------------------'}`

**Comment by gruppjo** [comment]
Wonderful. Thanks! Can't believe I didn't see that in the docs... https://github.com/SBoudrias/Inquirer.js/#separator
