### ISSUE TITLE
Update inquirer to stable release

### ISSUE THREAD

**Issue by yangchenyun** [yeoman/generator#924]
Inquirer has stabled its API in 1.0.0 release, it also adds an 'autocomplete' prompt type.
https://github.com/SBoudrias/Inquirer.js/releases

There is a major change on the prompt API whose effect propagates to yeoman's API as well.

**Comment by SBoudrias** [comment]
> it also adds an 'autocomplete' prompt type

There's no new prompt in Inquirer 1.0

Update would be good. Though there's some backward compatibility and integration with third party API stability to account for.

FWIW, this work will happen inside yeoman-environment.

**Comment by yangchenyun** [comment]
You are right, this PR made to its own module: https://github.com/SBoudrias/Inquirer.js/pull/265 👍

**Comment by SBoudrias** [comment]
Inquirer is now updated.
