### ISSUE TITLE
Prompt - Breaking change + no doc update

### ISSUE THREAD

**Issue by fluky** [yeoman/generator#926]
It appears that the project was recently updated with a breaking change to prompt.  It now returns a promise and does not call the callback function.  Typically when other projects add promise support they do it in a non-breaking faction, i.e., if callback is passed, then it is used, otherwise a promise is returned.

Either way, the documentation is now out of date and still refers to the callback.

**Comment by SBoudrias** [comment]
It was documented in our release notes https://github.com/yeoman/generator/releases/tag/v0.23.0

We'll update the documentation soon.

**Comment by caseyWebb** [comment]
👍 to issue, 👎 for not using semver

**Comment by caseyWebb** [comment]
https://github.com/yeoman/generator/pull/931

**Comment by SBoudrias** [comment]
> 👎 for not using semver/backwards-compatibility

 We are using semver correctly. We're pre 1.0 and have been releasing breaking change with every release.

I'll close this issue as the documentation has been updated last week,

**Comment by caseyWebb** [comment]
Out of curiosity, is there any merit to not starting at 1.0.0? I see this all the time and it makes zero sense to me.

Yeoman is pretty ubiquitous in the front-end world at this point; is a v1.0.0 impending? I see the milestone, but it almost seems abandoned.

**Comment by SBoudrias** [comment]
Slowly working towards it, but it's not a priority for me. It just sounds good on paper.

When I have time to work on Yeoman, I prefer to tackle issues that'll have bigger impact on the generator author community. Rushing to close a 1.0 release is not something out of what people will get a lot of value.
