### ISSUE TITLE
calling Prompt throws error in v0.23.1+

### ISSUE THREAD

**Issue by m-ux** [yeoman/generator#930]
I'm hitting an issue and wondering if someone can confirm.

Running a simple test of `this.prompt` using the example from the docs is throwing an error for me on **v0.23.1+** (it runs fine on **0.23.0**). Running `yo` **v1.7.0**

example code:
```
var generators = require('yeoman-generator');

module.exports = generators.Base.extend({
  prompting: function () {
    return this.prompt({
      type: 'input',
      name: 'name',
      message: 'Your project name',
      default: 'Hello'
    }).then(function(answers) {
      this.log(answers.name); // do stuff with returned answers
    }.bind(this));
  }
});
```

relevant part of error log:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (<path-to>/yeoman-generator/lib/base.js:232:45)
    at module.exports.generators.Base.extend.prompting(<line-number-for-my-code>)
```

Is this reproducible for anyone else?

**Comment by m-ux** [comment]
Actually, now it looks like just the original promise is firing, but anything that comes after (i.e. any `then`s or any future contexts in the run queue) aren't firing in **v0.23.0**.  Starting to think this could be something on my end...

**Comment by SBoudrias** [comment]
You need to bump `yo` -> `npm update -g yo`

**Comment by m-ux** [comment]
😞 thanks

**Comment by sgen** [comment]
Getting this error in 0.23.2 with the same example

**Comment by SBoudrias** [comment]
@sgen chances are you have multiple yo or npm install, so you keep using the old version even though you installed a new one.

**Comment by sgen** [comment]
Yup.

(sudo) npm dedupe -g fixed it might want to add that to you SO answer too.
