### ISSUE TITLE
yo:app running time is very long

### ISSUE THREAD

**Issue by noyobo** [yeoman/generator#932]
env
- node: v5.2.0
- yo: 1.8.2
- yeoman-generator: 0.23.3

I'm just `yo generator` to get a **generator-abc**

when `yo abc`, but that run time is very long

![](https://img.alicdn.com/tps/TB10rFMJVXXXXbYXpXXXXXXXXXX-1562-966.png)

15:46:03 - 15.47:24

**Comment by SBoudrias** [comment]
We can't really help you with that without any details or performance analysis on your part.
