### ISSUE TITLE
npmInstall() silently?

### ISSUE THREAD

**Issue by unional** [yeoman/generator#933]
`this.npmInstall(dependencies, { 'save-dev': true, 'silent': true });` doesn't work.

btw, the website shows `this.npmInstall(deps, { 'saveDev': true})` which does not work. `save-dev` does.

**Comment by unional** [comment]
Got it to work. But keep this open for updating the website

`this.npmInstall(dependencies, { 'save-dev': true, 'progress': false, 'loglevel': 'silent' })`

**Comment by SBoudrias** [comment]
Mind sending a PR with the fix?

**Comment by mischah** [comment]
PR over here: https://github.com/yeoman/yeoman.github.io/pull/680
