### ISSUE TITLE
Warning on dependency: cross-spawn-async 

### ISSUE THREAD

**Issue by LostInBrittany** [yeoman/generator#934]
When trying to install yeoman-generator, I get this warning:

```
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
```

It comes from the version of `cross-spawn` used in `yeoman-generator`, `cross-spawn` 2.0.0, that depends on `cross-spawn-async`. Newer versions of `cross-spawn` doesn't have this dependency.

Could you update `cross-spawn` to 3.0.0 or there is some problem with this version?

**Comment by SBoudrias** [comment]
Pr welcomed.

**Comment by LostInBrittany** [comment]
I'll try to do it later today. Do you have some contributing guidelines I should be aware of besides those of http://yeoman.io/contributing/ ?

**Comment by vintprox** [comment]
Well, it's back to our days:
![console output](https://user-images.githubusercontent.com/5708819/57191863-d68b1d80-6f32-11e9-8a84-392d6c6aee62.png)
