### ISSUE TITLE
version 0.21.1 is broken by break change

### ISSUE THREAD

**Issue by jannyHou** [yeoman/generator#936]
[`generator-loopback`](https://github.com/strongloop/generator-loopback) is depending on yeoman-generator@0.21.1 and keeps failing on test cases after yeoman-environment updated. 

It seems version 0.21.1 only compatible with yeoman-environment@1.5.3
Could you create a patch to downgrade yeoman-environment for 0.21.1? Thanks!

**Comment by SBoudrias** [comment]
Are you not able to update to `yeoman-test`?

**Comment by jannyHou** [comment]
@SBoudrias when I install yeoman-generator@0.21.1 it automatically installed yeoman-environment@1.6.1. But actually I believe yeoman-environment@1.5.3 it the one which compatible with 0.21.1.
Because 1.5.3 doesn't include the break change from inquirer.

**Comment by jannyHou** [comment]
The updated yeoman-test doesn't work on our CI. See https://github.com/strongloop/generator-loopback/pull/181

**Comment by SBoudrias** [comment]
@jannyHou looks like the patch is just not working, doesn't mean yeoman-test doesn't work on your CI.

I'll see if I can patch the old version when I have a minute. But that's not exactly a priority for me ATM.

**Comment by jannyHou** [comment]
@SBoudrias Thank you for letting me know. Would you mind if I create a patch to get it work?

**Comment by SBoudrias** [comment]
@jannyHou That would make this happens faster. Just link me to a branch on your fork and I'll merge as a new branch here.

**Comment by eddiemonge** [comment]
@jannyHou whats still left to do? (besides me updating generator-loopback)

**Comment by SBoudrias** [comment]
I believe we fixed that :)
