### ISSUE TITLE
npm "latest" distribution tag pointed to old version

### ISSUE THREAD

**Issue by TimothyGu** [yeoman/generator#939]
```sh
$ npm v yeoman-generator versions | tail -2
  '0.23.3' ]

$ npm v yeoman-generator dist-tags
{ latest: '0.21.2', pre: '0.18.0-pre.3' }
```

This means that when a user does `npm i yeoman-generator`, the version installed is different from the [online documentation](http://yeoman.io/authoring/). In particular, the behavior of `Base#prompt` is different from 0.21.2 to 0.23.3. While the [documentation](http://yeoman.io/authoring/user-interactions.html) says that the function returns a promise, it in actuality returns `this` on 0.21.2. OTOH, the [API reference](http://yeoman.io/generator/Base.html#prompt) is for the old version.

If this has been already documented somewhere, I apologize in advance; but it would probably be best if a person just getting started with Yeoman doesn't have to spend half an hour looking at Git blame for why the code isn't working.

**Comment by SBoudrias** [comment]
Fixed.

**Comment by TimothyGu** [comment]
Thanks!
