### ISSUE TITLE
unable to execute this.on('end') method

### ISSUE THREAD

**Issue by kkorada** [yeoman/generator#942]
i have two methods install and end in my generator

```
install: function () {
	var injectDependenciesAndConstants = function () {
		this.spawnCommand('gulp', ['ngconstant:dev', 'wiredep:app']);
	};
	this.installDependencies({
		callback: injectDependenciesAndConstants.bind(this)
	}
	);
},
end: function () {	  
	  this.on('end', function () {
                this.log(chalk.green('We are all done ! \nEnd Of Generator.'));
	  });	   
}
```

but **We are all done ! \nEnd Of Generator** is not comming in the end, my generator is ending up with gulp output

**Comment by eddiemonge** [comment]
you dont need to add the listener there since its already in the end method. if you moved that listener up it would fire. at the point you have at, the event has already fired. I think.

**Comment by SBoudrias** [comment]
Yeah, that looks correct. Basically, events are still there for backward compatibility. You shouldn't use them if you weren't using them before.
