### ISSUE TITLE
Dependencies installation command incorrect on Windows

### ISSUE THREAD

**Issue by scottaddie** [yeoman/generator#943]
After using a Yeoman generator to scaffold a project, I noticed the following output in the terminal:
![untitled](https://cloud.githubusercontent.com/assets/10702007/16102442/04a47ec4-3335-11e6-9250-72aca0b82bdf.png)

Since I'm using Windows, I would have expected a double ampersand to separate the `npm install` and `bower install` commands. If this only affects Windows, could we add a platform check like the following?

```javascript
var isWin = /^win/.test(process.platform);
```

That piece of info could then be used to generate either a single or a double ampersand in the `installDependencies` function: https://github.com/yeoman/generator/blob/master/lib/actions/install.js#L127.

**Comment by SBoudrias** [comment]
Oh, it's double `&&` on every platform. I wonder if that's a bug or the original author considered the ampersand a stylistic separator.

Mind sending a PR fixing this bug?

**Comment by scottaddie** [comment]
The last sentence in the screenshot above makes me believe that I should be able to copy and paste the command. I'll submit a PR to convert to double ampersand.

**Comment by scottaddie** [comment]
Closing this issue, as the fix was merged.
