### ISSUE TITLE
Missing files when publish

### ISSUE THREAD

**Issue by maasencioh** [yeoman/generator#946]
Hello, in [this generator](https://github.com/mljs/generator-mljs-packages) we're trying to generate a basic template, I tested locally and works fine, but I think that when we publish it, the files gitignore, travis and eslintrc are ignored.

Is there any workaround for this problem or something that we're missing?

**Comment by SBoudrias** [comment]
This seems related to npm. Maybe it ignores some dotfiles?

Are you sure these files are not ignored by `.npmignore` and that they're defined in your `package.json` `files` array?

**Comment by maasencioh** [comment]
Yes I'm pretty sure, that's the weird part and I don't have a clue what could be the problem

**Comment by SBoudrias** [comment]
Maybe refer to npm documentation https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package or ask their community for further support if you can't find out what's going on.

**Comment by iamstarkov** [comment]
@maasencioh  is that a problem, that all development-related files are excluded from published tarball?
this code in your pkg [`"files": ["src"]`](https://github.com/mljs/generator-mljs-packages/blob/master/templates/package.json#L6-L8) is the reason

**Comment by maasencioh** [comment]
@iamstarkov, that was it! thanks a lot
