### ISSUE TITLE
[Deprecation] Remote module is deprecated

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator#949]
`this.remote()`, `this.fetch()`, `this.extract()` (and `this.cacheRoot()`) are all deprecated.

### Preferred solution - Use npm

The legacy remote module is downloading a github repo everytime a user runs your generator. A better and easier solution is to rely on npm to fetch remotes.

1. Install your repo [as a npm module](https://docs.npmjs.com/cli/install) (npm can fetch tarballs and any git repo)

```
{
  "dependencies": {
    "github-repo": "github:yeoman/generator#version",
    "tarball": "http://example.com/resource.tar"
  }
}
```

2. Directly copy from the `node_modules` directory:

```
yeoman.base.extend({
  write: function () {
    this.fs.copy(
      path.join(__dirname, '../node_modules/package-name/**'),
      this.destinationPath()
    );
  }
});
```

### Backward compatibility

If you want an easy way to migrate a generator to the new version, you can rely on [yeoman-remote](https://github.com/yeoman/yeoman-remote). This package contains the legacy remote code, so you can use it almost as-is.

### Questions

For any issues migrating, feel free to post below for further support.

**Comment by adamgruber** [comment]
The benefit of `this.fetch()` and `this.extract()` are that they ensure you have the latest code for a dependency at the time you run the generator. Using your preferred solution gets the latest dependency code when you install the generator but you cannot be sure that you have the latest  dependency code at runtime.

A good example of this would be a generator that is used to start a new project based on a boilerplate. If I include the boilerplate as a dependency:
```
{
  dependencies: {
    "boilerplate": "some/path/to/code"
  }
}
```
Then when I install my generator, I will get the "boilerplate" dependency at that point in time. If any changes are made to "boilerplate" afterwards and I try to run the generator, I will not have the latest code from "boilerplate".

So, with these methods deprecated, what's the best way to ensure a generator has the latest version of a package at runtime?

**Comment by SBoudrias** [comment]
@adamgruber well the counter point of that is that you have no guarantee your generator code will be compatible with the updated boilerplate. My suggestion would be to update the version (or git sha) from your boilerplate dependency and push a new generator version out. This also has the benefit that the generated code won't change magically when running the same version of a generator.

Otherwise, using the `yeoman-remote` package will work.

**Comment by Tanimodori** [comment]
Using npm to handle git repos have a significant downside: It will execute `build`, `install` and 
 some other scripts defined in that repo's `package.json` [(docs)](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#git-urls-as-dependencies)


> When installing from a `git` repository, the presence of certain fields in the `package.json` will cause npm to believe it needs to perform a build. To do so your repository will be cloned into a temporary directory, all of its deps installed, relevant scripts run, and the resulting directory packed and installed. 
>
> This flow will occur if your git dependency uses `workspaces`, or if any of the following scripts are present:
> * `build`
> * `prepare`
> * `prepack`
> * `preinstall`
> * `install`
> * `postinstall`
>
> If your git repository includes pre-built artifacts, you will likely want to make sure that none of the above scripts are defined, or your dependency will be rebuilt for every installation.

Afaik this behavior has **NO workarounds**. You can create a fork of the repo you want to download and edit the `package.json`, but it needs to be manually update to keep track of upstream and edit it again in the generator to restore your change. I don't call it a workaround.

As for `yeoman-remote`, it is not maintained anymore and there's a bug in its dependencies (see https://github.com/yeoman/yeoman-remote/issues/6)

Any good suggestions as of 2022? @SBoudrias
