### ISSUE TITLE
Crash if calling diff on a deleted file

### ISSUE THREAD

**Issue by cbornet** [yeoman/generator#950]
After calling `this.fs.delete(foo.txt)`
The generator asks 

```
conflict foo.txt
? Overwrite foo.txt? (Ynaxdh)
```

Then if you chose `d` to show the diff, the generator crashes with `TypeError: Cannot read property 'length' of null`

This is because newFileContents is null in binary-diff.js and a call to newFileContents.length is made.

Also note that the existing foo.txt is a text file so the text diff should have been used instead of the binary but `istextorbinary.isBinarySync(undefined, newFileContents)` returns true.

**Comment by cbornet** [comment]
Even if testing isBinarySync correctly for null content, the generator will then crash calling ```this.adapter.diff(existing.toString(), file.contents.toString());```. So the best solution would probably to replace null file.contents by ```''```. I'm not sure where this should be done...

**Comment by SBoudrias** [comment]
`this.adapter.diff(existing.toString(), (file.contents || '').toString());` ?
