### ISSUE TITLE
When I run yeoman generator, in the selection part the up & down arrow keys do not function.

### ISSUE THREAD

**Issue by Brian1111** [yeoman/generator#951]
I ran the following yeoman generators: (1) meanjs, and (2) angular-fullstack on Gitbash terminal on Windows 10.  I have installed the latest version of every software, including Gitbash & Node.js, i.e., v 6.3.  At some point after running yeoman, I have  to select options with up and down arrow keys, but the arrow keys do not function.  Normally the arrow keys do work on Gitbash, but they do not work on Yeoman generator only.

**Comment by SBoudrias** [comment]
Node broke the readline on Windows. Try with a non-broken version https://github.com/nodejs/node/issues/5384

**Comment by Brian1111** [comment]
Here I found the solution.  The arrows and installation work very well on Windows Powershell, but they do not work on Git terminal.  The problem is with Git terminal, not Node.js.  Yeoman generator is not compatible with Git terminal.

**Comment by fishenal** [comment]
seems like, bash-shell on windows has this issue. 
MobaXterm on windows not work.
