### ISSUE TITLE
Can we use mem-fs 2.3.0?

### ISSUE THREAD

**Issue by stephanebruckert** [yeoman/generator#952]
This release adds support for glob options to copyTpl (previously these options were only available using copy) 

https://github.com/SBoudrias/mem-fs-editor/releases/tag/v2.3.0.

We are currently using 2.0.0 from mid-2015.

**Comment by SBoudrias** [comment]
We're using `^2.0.0` which mean we're using 2.3.0 - See more about how semver works http://semver.org/
