### ISSUE TITLE
Catching SIGINT signal.

### ISSUE THREAD

**Issue by urosjarc** [yeoman/generator#958]
I'm writing generator and i'm wondering how can I catch a SIGINT and similar signals in
generator it self while running with `yo my-generator`?

**Comment by SBoudrias** [comment]
We don't expose helpers for that, but the process object is globally accessible in Node. https://nodejs.org/api/process.html

**Comment by urosjarc** [comment]
The problem is that I can catch only exit signal but not other one... I will provide with some code example... soon.

**Comment by SBoudrias** [comment]
Do you have code example yet?
