### ISSUE TITLE
custom generator is not showing in the yeoman

### ISSUE THREAD

**Issue by mahapatrakamlesh** [yeoman/generator#960]
I had created the custom generator by the name "generator-kamlesh". I had publish it on the npm repository but in the yeoman.io website its not getting listed. Kindly do the needfull.

**Comment by mischah** [comment]
Hej @mahapatrakamlesh ,

I can see it here right now 👌 
http://yeoman.io/generators/

Issue can be closed.

**Comment by mahapatrakamlesh** [comment]
Hi

Thanks For resolving the issue.

**Comment by mischah** [comment]
I didn't resolve it :smirk: 
Guess it was just a matter of time.
