### ISSUE TITLE
Published a generator - does not end up in the list

### ISSUE THREAD

**Issue by wkamir** [yeoman/generator#961]
Hi,

I published a generator to npm yesterday - the name is "generator-dotnetcore-angular2-express-mongodb".  I also added the property keyword "yeoman-generator" to package.json.

On the generators-page it is claimed that the list is updated every hour - so I thought it might be online by now. Is something wrong with my generator? Or is the list not updated anymore?

Thanks,
Wolfgang

**Comment by mischah** [comment]
Hej @wkamir,

I can see it here right now 👌 
http://yeoman.io/generators/

Issue can be closed.

**Comment by wkamir** [comment]
Indeed it can - thank you!
