### ISSUE TITLE
Update Documentation to latest version of Codebase

### ISSUE THREAD

**Issue by migaber** [yeoman/generator#962]
latest build of documentation is 21 Feb and it didn't reflect the deprecation some methods like NamedBase. so please update the build to latest version

**Comment by mischah** [comment]
I thought that would be an easy PR which I could handle in a couple of minutes:

1. Update the API docs by running `npm run doc` in this repo
2. Override the content of the `generators` directory the website repo

But I didn’t find a place to update the docs the over here: https://github.com/yeoman/yeoman.github.io/tree/source/app

Nor I found an own repo for storing the docs.

So I keep on wondering where they are located :see_no_evil:

**Comment by SBoudrias** [comment]
@mischah It's in the `gh-pages` branch of this repository.

**Comment by mischah** [comment]
Ah. That totally makes sense :grinning:

**Comment by mischah** [comment]
PR landed 🚀
