### ISSUE TITLE
Feature: New installation method for Yarn

### ISSUE THREAD

**Issue by mischah** [yeoman/generator#964]
Hej,

I would love to have a [Yarn]() installation method in addition to `bowerInstall` and `npmInstall` 💖 

Would you accept a pull request for that feature?

Yours, Michael

**Comment by nusu** [comment]
+1

**Comment by SBoudrias** [comment]
FWIW, you can use `runInstall()` right now to install packages using yarn. Maybe we should wait a bit to provide it as part of the core library as it'll be a lot of open issues asking us why the command fail when yarn is not installed.

**Comment by mischah** [comment]
> FWIW, you can use `runInstall()` right now to install packages using yarn.

Yeah. I know 👌 

But `runInstall()` doesn’t provide a callback function to the case Yarn isn’t installed, right?

> Maybe we should wait a bit to provide it as part of the core library as it'll be a lot of open issues asking us why the command fail when yarn is not installed.

My idea was to have a `yarnInstall` method which:
+ checks if yarn is installed 
  + installs with `yarn install` in case yarn is installed
  + installs with `npm install` if yarn isn’t installed

Could be possible because of the compatibility between npm and Yarn.

**Comment by mischah** [comment]
Okay. Might cause problems when passing yarn options that npm doesn’t have.

And there a a few :dizzy_face:

What about to provide an optional param for the new `yarnInstall` which is a boolean like `fallbackToNpmInstall`. So authors of generators are aware of this drawback.

**Comment by mischah** [comment]
Just throwing in ideas.

**Comment by sindresorhus** [comment]
Maybe a more generic method `.installDependencies()` that uses `yarn` when available, otherwise `npm`. With `yarnArg` and `npmArg` options, in case you need to specify arguments for either.

**Comment by mischah** [comment]
There is already a method called `installDependencies()` :sunglasses: 
Lets sum up the current state. We now have:

+ `bowerInstall()`
  - installs with bower`
+ `npmInstall()`
  - installs with bower
+ `installDependencies()`
  - runs npm and bower
+ `runInstall()`
  - runs the install command for a given installer
  - used by `bowerInstall()` and `npmInstall()`

See: http://yeoman.io/generator/actions_install.html

In addition one could use any CLI installer with `spawnCommand()` like described here: http://yeoman.io/authoring/dependencies.html

---

Just realized that I’v mistaken `spawnCommand()` with `runInstall()` in my answer to @SBoudrias above:
> But `runInstall()` doesn’t provide a callback function to the case Yarn isn’t installed, right?

`runInstall()` do provide a callback :ok_hand:

**Comment by mischah** [comment]
But maybe Simon is right that it might be a bit early to generally support Yarn.

Cause Yarn will cause trouble for projects that are using bower in addition to npm.

➡️  It deletes the `bower_components` directory. See here: https://github.com/yarnpkg/yarn/issues/616

**Comment by thymikee** [comment]
@mischah Bower support is now [removed from Yarn](https://github.com/yarnpkg/yarn/pull/1441) (I believe it will land with the latest release)

**Comment by sindresorhus** [comment]
I think we should do the following:

- Deprecate `bowerInstall()` (Bower is dead)
- Add `yarnInstall()`
- Change `installDependencies()` to not use `bowerInstall()`, but to use Yarn when available, otherwise npm. With `yarnArgs` and `npmArgs` options, in case you need to specify arguments for either.

This would be a breaking change, but for the better.

**Comment by Borjagodoy** [comment]
I don't know if the deprecated bower install is a good option.

I think that we can add a new method yarnInstall() and  the user can chose between npm and yarn across the option parameter.

if the user want use yarn in the option object set yarn: true, else set npm: true.

**Comment by mischah** [comment]
First I thought think it’s to early to deprecate `bowerInstall()` and get rid of it within `installDependencies()` because Bower isn’t dead and is still used widely.

But Bower has no future and will day sooner than later.

So yes. Im with that:
> + Deprecate bowerInstall() (Bower is dead)  
> + Add yarnInstall()
> + Change installDependencies() to not use bowerInstall(), but to use Yarn when available, otherwise npm. With yarnArgs and npmArgs options, in case you need to specify arguments for either.

Authors of generators can still use Bower but with that breaking change it’s clear that have to switch. 

I could prepare a PR if the rest of @yeoman is okay with that breaking change.

**Comment by mischah** [comment]
Oh, I just recognized that there is a PR in the making over here: #974

**Comment by mischah** [comment]
Travis also supports Yarn now 🙀 

@Borjagodoy What’s the status with your PR over here: #974?

**Comment by mischah** [comment]
The Yarn install method is in master with 4eccb2a81b4fdb652ebf618a3dd7be7aa7950a96

Question:
Who will add this to the website?
https://github.com/yeoman/yeoman.github.io/blob/source/app/authoring/dependencies.md

**Comment by mischah** [comment]
> Question:
> Who will add this to the website?
> https://github.com/yeoman/yeoman.github.io/blob/source/app/authoring/dependencies.md

PR regarding the website over here https://github.com/yeoman/yeoman.github.io/pull/699
