### ISSUE TITLE
Default conflict resolution to not override user code

### ISSUE THREAD

**Issue by giovannicandido** [yeoman/generator#966]
Provide a config to the conflicter default to not override user files

Something like:

    this.conflicter.defaultResolution = 'n';

Current it defaults to override files

**Comment by SBoudrias** [comment]
The user can run with the `--force` flag if they want to force overwrite everything.

**Comment by giovannicandido** [comment]
And the oposite?

**Comment by SBoudrias** [comment]
The prompt offer the option to skip all.

**Comment by giovannicandido** [comment]
I should be more specific, sorry:

I'm trying to prevent the user from accidentally overriding the file. If the user just press enter in the prompt, the default is to override the file.

As a generator writer, I would like to change the default but keep the prompt.

**Comment by SBoudrias** [comment]
I see, this is not possible. I don't think this is a feature we'd like to add. Consistency in this case is better for end user as it's the same across generators. Allowing generator to configure this option would break user expectations.

**Comment by giovannicandido** [comment]
Ok. Consistency is best.

Thank you for your time and consideration.
