### ISSUE TITLE
Enhancement: Generate docs in gh-pages branch with every commit on master branch

### ISSUE THREAD

**Issue by mischah** [yeoman/generator#968]
Hej, wouldn’t that be useful?

This could be automated via Travis and would prevent outdated docs like described in #962

I could submit a PR to handle this 😘 

Yours, Michael

**Comment by SBoudrias** [comment]
Totally, see this ticket over here: https://github.com/yeoman/generator/issues/673

**Comment by SBoudrias** [comment]
@mischah Right now it looks like it pushes for each travis run, it should probably only from a single process/node version.
