### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by tonynorte** [yeoman/generator#979]
hi, I try to install this module but when I run this command:
npm i yeoman-generator

I just revive  "cb() never called!", I had used this package before and it is the first time than that happen, I have installed:
+node 5.9.1

thanks.

**Comment by SBoudrias** [comment]
Can you paste the error trace?

**Comment by tonynorte** [comment]
![image](https://cloud.githubusercontent.com/assets/4627129/20575738/29ccda88-b180-11e6-990f-96b17ec61367.png)

**Comment by SBoudrias** [comment]
Looks like that's an error with npm itself. Maybe try with the latest version? Otherwise you should open a bug report on their tracker.

Hope this helps a little.

**Comment by tonynorte** [comment]
hum yes I have installed the latest version, but thanks anyway.
