### ISSUE TITLE
Improve support for Yarn

### ISSUE THREAD

**Issue by mischah** [yeoman/generator#980]
Hej, 

this is a follow up to #964.
I just checked changes of 4eccb2a and I see a problem with how Yarn install is implemented. Or let’s say its missing one thing:

Dependencies should be installed with `yarn add lodash` or `yarn add --dev lodash`.
See: https://yarnpkg.com/en/docs/cli/install

Installing dependencies with `yarn install lodash --save` or `yarn install lodash --save` works for now but is deprecated since the first public release of Yarn:
![image](https://cloud.githubusercontent.com/assets/441011/20640893/fdcc846a-b3eb-11e6-8309-b2d71b857189.png)

So it’s just a matter of time until it breaks.

We should extend the [`runinstall` method](https://github.com/yeoman/generator/commit/4eccb2a81b4fdb652ebf618a3dd7be7aa7950a96#diff-c9a43560dd6d606dc7759d0eda3fb582L25) to call `yarn add` instead of `yarn install` for installing dependencies.

**Comment by SBoudrias** [comment]
Yup, totally sould

**Comment by mischah** [comment]
Nice 💖
