### ISSUE TITLE
this.prompt never resolves its promise

### ISSUE THREAD

**Issue by selbekk** [yeoman/generator#985]
I have the following code running on node 7:

```javascript
prompting() {
  const prompts = [
    {
	type: 'input',
	name: 'name',
	message: 'What is the official name of your component?',
    },
    {
	type: 'input',
	name: 'description',
	message: 'Describe it to me!',
    },
  ];

  return this.prompt(prompts)
    .then(answers => {
	this.answers = answers;
	this.log('Thanks! Now I\'m ready to create your project');
    });
}
```
The questions show up and everything is fine when filling them out.

However, the `.then` clause is never run, which leads me to think that the `this.prompt` method never resolves the promise it returns.

This worked before the breaking change in v0.23 (please consider semver-ing for the future!), when `this.prompt` accepted a callback. 

What am I doing wrong?

**Comment by selbekk** [comment]
I noticed that using the callback approach still works. Weirdness. Would still love an explanation though,

**Comment by zckrs** [comment]
You can show here if you want a example https://github.com/FountainJS/fountain-generator/blob/master/lib/Base.js#L111

**Comment by selbekk** [comment]
Looks like this not working was my bad - had the wrong version of yeoman locally. Sorry about this - closing the issue.

**Comment by zckrs** [comment]
:trollface:
