### ISSUE TITLE
Fix deploying the docs with every Git tag

### ISSUE THREAD

**Issue by mischah** [yeoman/generator#986]
Doesn’t work properly right now cause this doesn’t match 🙈

https://github.com/yeoman/generator/blob/master/deploy.sh#L11

**Comment by mischah** [comment]
Did a manual update for now.

**Comment by SBoudrias** [comment]
I think I just fixed this today. :)

**Comment by mischah** [comment]
@SBoudrias Thanks for the fix. Was on my imaginary To Do list for quite a while :pensive:

Sorry for being pretty inactive since the beginning of 2017. But with the new born and the 2 year old there is unfortunately not much time and energy left beside work 😖
