### ISSUE TITLE
Is `installDependencies` deprecated?

### ISSUE THREAD

**Issue by lixinliang** [yeoman/generator#990]
My generator like this:
```js
generators.Base.extend({
  install () {
    this.installDependencies({
      npm: true,
      yarn: false,
      bower: false,
      skipInstall: false,
      callback () {
        log('Dependencies installed!');
        process.exit(1);
      },
    });
  }
});
```
And it's not work.

Its version is:
```json
{
  "yeoman-generator": "^0.24.1"
}
```

**Comment by SBoudrias** [comment]
What is the behavior your expect? What is the behavior you see right now? `installDependencies` does work.

You can see the api documented here http://yeoman.io/generator/actions_install.html#.installDependencies

**Comment by lixinliang** [comment]
Sorry, it's my mistake. That's work indeed.

But, in the following case, `installDependencies`  seems not work.
```js
generators.Base.extend({
    install () {
        let choices = [
            'Link to the shared node_modules',
            'Install here',
        ];
        this.prompt([
            {
                type : 'list',
                name : 'install_node_modules',
                message : 'Link to shared node_modules or Install node_modules here?',
                choices,
            },
        ]).then(( answers ) => {
            if (answers.install_node_modules == choices[0]) {
                fs.symlinkSync(path.join(__dirname, './templates/node_modules'), 'node_modules');
                log('> finished');
                process.exit(1);
            } else {
                this.installDependencies({
                    npm : true,
                    bower : false,
                    skipInstall : false,
                    callback () {
                        log('> finished');
                        process.exit(1);
                    }
                });
            }
        });
    },
});
```

I want to `installDependencies` action according to the answers of prompt.

![image](https://cloud.githubusercontent.com/assets/9375027/21473646/928e77b6-cb4d-11e6-916d-467eab2ee771.png)

**Comment by SBoudrias** [comment]
Any chance there's no package.json in the folder where npm is invoked and it noop?

**Comment by lixinliang** [comment]
`package.json` was copied in `writing` stage.

BTW, I would use `yeoman` to reinstall my node_modules.
`package.json` is already here.
![image](https://cloud.githubusercontent.com/assets/9375027/21488529/d953c736-cc1b-11e6-80fe-5f2cd1cc5234.png)

Do you have any idea?

**Comment by lixinliang** [comment]
My yeoman version:
```json
{
  "yeoman-generator": "^1.0.1"
}
```
And `this.installDependencies` is work.

However, I use `this.installDependencies` in a `then` callback of `Promise`, like the following example:
```js
module.exports = class Generator extends Base {

    // some code

    install () {
        this.prompt(/* options */).then(( answers ) => {

            // some code

            this.installDependencies({
                npm : true,
                bower : false,
                skipInstall : false,
                callback () {},
            });
            
        });
    },
};
```

Now, `this.installDependencies` isn't work.

It seems a problem about `child_process` and `Promise`.
`this.installDependencies` already called, but `child_process` would be killed.

I'm not sure the above conclusion.
But, there's no doubt that it's not an issue of `yeoman`.

**Comment by SBoudrias** [comment]
You need to `return this.prompt()` to have Yeoman waits for the prompt answers. Otherwise the Yeoman process will be done before you get the answers.

Also, no need to call `this.installDependencies` in the prompt promise resolution. This function can be called anywhere.
