### ISSUE TITLE
Using npm install in case yarn isn’t available?

### ISSUE THREAD

**Issue by mischah** [yeoman/generator#991]
Hej, 

Using the yarn install method if Yarn isn’t installed obviously fails.

Right now I’m catching the error in v2.0.0 of [generator-http-fake-backend](https://github.com/micromata/generator-http-fake-backend/releases) and add a little text to the default error message:

![](https://cloud.githubusercontent.com/assets/441011/21367248/b37b5984-c6fd-11e6-8cf0-c255ad551cc9.png)

But to increase the UX I would like to use npm in case Yarn isn’t available.

I could check if Yarn is available within the code of my generator. But it feels to me that this should be handled by `yeoman-generator`.

Any opinions on that?

Cheers, Michael

**Comment by SamHH** [comment]
I have a simple solution FWIW: https://github.com/imperodesign/generator-impero/blob/development/generators/app/index.js#L329

Not sure about integrating into Yeoman. Are there ever any situations where somebody with Yarn might choose to use npm for installing modules instead?

**Comment by SBoudrias** [comment]
I think this makes sense. We might want to make this an option though - like `fallbackToNpm`.

Then try to run yarn and if an error occurs, try npm. If yarn fail, we should display a warning, and if npm also fail, then we should only show the yarn failure message.

**Comment by mischah** [comment]
Good idea. I think `fallbackToNpm` should default to `true`. Am I right?

**Comment by addyosmani** [comment]
I personally think defaulting it to true makes sense here.

**Comment by hoanguyen311** [comment]
yes, please make it happen
