### ISSUE TITLE
Question: npmInstall package from github

### ISSUE THREAD

**Issue by jmls** [yeoman/generator#992]
I've been playing with the npmInstall() and got this sort of thing running just fine:

```
install: function () {
    this.npmInstall([
      'chai',
      'mocha',
```

However, there is a package that I need to install from a github repo. Normally I would use

```
npm install git+ssh://git@github.com/<somerepo>
```

is it possible to achieve that in npmInstall() ?

**Comment by SBoudrias** [comment]
`this.npmInstall(['git+ssh://git@github.com/<somerepo>'])` should just work.

Also, why not just putting it in the generated `package.json` file directly?

**Comment by eddiemonge** [comment]
@jmls ^^

**Comment by jmls** [comment]
indeed, it worked for me. thanks;
