### ISSUE TITLE
this.directory not running process

### ISSUE THREAD

**Issue by jmls** [yeoman/generator#993]
I have this code

```
this.directory(this.sourceRoot(),this.destinationRoot(),function(body,src,dst,encOpt) {
    console.log("xxx",sourcePath,encodingOptions);
    return body;
});
```
Whilst it **does** copy the folder structure
![image](https://cloud.githubusercontent.com/assets/929523/21713464/0ab09b78-d3f2-11e6-8fb0-f3e0bbd44fa5.png)

it doesn't log the "xxx" as I expected it to. However, the files do seem to be passed through ejs.

If I remove the process function entirely, I get the same end result

so, I have 2 questions
#1 why is the process function of this.directory not being run
#2 how can I pass options to ejs using *this.directory()* ?

**Comment by SBoudrias** [comment]
Not sure, `this.directory` has been completely remove from 1.0. It's a very old function and wasn't maintained anymore.

Try using `this.fs.copyTpl()`. https://github.com/SBoudrias/mem-fs-editor#copytplfrom-to-context-templateoptions--copyoptions
