### ISSUE TITLE
Using remote and deleting folder that is in cache

### ISSUE THREAD

**Issue by miguelsmuller** [yeoman/generator#998]
I'm using [yeoman-remote](https://github.com/yeoman/yeoman-remote) to download a zip. The download and extraction are completed normally with no error.

The problem that happens is that I need to delete some unnecessary files and folders in the process. The files are deleted normally, but the folders are not deleted and no errors are reported.

I do not know how to solve this problem. I also do not know if I'm doing something wrong. Has anyone had a similar case? Can I get a solution to this situation?

The code I'm using follows below
```
remote('https://wordpress.org/latest.zip', function (err, cachePath) {

	this.fs.copy(
	  path.join(cachePath, '**'),
	  this.destinationPath('public/'),
	  { globOptions: { dot: true } }
	);

	// These lines work	
	this.fs.delete(this.destinationPath('public/license.txt'));
	this.fs.delete(this.destinationPath('public/readme.html'));
	this.fs.delete(this.destinationPath('public/wp-content/plugins/hello.php'));

	// These lines do not work
	this.fs.delete(this.destinationPath('public/wp-content/themes/**/*'));
	this.fs.delete(this.destinationPath('public/wp-content/plugins/akismet/'));

	done();
}.bind(this));
```

**Comment by SBoudrias** [comment]
This issue has pretty much the same root as https://github.com/SBoudrias/mem-fs-editor/issues/61

Until a fix is created, you'll need to delete each files individually.

**Comment by miguelsmuller** [comment]
I've been reading.
Complicated also because I can not use other packages type [fs-extra](https://www.npmjs.com/package/fs-extra) to accomplish this function.
