### ISSUE TITLE
Improve "skip install" option name

### ISSUE THREAD

**Issue by sholladay** [yeoman/generator#999]
`--skip-install` is super useful. I am glad it is provided out of the box. I use it all the time when manually testing changes I've made to my prompts. But it is a bit weirdly named and more verbose than it needs to be.

I think it should be `--no-install` just like all other negated option names.

This would be both more intuitive and faster to type.

**Comment by mischah** [comment]
I don't feel that change. Other opinions?

**Comment by addyosmani** [comment]
I've personally always felt `--skip-install` was pretty clear. Perhaps we can keep this issue open a while to see if folks have strong opinions about it.

@mischah btw, did we give you access to the twitter account? We could probably use it more heavily to seek community input on issues like this :)

**Comment by mischah** [comment]
Hej @addyosmani 

> did we give you access to the twitter account? 

Nope. 

> We could probably use it more heavily to seek community input on issues like this :)

Good idea 👌
